#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build a clean app.js with proper quote handling."""
import os

# Use a simple approach: build each line with consistent quoting
# JS code uses SINGLE QUOTES for string delimiters
# HTML attributes inside JS strings use DOUBLE QUOTES
# This means: 'class="muted"' is correct
#             '<div class="chip">' + text + '</div>' is correct

lines = []

def w(s):
    lines.append(s)

w("/* TransMed frontend logic - simple and clean */")
w("(function() {")
w("  'use strict';")
w("")
w("  // --- DOM helpers ---")
w("  var byId = function(id) { return document.getElementById(id); };")
w("  var qs = function(sel) { return document.querySelector(sel); };")
w("  var qsa = function(sel) { return Array.from(document.querySelectorAll(sel)); };")
w("  var bindClick = function(el, handler) { if (el) el.addEventListener('click', handler); };")
w("  var bindChange = function(el, handler) { if (el) el.addEventListener('change', handler); };")
w("")
w("  // --- API base detection ---")
w("  // CSS selector: meta[name='api-base']")
w("  var metaApi = qs(\"meta[name='api-base']\");")
w("  var isPages = location.hostname.indexOf('github.io') !== -1;")
w("  var API = '';")
w("  if (metaApi) API = metaApi.getAttribute('content') || '';")
w("  else if (location.protocol === 'file:' || location.hostname === '127.0.0.1' || location.hostname === 'localhost') API = 'http://127.0.0.1:8000';")
w("")
w("  // --- Auth helpers ---")
w("  var TOKEN_KEY = 'transmed_token';")
w("  var USER_KEY = 'transmed_user';")
w("  var getToken = function() { return localStorage.getItem(TOKEN_KEY); };")
w("  var setToken = function(t) { t ? localStorage.setItem(TOKEN_KEY, t) : localStorage.removeItem(TOKEN_KEY); };")
w("  var getUser = function() { try { var raw = localStorage.getItem(USER_KEY); return raw ? JSON.parse(raw) : null; } catch(e) { return null; } };")
w("  var setUser = function(u) { u ? localStorage.setItem(USER_KEY, JSON.stringify(u)) : localStorage.removeItem(USER_KEY); };")
w("")
w("  // --- View switching ---")
w("  var navLinks = qsa('.nav-link');")
w("  var views = qsa('.view');")
w("  var setActive = function(view) {")
w("    views.forEach(function(v) { v.classList.toggle('active', v.dataset.view === view); });")
w("    navLinks.forEach(function(a) { a.classList.toggle('active', a.dataset.view === view); });")
w("    try {")
w("      if (view === 'hospitals') loadHospitals();")
w("      if (view === 'medication') loadMedications();")
w("      if (view === 'navigation') initNavigation();")
w("    } catch(e) { console.warn('setActive error:', e); }")
w("  };")
w("  navLinks.forEach(function(a) { bindClick(a, function() { setActive(a.dataset.view); }); });")
w("  qsa('[data-go]').forEach(function(btn) { bindClick(btn, function() { setActive(btn.dataset.go); }); });")
w("")
w("  // --- Login/Register modal ---")
w("  var authModal = byId('auth-modal');")
w("  var refreshAuthUI = function() {")
w("    var user = getUser();")
w("    if (byId('btn-login')) byId('btn-login').classList.toggle('hidden', !!user);")
w("    if (byId('user-chip')) byId('user-chip').classList.toggle('hidden', !user);")
w("    if (byId('user-email') && user) byId('user-email').textContent = user.email;")
w("  };")
w("  if (authModal) bindClick(authModal, function(e) { if (e.target === authModal) authModal.classList.add('hidden'); });")
w("  bindClick(byId('btn-login'), function() { if (authModal) authModal.classList.remove('hidden'); });")
w("  bindClick(byId('btn-logout'), function() { setToken(null); setUser(null); refreshAuthUI(); setActive('home'); });")
w("")
w("  var switchAuthTab = function(tab) {")
w("    qsa('.modal-tabs .tab').forEach(function(b) { b.classList.toggle('active', b.dataset.tab === tab); });")
w("    var l = byId('tab-login'); if (l) l.classList.toggle('hidden', tab !== 'login');")
w("    var r = byId('tab-register'); if (r) r.classList.toggle('hidden', tab !== 'register');")
w("    var msg = byId('auth-message'); if (msg) msg.textContent = '';")
w("  };")
w("  qsa('.modal-tabs .tab').forEach(function(btn) { bindClick(btn, function() { switchAuthTab(btn.dataset.tab); }); });")
w("")
w("  bindClick(byId('btn-do-login'), function() {")
w("    var email = byId('login-email') ? byId('login-email').value.trim() : '';")
w("    var pw = byId('login-password') ? byId('login-password').value : '';")
w("    var msg = byId('auth-message');")
w("    if (!email || !pw) { if (msg) msg.textContent = 'Please enter email and password'; return; }")
w("    fetch(API + '/api/auth/login', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({email: email, password: pw}) })")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        if (data && data.access_token) { setToken(data.access_token); setUser(data.user); refreshAuthUI(); if (authModal) authModal.classList.add('hidden'); setActive('home'); }")
w("        else { if (msg) msg.textContent = (data && data.detail) || 'Login failed'; }")
w("      }).catch(function(e) { if (msg) msg.textContent = 'Error: ' + e.message; });")
w("  });")
w("")
w("  bindClick(byId('btn-do-register'), function() {")
w("    var name = byId('reg-name') ? byId('reg-name').value.trim() : '';")
w("    var email = byId('reg-email') ? byId('reg-email').value.trim() : '';")
w("    var pw = byId('reg-password') ? byId('reg-password').value : '';")
w("    var lang = byId('reg-language') ? byId('reg-language').value : 'en';")
w("    var country = byId('reg-country') ? byId('reg-country').value.trim() : '';")
w("    var msg = byId('auth-message');")
w("    if (!name || !email || pw.length < 6) { if (msg) msg.textContent = 'Please fill all fields (min 6 char password)'; return; }")
w("    fetch(API + '/api/auth/register', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({full_name: name, email: email, password: pw, language: lang, country: country}) })")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        if (data && data.access_token) { setToken(data.access_token); setUser(data.user); refreshAuthUI(); if (authModal) authModal.classList.add('hidden'); setActive('home'); }")
w("        else { if (msg) msg.textContent = (data && data.detail) || 'Registration failed'; }")
w("      }).catch(function(e) { if (msg) msg.textContent = 'Error: ' + e.message; });")
w("  });")
w("")
w("  // --- Translate ---")
w("  bindClick(byId('btn-translate'), function() {")
w("    var txt = byId('src-text') ? byId('src-text').value.trim() : '';")
w("    var srcLang = byId('src-lang') ? byId('src-lang').value : 'en';")
w("    var tgtLang = byId('tgt-lang') ? byId('tgt-lang').value : 'zh';")
w("    var btn = byId('btn-translate');")
w("    var out = byId('tgt-text');")
w("    if (!txt || !out) return;")
w("    if (btn) { btn.disabled = true; btn.textContent = 'Translating...'; }")
w("    fetch(API + '/api/translate', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({text: txt, source_lang: srcLang, target_lang: tgtLang, medical_context: true}) })")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        out.textContent = data.translated_text || '(no translation)';")
w("        var c = typeof data.confidence === 'number' ? Math.round(data.confidence * 100) : 80;")
w("        var conf = byId('confidence-bar'); if (conf) conf.classList.remove('hidden');")
w("        var cv = byId('conf-value'); if (cv) cv.textContent = c;")
w("        var cf = byId('conf-fill'); if (cf) cf.style.width = c + '%';")
w("        var rv = byId('risk-value'); if (rv) rv.textContent = data.risk_level || 'low';")
w("        var rb = byId('btn-confirm-risk'); if (rb) rb.classList.toggle('hidden', data.risk_level !== 'high');")
w("        var ca = byId('conf-advice'); if (ca) ca.textContent = data.safety_advice || '';")
w("        var matched = byId('matched-terms');")
w("        if (matched) {")
w("          var items = (data.medical_terms || []).map(function(t) {")
w("            var def = t.definition ? ' ' + '\u00b7' + ' ' + t.definition : '';")
w("            return '<span class=\"chip\">' + t.term + def + '</span>';")
w("          }).join('');")
w("          matched.innerHTML = items ? '<div class=\"muted small\" style=\"margin-bottom:6px;\">Medical terms:</div>' + items : '';")
w("        }")
w("      }).catch(function(e) { out.textContent = 'Error: ' + e.message; })")
w("      .finally(function() { if (btn) { btn.disabled = false; btn.textContent = 'Translate'; } });")
w("  });")
w("")
w("  bindClick(byId('swap-lang'), function() {")
w("    var src = byId('src-lang'); var tgt = byId('tgt-lang');")
w("    if (src && tgt) { var v = src.value; src.value = tgt.value; tgt.value = v; }")
w("  });")
w("")
w("  // --- Symptom chips ---")
w("  var symptomBox = byId('symptom-chips');")
w("  if (symptomBox) {")
w("    ['headache', 'chest pain', 'cough', 'fever', 'stomach pain', 'back pain', 'skin rash', 'dizziness', 'fatigue', 'sore throat', 'shortness of breath', 'nausea', 'joint pain', 'anxiety'].forEach(function(txt) {")
w("      var el = document.createElement('button');")
w("      el.className = 'chip'; el.textContent = txt; el.type = 'button';")
w("      bindClick(el, function() { var t = byId('src-text'); if (t) t.value = txt; });")
w("      symptomBox.appendChild(el);")
w("    });")
w("  }")
w("")
w("  // --- Triage & hospitals ---")
w("  var lastHospitals = [];")
w("  bindClick(byId('btn-triage'), function() {")
w("    var symptom = byId('triage-input') ? byId('triage-input').value.trim() : '';")
w("    var el = byId('triage-result');")
w("    if (!symptom) return;")
w("    fetch(API + '/api/triage', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({symptoms: symptom, language: 'en'}) })")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        if (!el) return;")
w("        el.classList.remove('hidden');")
w("        var dept = data.department_en || 'General Medicine';")
w("        var deptZh = data.department_zh || '';")
w("        var urgent = !!data.urgent;")
w("        if (urgent) el.classList.add('urgent');")
w("        var label = urgent ? 'URGENT - please see a doctor ASAP' : 'Recommended';")
w("        var matched = '';")
w("        if (data.matched_symptoms && data.matched_symptoms.length) {")
w("          matched = '<div class=\"muted small\" style=\"margin-top:6px;\">Matched: ' + data.matched_symptoms.map(function(s){return '<span class=\"chip\">' + s + '</span>';}).join('') + '</div>';")
w("        }")
w("        var zhPart = deptZh ? ' ' + '\u00b7' + ' ' + deptZh : '';")
w("        el.innerHTML = '<div><span class=\"triage-label\">' + label + '</span></div>' +")
w("          '<strong>Department:</strong> ' + dept + zhPart + '<br>' +")
w("          (data.recommendation_en || 'Please consult a doctor.') + matched;")
w("      }).catch(function(e) { if (el) el.textContent = 'Triage service unavailable.'; });")
w("    loadHospitals();")
w("  });")
w("")
w("  function loadHospitals() {")
w("    var container = byId('hospital-list');")
w("    if (!container) return;")
w("    fetch(API + '/api/hospitals?limit=20')")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        var list = (data && data.hospitals) ? data.hospitals : [];")
w("        lastHospitals = list;")
w("        renderHospitals(list);")
w("      }).catch(function(e) { container.innerHTML = '<p class=\"muted\">Hospital list unavailable.</p>'; });")
w("  }")
w("")
w("  function renderHospitals(list) {")
w("    var container = byId('hospital-list');")
w("    if (!container) return;")
w("    if (!Array.isArray(list) || !list.length) { container.innerHTML = '<p class=\"muted\">No hospitals found.</p>'; return; }")
w("    container.innerHTML = list.map(function(h) {")
w("      var name = h.name || '';")
w("      var nameZh = h.name_zh && h.name_zh !== h.name ? ' ' + '\u00b7' + ' ' + h.name_zh : '';")
w("      var address = h.address || '';")
w("      var rating = typeof h.rating === 'number' ? h.rating.toFixed(1) : '-';")
w("      var wait = typeof h.wait_minutes === 'number' ? h.wait_minutes + ' min' : '-';")
w("      var dist = typeof h.distance_km === 'number' ? h.distance_km.toFixed(1) + ' km' : '-';")
w("      var specialties = (h.specialties || []).slice(0, 5).map(function(s) { return '<span class=\"chip\">' + (typeof s === 'string' ? s : (s.name || s)) + '</span>'; }).join('');")
w("      var insurances = (h.insurance || []).slice(0, 4).map(function(s) { return '<span class=\"chip\">' + s + '</span>'; }).join('');")
w("      var languages = (h.languages || []).map(function(s) { return '<span class=\"chip\">' + s + '</span>'; }).join('');")
w("      var parts = [];")
w("      parts.push('<div class=\"hospital\">');")
w("      parts.push('<div class=\"hospital-main\">');")
w("      parts.push('<div class=\"hospital-head\"><h4>' + name + nameZh + '</h4></div>');")
w("      parts.push('<div class=\"sub\">Address: ' + address + '</div>');")
w("      if (h.phone) parts.push('<div class=\"sub\">Phone: ' + h.phone + '</div>');")
w("      parts.push('<div class=\"hospital-meta-row\"><span class=\"meta-item\">Wait: <strong>' + wait + '</strong></span><span class=\"meta-item\">Distance: <strong>' + dist + '</strong></span></div>');")
w("      if (specialties) parts.push('<div class=\"chips\"><span class=\"muted small\">Specialties: </span>' + specialties + '</div>');")
w("      if (insurances) parts.push('<div class=\"chips\"><span class=\"muted small\">Insurance: </span>' + insurances + '</div>');")
w("      if (languages) parts.push('<div class=\"chips\"><span class=\"muted small\">Languages: </span>' + languages + '</div>');")
w("      parts.push('</div>');")
w("      parts.push('<div class=\"hospital-side\">');")
w("      parts.push('<div class=\"rating-badge\"><span class=\"rating-num\">' + rating + '</span></div>');")
w("      parts.push('<button class=\"btn btn-light btn-nav\">Navigate here</button>');")
w("      parts.push('</div></div>');")
w("      return parts.join('');")
w("    }).join('');")
w("    qsa('#hospital-list .btn-nav').forEach(function(btn) { bindClick(btn, function() { setActive('navigation'); }); });")
w("  }")
w("")
w("  // --- Navigation ---")
w("  function initNavigation() {")
w("    var out = byId('nav-output');")
w("    if (!out) return;")
w("    out.innerHTML = '<div class=\"card\"><h4 style=\"margin-top:0;\">Outdoor Hospital Navigation</h4><p class=\"muted small\">Select a hospital from the Hospitals page, then use external map services (Google Maps, AMap, Apple Maps, Baidu Maps) to get directions.</p><p>Click the Use my location button to enable geolocation-based routing from your current position.</p></div>';")
w("  }")
w("")
w("  bindClick(byId('nav-locate'), function() {")
w("    if (!navigator.geolocation) { alert('Geolocation not available in this browser'); return; }")
w("    navigator.geolocation.getCurrentPosition(function(pos) {")
w("      alert('Your location: ' + pos.coords.latitude.toFixed(4) + ', ' + pos.coords.longitude.toFixed(4));")
w("    }, function(err) { alert('Location error: ' + err.message); });")
w("  });")
w("")
w("  // --- Medications ---")
w("  function loadMedications() {")
w("    var listEl = byId('med-list');")
w("    if (!listEl) return;")
w("    fetch(API + '/api/medications?limit=30')")
w("      .then(function(r) { return r.json(); })")
w("      .then(function(data) {")
w("        var meds = data.medications || [];")
w("        var picker = byId('med-picker');")
w("        if (picker) {")
w("          picker.innerHTML = '';")
w("          meds.forEach(function(m) { var opt = document.createElement('option'); opt.value = m.id || m.name; opt.textContent = m.name; picker.appendChild(opt); });")
w("        }")
w("        listEl.innerHTML = '<p class=\"muted small\">' + meds.length + ' medications available. Log in to save your personal list.</p>';")
w("      }).catch(function(e) { listEl.innerHTML = '<p class=\"muted\">Medication list unavailable.</p>'; });")
w("  }")
w("")
w("  bindClick(byId('btn-add-med'), function() {")
w("    if (!getUser()) { alert('Please log in to save medications'); return; }")
w("    alert('Medication saved (demo feature)');")
w("  });")
w("")
w("  // --- Insurance ---")
w("  bindClick(byId('btn-insurance'), function() {")
w("    var sel = byId('ins-provider');")
w("    var out = byId('ins-result');")
w("    if (!sel || !out) return;")
w("    var name = sel.value;")
w("    var parts = [];")
w("    parts.push('<div class=\"card\">');")
w("    parts.push('<h4 style=\"margin-top:0;\">Checklist for ' + name + '</h4>');")
w("    parts.push('<ul style=\"line-height:1.8;\"><li>Passport / ID</li><li>Insurance card</li><li>Previous medical records</li><li>Referral letter (if required)</li><li>Invoice for reimbursement</li></ul>');")
w("    parts.push('</div>');")
w("    out.innerHTML = parts.join('');")
w("  });")
w("")
w("  bindClick(byId('btn-add-claim'), function() {")
w("    if (!getUser()) { alert('Please log in first'); return; }")
w("    alert('Claim submitted (demo feature)');")
w("  });")
w("")
w("  // --- Privacy ---")
w("  bindClick(byId('btn-export'), function() { alert('Export ready (demo)'); });")
w("  bindClick(byId('btn-wipe'), function() { if (confirm('Delete all your saved records?')) alert('Records wiped (demo)'); });")
w("")
w("  // --- Feedback ---")
w("  bindClick(byId('btn-send-feedback'), function() {")
w("    var content = byId('fb-content') ? byId('fb-content').value.trim() : '';")
w("    var statusEl = byId('fb-status');")
w("    if (!content) return;")
w("    if (statusEl) statusEl.textContent = 'Thank you for your feedback!';")
w("    if (byId('fb-content')) byId('fb-content').value = '';")
w("  });")
w("")
w("  // --- Quick symptom chips on hospital page ---")
w("  var hospitalChips = byId('symptom-chips');")
w("  // already handled above")
w("")
w("  // --- Init ---")
w("  refreshAuthUI();")
w("  setActive('home');")
w("  console.log('TransMed UI initialized, API:', API);")
w("})();")

content = "\n".join(lines)

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "transmed_web", "app.js")
with open(outpath, "w", encoding="utf-8") as f:
    f.write(content)
print(f"Written {len(lines)} lines to {outpath}")
