# -*- coding: utf-8 -*-
"""Extended bilingual medical term corpus for TransMed.

This module supplements ``transmed_app.data.MEDICAL_TERMS`` with a large,
high-value set of English -> (中文, latin_or_INN) entries that a foreign
patient or clinician in mainland China would realistically encounter.

The third tuple element is the Latin medical term or the drug INN
(International Nonproprietary Name) where a standard one exists; otherwise
the standard English term is repeated rather than inventing Latin.

Keys are lowercase. This dict is intentionally kept free of any key already
present in ``MEDICAL_TERMS`` so the two can be merged with minimal overlap.
"""

MEDICAL_TERMS_EXT: "dict[str, tuple[str, str]]" = {
    # ------------------------------------------------------------------
    # Symptoms & signs
    # ------------------------------------------------------------------
    "tachycardia": ("心动过速", "tachycardia"),
    "bradycardia": ("心动过缓", "bradycardia"),
    "hemoptysis": ("咯血", "haemoptysis"),
    "melena": ("黑便", "melaena"),
    "hematemesis": ("呕血", "haematemesis"),
    "hematochezia": ("便血", "haematochezia"),
    "dysphagia": ("吞咽困难", "dysphagia"),
    "odynophagia": ("吞咽疼痛", "odynophagia"),
    "photophobia": ("畏光", "photophobia"),
    "paresthesia": ("感觉异常", "paraesthesia"),
    "syncope": ("晕厥", "syncope"),
    "presyncope": ("晕厥前兆", "presyncope"),
    "orthopnea": ("端坐呼吸", "orthopnoea"),
    "dyspnea": ("呼吸困难", "dyspnoea"),
    "tachypnea": ("呼吸急促", "tachypnoea"),
    "bradypnea": ("呼吸过缓", "bradypnoea"),
    "apnea": ("呼吸暂停", "apnoea"),
    "hyperventilation": ("过度通气", "hyperventilation"),
    "cyanosis": ("发绀", "cyanosis"),
    "pallor": ("面色苍白", "pallor"),
    "diaphoresis": ("大汗", "diaphoresis"),
    "anhidrosis": ("无汗", "anhidrosis"),
    "hyperhidrosis": ("多汗症", "hyperhidrosis"),
    "pruritus": ("瘙痒", "pruritus"),
    "urticaria": ("荨麻疹", "urticaria"),
    "erythema": ("红斑", "erythema"),
    "petechiae": ("瘀点", "petechiae"),
    "purpura": ("紫癜", "purpura"),
    "ecchymosis": ("瘀斑", "ecchymosis"),
    "edema lower limb": ("下肢水肿", "oedema"),
    "ascites": ("腹水", "ascites"),
    "anasarca": ("全身水肿", "anasarca"),
    "lymphadenopathy": ("淋巴结肿大", "lymphadenopathy"),
    "hepatomegaly": ("肝肿大", "hepatomegaly"),
    "splenomegaly": ("脾肿大", "splenomegaly"),
    "hepatosplenomegaly": ("肝脾肿大", "hepatosplenomegaly"),
    "cachexia": ("恶病质", "cachexia"),
    "malaise": ("乏力不适", "malaise"),
    "anorexia": ("食欲不振", "anorexia"),
    "polydipsia": ("多饮", "polydipsia"),
    "polyuria": ("多尿", "polyuria"),
    "polyphagia": ("多食", "polyphagia"),
    "oliguria": ("少尿", "oliguria"),
    "anuria": ("无尿", "anuria"),
    "nocturia": ("夜尿", "nocturia"),
    "dysuria": ("排尿困难", "dysuria"),
    "hematuria": ("血尿", "haematuria"),
    "pyuria": ("脓尿", "pyuria"),
    "proteinuria": ("蛋白尿", "proteinuria"),
    "hesitancy": ("排尿踌躇", "urinary hesitancy"),
    "dribbling": ("尿后滴沥", "post-void dribbling"),
    "tenesmus": ("里急后重", "tenesmus"),
    "flatulence": ("肠胀气", "flatulence"),
    "belching": ("嗳气", "eructation"),
    "regurgitation": ("反流", "regurgitation"),
    "dyspepsia": ("消化不良", "dyspepsia"),
    "epigastric pain": ("上腹痛", "epigastric pain"),
    "colic": ("绞痛", "colic"),
    "borborygmi": ("肠鸣音亢进", "borborygmi"),
    "steatorrhea": ("脂肪泻", "steatorrhoea"),
    "hematospermia": ("血精", "haematospermia"),
    "epistaxis": ("鼻出血", "epistaxis"),
    "rhinorrhea": ("流涕", "rhinorrhoea"),
    "anosmia": ("嗅觉丧失", "anosmia"),
    "hyposmia": ("嗅觉减退", "hyposmia"),
    "ageusia": ("味觉丧失", "ageusia"),
    "dysgeusia": ("味觉障碍", "dysgeusia"),
    "tinnitus": ("耳鸣", "tinnitus"),
    "vertigo": ("眩晕", "vertigo"),
    "otalgia": ("耳痛", "otalgia"),
    "otorrhea": ("耳漏", "otorrhoea"),
    "hoarseness": ("声音嘶哑", "hoarseness"),
    "dysphonia": ("发声障碍", "dysphonia"),
    "aphonia": ("失声", "aphonia"),
    "dysarthria": ("构音障碍", "dysarthria"),
    "aphasia": ("失语症", "aphasia"),
    "dysphasia": ("言语障碍", "dysphasia"),
    "diplopia": ("复视", "diplopia"),
    "amblyopia": ("弱视", "amblyopia"),
    "scotoma": ("暗点", "scotoma"),
    "nystagmus": ("眼球震颤", "nystagmus"),
    "ptosis": ("上睑下垂", "ptosis"),
    "proptosis": ("眼球突出", "proptosis"),
    "lacrimation": ("流泪", "lacrimation"),
    "epiphora": ("溢泪", "epiphora"),
    "myalgia": ("肌肉疼痛", "myalgia"),
    "arthralgia": ("关节疼痛", "arthralgia"),
    "ataxia": ("共济失调", "ataxia"),
    "spasticity": ("痉挛状态", "spasticity"),
    "rigidity": ("强直", "rigidity"),
    "fasciculation": ("肌束颤动", "fasciculation"),
    "cramp": ("抽筋", "muscle cramp"),
    "claudication": ("跛行", "claudication"),
    "hemiparesis": ("偏侧轻瘫", "hemiparesis"),
    "hemiplegia": ("偏瘫", "hemiplegia"),
    "paraplegia": ("截瘫", "paraplegia"),
    "quadriplegia": ("四肢瘫", "quadriplegia"),
    "paralysis": ("瘫痪", "paralysis"),
    "hypoesthesia": ("感觉减退", "hypoaesthesia"),
    "anesthesia sensory": ("感觉缺失", "anaesthesia"),
    "allodynia": ("异常性疼痛", "allodynia"),
    "hyperalgesia": ("痛觉过敏", "hyperalgesia"),
    "neuralgia": ("神经痛", "neuralgia"),
    "radiculopathy": ("神经根病", "radiculopathy"),
    "sciatica": ("坐骨神经痛", "sciatica"),
    "stiff neck": ("颈项强直", "nuchal rigidity"),
    "lethargy": ("嗜睡倦怠", "lethargy"),
    "somnolence": ("嗜睡", "somnolence"),
    "stupor": ("木僵", "stupor"),
    "coma": ("昏迷", "coma"),
    "delirium": ("谵妄", "delirium"),
    "disorientation": ("定向力障碍", "disorientation"),
    "hallucination": ("幻觉", "hallucination"),
    "delusion": ("妄想", "delusion"),
    "amnesia": ("遗忘症", "amnesia"),
    "syncopal episode": ("晕厥发作", "syncopal episode"),
    "febrile": ("发热的", "febrile"),
    "afebrile": ("无发热的", "afebrile"),
    "rigors": ("寒战", "rigors"),
    "hot flash": ("潮热", "hot flush"),
    "weight loss unintentional": ("非自主性体重下降", "unintentional weight loss"),
    "failure to thrive": ("生长发育迟缓", "failure to thrive"),
    "dizziness on standing": ("起立时头晕", "orthostatic dizziness"),
    "palpitation episode": ("心悸发作", "palpitation"),
    "chest discomfort": ("胸部不适", "chest discomfort"),
    "pleuritic pain": ("胸膜性疼痛", "pleuritic pain"),
    "abdominal distension": ("腹胀", "abdominal distension"),
    "rebound tenderness": ("反跳痛", "rebound tenderness"),
    "guarding": ("腹肌紧张", "abdominal guarding"),
    "jaundice scleral": ("巩膜黄染", "scleral icterus"),
    "clubbing": ("杵状指", "digital clubbing"),
    "koilonychia": ("匙状甲", "koilonychia"),
    "pitting edema": ("凹陷性水肿", "pitting oedema"),

    # ------------------------------------------------------------------
    # Diseases & conditions — cardiovascular
    # ------------------------------------------------------------------
    "myocardial infarction": ("心肌梗死", "myocardial infarction"),
    "acute coronary syndrome": ("急性冠脉综合征", "acute coronary syndrome"),
    "angina pectoris": ("心绞痛", "angina pectoris"),
    "unstable angina": ("不稳定型心绞痛", "unstable angina"),
    "congestive heart failure": ("充血性心力衰竭", "congestive heart failure"),
    "cardiomyopathy": ("心肌病", "cardiomyopathy"),
    "myocarditis": ("心肌炎", "myocarditis"),
    "pericarditis": ("心包炎", "pericarditis"),
    "endocarditis": ("心内膜炎", "endocarditis"),
    "valvular heart disease": ("心脏瓣膜病", "valvular heart disease"),
    "mitral stenosis": ("二尖瓣狭窄", "mitral stenosis"),
    "mitral regurgitation": ("二尖瓣关闭不全", "mitral regurgitation"),
    "aortic stenosis": ("主动脉瓣狭窄", "aortic stenosis"),
    "aortic regurgitation": ("主动脉瓣关闭不全", "aortic regurgitation"),
    "aortic aneurysm": ("主动脉瘤", "aortic aneurysm"),
    "aortic dissection": ("主动脉夹层", "aortic dissection"),
    "peripheral artery disease": ("外周动脉疾病", "peripheral arterial disease"),
    "deep vein thrombosis": ("深静脉血栓", "deep vein thrombosis"),
    "pulmonary embolism": ("肺栓塞", "pulmonary embolism"),
    "varicose veins": ("静脉曲张", "varicose veins"),
    "thrombophlebitis": ("血栓性静脉炎", "thrombophlebitis"),
    "atherosclerosis": ("动脉粥样硬化", "atherosclerosis"),
    "hyperlipidemia": ("高脂血症", "hyperlipidaemia"),
    "dyslipidemia": ("血脂异常", "dyslipidaemia"),
    "hypotension": ("低血压", "hypotension"),
    "orthostatic hypotension": ("体位性低血压", "orthostatic hypotension"),
    "hypertensive crisis": ("高血压危象", "hypertensive crisis"),
    "ventricular tachycardia": ("室性心动过速", "ventricular tachycardia"),
    "ventricular fibrillation": ("心室颤动", "ventricular fibrillation"),
    "supraventricular tachycardia": ("室上性心动过速", "supraventricular tachycardia"),
    "bradyarrhythmia": ("缓慢性心律失常", "bradyarrhythmia"),
    "heart block": ("心脏传导阻滞", "heart block"),
    "cardiac arrest": ("心脏骤停", "cardiac arrest"),
    "cardiogenic shock": ("心源性休克", "cardiogenic shock"),
    "rheumatic heart disease": ("风湿性心脏病", "rheumatic heart disease"),
    "congenital heart disease": ("先天性心脏病", "congenital heart disease"),
    "patent foramen ovale": ("卵圆孔未闭", "patent foramen ovale"),

    # ------------------------------------------------------------------
    # Diseases & conditions — respiratory
    # ------------------------------------------------------------------
    "chronic obstructive pulmonary disease": ("慢性阻塞性肺疾病", "chronic obstructive pulmonary disease"),
    "emphysema": ("肺气肿", "emphysema"),
    "chronic bronchitis": ("慢性支气管炎", "chronic bronchitis"),
    "bronchiectasis": ("支气管扩张", "bronchiectasis"),
    "bronchiolitis": ("细支气管炎", "bronchiolitis"),
    "pleurisy": ("胸膜炎", "pleurisy"),
    "pleural effusion": ("胸腔积液", "pleural effusion"),
    "pneumothorax": ("气胸", "pneumothorax"),
    "hemothorax": ("血胸", "haemothorax"),
    "empyema": ("脓胸", "empyema"),
    "pulmonary edema": ("肺水肿", "pulmonary oedema"),
    "pulmonary fibrosis": ("肺纤维化", "pulmonary fibrosis"),
    "pulmonary hypertension": ("肺动脉高压", "pulmonary hypertension"),
    "acute respiratory distress syndrome": ("急性呼吸窘迫综合征", "acute respiratory distress syndrome"),
    "respiratory failure": ("呼吸衰竭", "respiratory failure"),
    "sleep apnea": ("睡眠呼吸暂停", "sleep apnoea"),
    "obstructive sleep apnea": ("阻塞性睡眠呼吸暂停", "obstructive sleep apnoea"),
    "cystic fibrosis": ("囊性纤维化", "cystic fibrosis"),
    "sarcoidosis": ("结节病", "sarcoidosis"),
    "pneumoconiosis": ("尘肺", "pneumoconiosis"),
    "silicosis": ("矽肺", "silicosis"),
    "asbestosis": ("石棉肺", "asbestosis"),
    "lung cancer": ("肺癌", "lung carcinoma"),
    "mesothelioma": ("间皮瘤", "mesothelioma"),
    "whooping cough": ("百日咳", "pertussis"),
    "croup": ("喉炎（哮吼）", "croup"),
    "laryngitis": ("喉炎", "laryngitis"),
    "pharyngitis": ("咽炎", "pharyngitis"),
    "tonsillitis": ("扁桃体炎", "tonsillitis"),
    "rhinitis": ("鼻炎", "rhinitis"),
    "allergic rhinitis": ("过敏性鼻炎", "allergic rhinitis"),
    "hay fever": ("花粉症", "allergic rhinitis"),

    # ------------------------------------------------------------------
    # Diseases & conditions — GI / hepatology
    # ------------------------------------------------------------------
    "gastroesophageal reflux disease": ("胃食管反流病", "gastro-oesophageal reflux disease"),
    "esophagitis": ("食管炎", "oesophagitis"),
    "esophageal varices": ("食管静脉曲张", "oesophageal varices"),
    "hiatal hernia": ("食管裂孔疝", "hiatal hernia"),
    "duodenal ulcer": ("十二指肠溃疡", "duodenal ulcer"),
    "gastric ulcer": ("胃溃疡", "gastric ulcer"),
    "stomach cancer": ("胃癌", "gastric carcinoma"),
    "helicobacter pylori infection": ("幽门螺杆菌感染", "Helicobacter pylori infection"),
    "irritable bowel syndrome": ("肠易激综合征", "irritable bowel syndrome"),
    "inflammatory bowel disease": ("炎症性肠病", "inflammatory bowel disease"),
    "crohn disease": ("克罗恩病", "Crohn disease"),
    "ulcerative colitis": ("溃疡性结肠炎", "ulcerative colitis"),
    "diverticulitis": ("憩室炎", "diverticulitis"),
    "diverticulosis": ("憩室病", "diverticulosis"),
    "intestinal obstruction": ("肠梗阻", "intestinal obstruction"),
    "ileus": ("肠麻痹", "ileus"),
    "intussusception": ("肠套叠", "intussusception"),
    "volvulus": ("肠扭转", "volvulus"),
    "colorectal cancer": ("结直肠癌", "colorectal carcinoma"),
    "colon polyp": ("结肠息肉", "colonic polyp"),
    "anal fissure": ("肛裂", "anal fissure"),
    "anal fistula": ("肛瘘", "anal fistula"),
    "perianal abscess": ("肛周脓肿", "perianal abscess"),
    "pancreatitis": ("胰腺炎", "pancreatitis"),
    "acute pancreatitis": ("急性胰腺炎", "acute pancreatitis"),
    "chronic pancreatitis": ("慢性胰腺炎", "chronic pancreatitis"),
    "pancreatic cancer": ("胰腺癌", "pancreatic carcinoma"),
    "cholecystitis": ("胆囊炎", "cholecystitis"),
    "cholelithiasis": ("胆石症", "cholelithiasis"),
    "cholangitis": ("胆管炎", "cholangitis"),
    "biliary colic": ("胆绞痛", "biliary colic"),
    "fatty liver": ("脂肪肝", "hepatic steatosis"),
    "nonalcoholic fatty liver disease": ("非酒精性脂肪肝病", "non-alcoholic fatty liver disease"),
    "hepatitis a": ("甲型肝炎", "hepatitis A"),
    "hepatitis b": ("乙型肝炎", "hepatitis B"),
    "hepatitis c": ("丙型肝炎", "hepatitis C"),
    "liver cirrhosis": ("肝硬化", "hepatic cirrhosis"),
    "hepatic encephalopathy": ("肝性脑病", "hepatic encephalopathy"),
    "liver cancer": ("肝癌", "hepatocellular carcinoma"),
    "portal hypertension": ("门静脉高压", "portal hypertension"),
    "gastrointestinal bleeding": ("消化道出血", "gastrointestinal haemorrhage"),

    # ------------------------------------------------------------------
    # Diseases & conditions — endocrine / metabolic
    # ------------------------------------------------------------------
    "diabetic ketoacidosis": ("糖尿病酮症酸中毒", "diabetic ketoacidosis"),
    "hypoglycemia": ("低血糖", "hypoglycaemia"),
    "hyperglycemia": ("高血糖", "hyperglycaemia"),
    "diabetic neuropathy": ("糖尿病神经病变", "diabetic neuropathy"),
    "diabetic retinopathy": ("糖尿病视网膜病变", "diabetic retinopathy"),
    "diabetic nephropathy": ("糖尿病肾病", "diabetic nephropathy"),
    "gestational diabetes": ("妊娠期糖尿病", "gestational diabetes"),
    "metabolic syndrome": ("代谢综合征", "metabolic syndrome"),
    "obesity": ("肥胖症", "obesity"),
    "thyroid nodule": ("甲状腺结节", "thyroid nodule"),
    "goiter": ("甲状腺肿", "goitre"),
    "thyroiditis": ("甲状腺炎", "thyroiditis"),
    "graves disease": ("格雷夫斯病", "Graves disease"),
    "hashimoto thyroiditis": ("桥本甲状腺炎", "Hashimoto thyroiditis"),
    "thyroid cancer": ("甲状腺癌", "thyroid carcinoma"),
    "thyroid storm": ("甲状腺危象", "thyroid storm"),
    "cushing syndrome": ("库欣综合征", "Cushing syndrome"),
    "addison disease": ("艾迪生病", "Addison disease"),
    "adrenal insufficiency": ("肾上腺功能不全", "adrenal insufficiency"),
    "pheochromocytoma": ("嗜铬细胞瘤", "phaeochromocytoma"),
    "hyperparathyroidism": ("甲状旁腺功能亢进", "hyperparathyroidism"),
    "hypoparathyroidism": ("甲状旁腺功能减退", "hypoparathyroidism"),
    "hypercalcemia": ("高钙血症", "hypercalcaemia"),
    "hypocalcemia": ("低钙血症", "hypocalcaemia"),
    "hyperkalemia": ("高钾血症", "hyperkalaemia"),
    "hypokalemia": ("低钾血症", "hypokalaemia"),
    "hyponatremia": ("低钠血症", "hyponatraemia"),
    "hypernatremia": ("高钠血症", "hypernatraemia"),
    "acidosis": ("酸中毒", "acidosis"),
    "alkalosis": ("碱中毒", "alkalosis"),
    "dehydration severe": ("重度脱水", "dehydration"),
    "acromegaly": ("肢端肥大症", "acromegaly"),
    "diabetes insipidus": ("尿崩症", "diabetes insipidus"),
    "polycystic ovary syndrome": ("多囊卵巢综合征", "polycystic ovary syndrome"),
    "hyperuricemia": ("高尿酸血症", "hyperuricaemia"),

    # ------------------------------------------------------------------
    # Diseases & conditions — neuro
    # ------------------------------------------------------------------
    "transient ischemic attack": ("短暂性脑缺血发作", "transient ischaemic attack"),
    "ischemic stroke": ("缺血性卒中", "ischaemic stroke"),
    "hemorrhagic stroke": ("出血性卒中", "haemorrhagic stroke"),
    "cerebral hemorrhage": ("脑出血", "cerebral haemorrhage"),
    "subarachnoid hemorrhage": ("蛛网膜下腔出血", "subarachnoid haemorrhage"),
    "subdural hematoma": ("硬膜下血肿", "subdural haematoma"),
    "epidural hematoma": ("硬膜外血肿", "epidural haematoma"),
    "cerebral aneurysm": ("脑动脉瘤", "cerebral aneurysm"),
    "meningitis": ("脑膜炎", "meningitis"),
    "encephalitis": ("脑炎", "encephalitis"),
    "encephalopathy": ("脑病", "encephalopathy"),
    "multiple sclerosis": ("多发性硬化", "multiple sclerosis"),
    "amyotrophic lateral sclerosis": ("肌萎缩侧索硬化", "amyotrophic lateral sclerosis"),
    "myasthenia gravis": ("重症肌无力", "myasthenia gravis"),
    "guillain barre syndrome": ("吉兰-巴雷综合征", "Guillain-Barre syndrome"),
    "peripheral neuropathy": ("周围神经病", "peripheral neuropathy"),
    "trigeminal neuralgia": ("三叉神经痛", "trigeminal neuralgia"),
    "bell palsy": ("贝尔面瘫", "Bell palsy"),
    "carpal tunnel syndrome": ("腕管综合征", "carpal tunnel syndrome"),
    "concussion": ("脑震荡", "concussion"),
    "traumatic brain injury": ("创伤性脑损伤", "traumatic brain injury"),
    "spinal cord injury": ("脊髓损伤", "spinal cord injury"),
    "cerebral palsy": ("脑性瘫痪", "cerebral palsy"),
    "huntington disease": ("亨廷顿病", "Huntington disease"),
    "tension headache": ("紧张性头痛", "tension-type headache"),
    "cluster headache": ("丛集性头痛", "cluster headache"),
    "narcolepsy": ("发作性睡病", "narcolepsy"),
    "restless legs syndrome": ("不宁腿综合征", "restless legs syndrome"),
    "status epilepticus": ("癫痫持续状态", "status epilepticus"),

    # ------------------------------------------------------------------
    # Diseases & conditions — infectious
    # ------------------------------------------------------------------
    "urinary tract infection upper": ("上尿路感染", "upper urinary tract infection"),
    "pyelonephritis": ("肾盂肾炎", "pyelonephritis"),
    "cellulitis": ("蜂窝织炎", "cellulitis"),
    "abscess": ("脓肿", "abscess"),
    "osteomyelitis": ("骨髓炎", "osteomyelitis"),
    "septic arthritis": ("化脓性关节炎", "septic arthritis"),
    "septic shock": ("感染性休克", "septic shock"),
    "bacteremia": ("菌血症", "bacteraemia"),
    "tetanus infection": ("破伤风感染", "tetanus"),
    "typhoid fever": ("伤寒", "typhoid fever"),
    "cholera": ("霍乱", "cholera"),
    "dysentery": ("痢疾", "dysentery"),
    "amebiasis": ("阿米巴病", "amoebiasis"),
    "giardiasis": ("贾第虫病", "giardiasis"),
    "schistosomiasis": ("血吸虫病", "schistosomiasis"),
    "leptospirosis": ("钩端螺旋体病", "leptospirosis"),
    "brucellosis": ("布鲁氏菌病", "brucellosis"),
    "anthrax": ("炭疽", "anthrax"),
    "plague": ("鼠疫", "plague"),
    "dengue fever": ("登革热", "dengue fever"),
    "chikungunya": ("基孔肯雅热", "chikungunya"),
    "zika virus": ("寨卡病毒", "Zika virus"),
    "japanese encephalitis": ("流行性乙型脑炎", "Japanese encephalitis"),
    "hemorrhagic fever": ("出血热", "haemorrhagic fever"),
    "hand foot mouth disease": ("手足口病", "hand, foot and mouth disease"),
    "scarlet fever": ("猩红热", "scarlet fever"),
    "diphtheria": ("白喉", "diphtheria"),
    "epstein barr virus": ("EB病毒", "Epstein-Barr virus"),
    "infectious mononucleosis": ("传染性单核细胞增多症", "infectious mononucleosis"),
    "cytomegalovirus": ("巨细胞病毒", "cytomegalovirus"),
    "herpes zoster": ("带状疱疹", "herpes zoster"),
    "herpes simplex": ("单纯疱疹", "herpes simplex"),
    "genital herpes": ("生殖器疱疹", "genital herpes"),
    "syphilis": ("梅毒", "syphilis"),
    "gonorrhea": ("淋病", "gonorrhoea"),
    "chlamydia": ("衣原体感染", "chlamydia"),
    "human papillomavirus": ("人乳头瘤病毒", "human papillomavirus"),
    "candidiasis": ("念珠菌病", "candidiasis"),
    "tinea": ("癣", "tinea"),
    "tuberculosis pulmonary": ("肺结核", "pulmonary tuberculosis"),
    "norovirus": ("诺如病毒", "norovirus"),
    "rotavirus": ("轮状病毒", "rotavirus"),
    "sepsis severe": ("严重脓毒症", "sepsis"),

    # ------------------------------------------------------------------
    # Diseases & conditions — hematology / oncology
    # ------------------------------------------------------------------
    "iron deficiency anemia": ("缺铁性贫血", "iron deficiency anaemia"),
    "aplastic anemia": ("再生障碍性贫血", "aplastic anaemia"),
    "hemolytic anemia": ("溶血性贫血", "haemolytic anaemia"),
    "sickle cell anemia": ("镰状细胞贫血", "sickle cell anaemia"),
    "thalassemia": ("地中海贫血", "thalassaemia"),
    "pernicious anemia": ("恶性贫血", "pernicious anaemia"),
    "polycythemia": ("红细胞增多症", "polycythaemia"),
    "thrombocytopenia": ("血小板减少症", "thrombocytopenia"),
    "thrombocytosis": ("血小板增多症", "thrombocytosis"),
    "neutropenia": ("中性粒细胞减少", "neutropenia"),
    "hemophilia": ("血友病", "haemophilia"),
    "von willebrand disease": ("血管性血友病", "von Willebrand disease"),
    "disseminated intravascular coagulation": ("弥散性血管内凝血", "disseminated intravascular coagulation"),
    "deep venous thrombosis": ("深静脉血栓形成", "deep venous thrombosis"),
    "myeloma": ("骨髓瘤", "myeloma"),
    "multiple myeloma": ("多发性骨髓瘤", "multiple myeloma"),
    "acute leukemia": ("急性白血病", "acute leukaemia"),
    "chronic leukemia": ("慢性白血病", "chronic leukaemia"),
    "hodgkin lymphoma": ("霍奇金淋巴瘤", "Hodgkin lymphoma"),
    "non hodgkin lymphoma": ("非霍奇金淋巴瘤", "non-Hodgkin lymphoma"),
    "metastasis": ("转移", "metastasis"),
    "carcinoma": ("癌", "carcinoma"),
    "sarcoma": ("肉瘤", "sarcoma"),
    "melanoma": ("黑色素瘤", "melanoma"),
    "basal cell carcinoma": ("基底细胞癌", "basal cell carcinoma"),
    "squamous cell carcinoma": ("鳞状细胞癌", "squamous cell carcinoma"),
    "breast cancer": ("乳腺癌", "breast carcinoma"),
    "cervical cancer": ("宫颈癌", "cervical carcinoma"),
    "ovarian cancer": ("卵巢癌", "ovarian carcinoma"),
    "endometrial cancer": ("子宫内膜癌", "endometrial carcinoma"),
    "prostate cancer": ("前列腺癌", "prostate carcinoma"),
    "bladder cancer": ("膀胱癌", "bladder carcinoma"),
    "kidney cancer": ("肾癌", "renal carcinoma"),
    "esophageal cancer": ("食管癌", "oesophageal carcinoma"),
    "nasopharyngeal carcinoma": ("鼻咽癌", "nasopharyngeal carcinoma"),
    "thyroid carcinoma": ("甲状腺癌", "thyroid carcinoma"),
    "brain tumor": ("脑肿瘤", "brain tumour"),
    "glioma": ("胶质瘤", "glioma"),
    "benign tumor": ("良性肿瘤", "benign tumour"),
    "malignant tumor": ("恶性肿瘤", "malignant tumour"),
    "remission": ("缓解", "remission"),
    "relapse": ("复发", "relapse"),
    "palliative care": ("姑息治疗", "palliative care"),

    # ------------------------------------------------------------------
    # Diseases & conditions — musculoskeletal / rheumatology
    # ------------------------------------------------------------------
    "tendinitis": ("肌腱炎", "tendinitis"),
    "bursitis": ("滑囊炎", "bursitis"),
    "fibromyalgia": ("纤维肌痛", "fibromyalgia"),
    "lupus": ("狼疮", "systemic lupus erythematosus"),
    "systemic lupus erythematosus": ("系统性红斑狼疮", "systemic lupus erythematosus"),
    "scleroderma": ("硬皮病", "scleroderma"),
    "sjogren syndrome": ("干燥综合征", "Sjogren syndrome"),
    "ankylosing spondylitis": ("强直性脊柱炎", "ankylosing spondylitis"),
    "psoriatic arthritis": ("银屑病关节炎", "psoriatic arthritis"),
    "gouty arthritis": ("痛风性关节炎", "gouty arthritis"),
    "vasculitis": ("血管炎", "vasculitis"),
    "polymyalgia rheumatica": ("风湿性多肌痛", "polymyalgia rheumatica"),
    "herniated disc": ("椎间盘突出", "herniated intervertebral disc"),
    "scoliosis": ("脊柱侧弯", "scoliosis"),
    "kyphosis": ("驼背", "kyphosis"),
    "spinal stenosis": ("椎管狭窄", "spinal stenosis"),
    "frozen shoulder": ("冻结肩", "adhesive capsulitis"),
    "rotator cuff tear": ("肩袖撕裂", "rotator cuff tear"),
    "meniscus tear": ("半月板撕裂", "meniscal tear"),
    "ligament tear": ("韧带撕裂", "ligament tear"),
    "tennis elbow": ("网球肘", "lateral epicondylitis"),
    "plantar fasciitis": ("足底筋膜炎", "plantar fasciitis"),
    "dislocation": ("脱位", "dislocation"),
    "compound fracture": ("开放性骨折", "compound fracture"),
    "stress fracture": ("应力性骨折", "stress fracture"),
    "osteomalacia": ("骨软化症", "osteomalacia"),
    "rickets": ("佝偻病", "rickets"),
    "avascular necrosis": ("缺血性坏死", "avascular necrosis"),

    # ------------------------------------------------------------------
    # Diseases & conditions — dermatology
    # ------------------------------------------------------------------
    "dermatitis": ("皮炎", "dermatitis"),
    "atopic dermatitis": ("特应性皮炎", "atopic dermatitis"),
    "contact dermatitis": ("接触性皮炎", "contact dermatitis"),
    "seborrheic dermatitis": ("脂溢性皮炎", "seborrhoeic dermatitis"),
    "rosacea": ("玫瑰痤疮", "rosacea"),
    "vitiligo": ("白癜风", "vitiligo"),
    "melasma": ("黄褐斑", "melasma"),
    "impetigo": ("脓疱疮", "impetigo"),
    "folliculitis": ("毛囊炎", "folliculitis"),
    "boil": ("疖", "furuncle"),
    "carbuncle": ("痈", "carbuncle"),
    "abscess skin": ("皮肤脓肿", "cutaneous abscess"),
    "pressure ulcer": ("压疮", "pressure ulcer"),
    "bedsore": ("褥疮", "decubitus ulcer"),
    "skin tag": ("皮赘", "acrochordon"),
    "mole": ("痣", "melanocytic naevus"),
    "keloid": ("瘢痕疙瘩", "keloid"),
    "alopecia": ("脱发", "alopecia"),
    "hyperpigmentation": ("色素沉着过度", "hyperpigmentation"),
    "blister": ("水疱", "blister"),
    "callus": ("胼胝", "callus"),
    "corn skin": ("鸡眼", "clavus"),
    "sunburn": ("晒伤", "sunburn"),
    "frostbite": ("冻伤", "frostbite"),
    "heat rash": ("痱子", "miliaria"),

    # ------------------------------------------------------------------
    # Diseases & conditions — psychiatric / mental health
    # ------------------------------------------------------------------
    "bipolar disorder": ("双相情感障碍", "bipolar disorder"),
    "major depressive disorder": ("重性抑郁障碍", "major depressive disorder"),
    "generalized anxiety disorder": ("广泛性焦虑障碍", "generalised anxiety disorder"),
    "panic disorder": ("惊恐障碍", "panic disorder"),
    "panic attack": ("惊恐发作", "panic attack"),
    "obsessive compulsive disorder": ("强迫症", "obsessive-compulsive disorder"),
    "post traumatic stress disorder": ("创伤后应激障碍", "post-traumatic stress disorder"),
    "phobia": ("恐惧症", "phobia"),
    "social anxiety": ("社交焦虑", "social anxiety disorder"),
    "eating disorder": ("进食障碍", "eating disorder"),
    "anorexia nervosa": ("神经性厌食", "anorexia nervosa"),
    "bulimia nervosa": ("神经性贪食", "bulimia nervosa"),
    "attention deficit hyperactivity disorder": ("注意缺陷多动障碍", "attention deficit hyperactivity disorder"),
    "autism spectrum disorder": ("孤独症谱系障碍", "autism spectrum disorder"),
    "substance abuse": ("物质滥用", "substance abuse"),
    "alcohol use disorder": ("酒精使用障碍", "alcohol use disorder"),
    "drug addiction": ("药物成瘾", "drug addiction"),
    "withdrawal symptoms": ("戒断症状", "withdrawal symptoms"),
    "suicidal ideation": ("自杀意念", "suicidal ideation"),
    "self harm": ("自残", "self-harm"),
    "psychosis": ("精神病性障碍", "psychosis"),
    "mania": ("躁狂", "mania"),
    "personality disorder": ("人格障碍", "personality disorder"),
    "psychotherapy": ("心理治疗", "psychotherapy"),
    "cognitive behavioral therapy": ("认知行为疗法", "cognitive behavioural therapy"),
    "mental health": ("心理健康", "mental health"),

    # ------------------------------------------------------------------
    # Diseases & conditions — ophthalmic
    # ------------------------------------------------------------------
    "cataract": ("白内障", "cataract"),
    "glaucoma": ("青光眼", "glaucoma"),
    "macular degeneration": ("黄斑变性", "macular degeneration"),
    "retinal detachment": ("视网膜脱离", "retinal detachment"),
    "myopia": ("近视", "myopia"),
    "hyperopia": ("远视", "hyperopia"),
    "astigmatism": ("散光", "astigmatism"),
    "presbyopia": ("老花眼", "presbyopia"),
    "dry eye": ("干眼症", "dry eye"),
    "blepharitis": ("睑缘炎", "blepharitis"),
    "keratitis": ("角膜炎", "keratitis"),
    "uveitis": ("葡萄膜炎", "uveitis"),
    "strabismus": ("斜视", "strabismus"),
    "color blindness": ("色盲", "colour blindness"),
    "corneal ulcer": ("角膜溃疡", "corneal ulcer"),
    "chalazion": ("睑板腺囊肿", "chalazion"),

    # ------------------------------------------------------------------
    # Diseases & conditions — ENT / dental
    # ------------------------------------------------------------------
    "deviated septum": ("鼻中隔偏曲", "deviated nasal septum"),
    "nasal polyp": ("鼻息肉", "nasal polyp"),
    "labyrinthitis": ("迷路炎", "labyrinthitis"),
    "meniere disease": ("梅尼埃病", "Meniere disease"),
    "vertigo benign positional": ("良性阵发性位置性眩晕", "benign paroxysmal positional vertigo"),
    "earwax impaction": ("耵聍栓塞", "cerumen impaction"),
    "perforated eardrum": ("鼓膜穿孔", "tympanic membrane perforation"),
    "tinnitus chronic": ("慢性耳鸣", "chronic tinnitus"),
    "sleep snoring": ("打鼾", "snoring"),
    "dental caries": ("龋齿", "dental caries"),
    "cavity": ("蛀牙", "dental caries"),
    "gingivitis": ("牙龈炎", "gingivitis"),
    "periodontitis": ("牙周炎", "periodontitis"),
    "dental abscess": ("牙脓肿", "dental abscess"),
    "tooth decay": ("龋坏", "tooth decay"),
    "wisdom tooth": ("智齿", "third molar"),
    "tmj disorder": ("颞下颌关节紊乱", "temporomandibular joint disorder"),
    "mouth ulcer": ("口腔溃疡", "aphthous ulcer"),
    "oral thrush": ("鹅口疮", "oral candidiasis"),
    "bad breath": ("口臭", "halitosis"),

    # ------------------------------------------------------------------
    # Diseases & conditions — urology / nephrology
    # ------------------------------------------------------------------
    "acute kidney injury": ("急性肾损伤", "acute kidney injury"),
    "chronic kidney disease": ("慢性肾脏病", "chronic kidney disease"),
    "end stage renal disease": ("终末期肾病", "end-stage renal disease"),
    "nephrotic syndrome": ("肾病综合征", "nephrotic syndrome"),
    "glomerulonephritis": ("肾小球肾炎", "glomerulonephritis"),
    "renal colic": ("肾绞痛", "renal colic"),
    "hydronephrosis": ("肾积水", "hydronephrosis"),
    "benign prostatic hyperplasia": ("良性前列腺增生", "benign prostatic hyperplasia"),
    "prostatitis": ("前列腺炎", "prostatitis"),
    "epididymitis": ("附睾炎", "epididymitis"),
    "orchitis": ("睾丸炎", "orchitis"),
    "testicular torsion": ("睾丸扭转", "testicular torsion"),
    "varicocele": ("精索静脉曲张", "varicocele"),
    "hydrocele": ("鞘膜积液", "hydrocele"),
    "urinary retention": ("尿潴留", "urinary retention"),
    "urinary incontinence": ("尿失禁", "urinary incontinence"),
    "overactive bladder": ("膀胱过度活动症", "overactive bladder"),
    "cystitis": ("膀胱炎", "cystitis"),
    "urethritis": ("尿道炎", "urethritis"),

    # ------------------------------------------------------------------
    # Diseases & conditions — ob/gyn
    # ------------------------------------------------------------------
    "ectopic pregnancy": ("异位妊娠", "ectopic pregnancy"),
    "preeclampsia": ("子痫前期", "pre-eclampsia"),
    "eclampsia": ("子痫", "eclampsia"),
    "placenta previa": ("前置胎盘", "placenta praevia"),
    "placental abruption": ("胎盘早剥", "placental abruption"),
    "postpartum hemorrhage": ("产后出血", "postpartum haemorrhage"),
    "gestational hypertension": ("妊娠期高血压", "gestational hypertension"),
    "premature labor": ("早产", "premature labour"),
    "cesarean section": ("剖宫产", "caesarean section"),
    "endometriosis": ("子宫内膜异位症", "endometriosis"),
    "uterine fibroid": ("子宫肌瘤", "uterine fibroid"),
    "ovarian cyst": ("卵巢囊肿", "ovarian cyst"),
    "pelvic inflammatory disease": ("盆腔炎", "pelvic inflammatory disease"),
    "cervicitis": ("宫颈炎", "cervicitis"),
    "vaginitis": ("阴道炎", "vaginitis"),
    "bacterial vaginosis": ("细菌性阴道病", "bacterial vaginosis"),
    "menorrhagia": ("月经过多", "menorrhagia"),
    "dysmenorrhea": ("痛经", "dysmenorrhoea"),
    "amenorrhea": ("闭经", "amenorrhoea"),
    "premenstrual syndrome": ("经前期综合征", "premenstrual syndrome"),
    "infertility": ("不孕不育", "infertility"),
    "cervical dysplasia": ("宫颈不典型增生", "cervical dysplasia"),
    "uterine prolapse": ("子宫脱垂", "uterine prolapse"),
    "mastitis": ("乳腺炎", "mastitis"),
    "breast lump": ("乳房肿块", "breast lump"),
    "prenatal care": ("产前检查", "prenatal care"),
    "postnatal care": ("产后护理", "postnatal care"),
    "due date": ("预产期", "estimated date of delivery"),
    "trimester": ("孕期三个月段", "trimester"),
    "fetal heart rate": ("胎心率", "foetal heart rate"),
    "epidural anesthesia": ("硬膜外麻醉", "epidural anaesthesia"),

    # ------------------------------------------------------------------
    # Diseases & conditions — pediatric
    # ------------------------------------------------------------------
    "jaundice neonatal": ("新生儿黄疸", "neonatal jaundice"),
    "colic infant": ("婴儿肠绞痛", "infantile colic"),
    "diaper rash": ("尿布疹", "diaper dermatitis"),
    "febrile seizure": ("热性惊厥", "febrile seizure"),
    "roseola": ("幼儿急疹", "roseola"),
    "fifth disease": ("第五病（传染性红斑）", "erythema infectiosum"),
    "kawasaki disease": ("川崎病", "Kawasaki disease"),
    "intussusception pediatric": ("小儿肠套叠", "intussusception"),
    "pyloric stenosis": ("幽门狭窄", "pyloric stenosis"),
    "congenital hypothyroidism": ("先天性甲状腺功能减退", "congenital hypothyroidism"),
    "down syndrome": ("唐氏综合征", "Down syndrome"),
    "developmental delay": ("发育迟缓", "developmental delay"),
    "growth chart": ("生长曲线图", "growth chart"),
    "vaccination schedule": ("疫苗接种程序", "vaccination schedule"),
    "premature birth": ("早产", "premature birth"),
    "low birth weight": ("低出生体重", "low birth weight"),
    "teething": ("出牙", "teething"),
    "bronchiolitis infant": ("婴儿细支气管炎", "bronchiolitis"),

    # ------------------------------------------------------------------
    # Drugs — antibiotics (INN)
    # ------------------------------------------------------------------
    "penicillin": ("青霉素", "benzylpenicillinum"),
    "amoxicillin clavulanate": ("阿莫西林克拉维酸", "amoxicillinum/acidum clavulanicum"),
    "ampicillin": ("氨苄西林", "ampicillinum"),
    "cefazolin": ("头孢唑林", "cefazolinum"),
    "cefuroxime": ("头孢呋辛", "cefuroximum"),
    "cefotaxime": ("头孢噻肟", "cefotaximum"),
    "ceftazidime": ("头孢他啶", "ceftazidimum"),
    "cefepime": ("头孢吡肟", "cefepimum"),
    "cephalexin": ("头孢氨苄", "cefalexinum"),
    "meropenem": ("美罗培南", "meropenemum"),
    "imipenem": ("亚胺培南", "imipenemum"),
    "gentamicin": ("庆大霉素", "gentamicinum"),
    "amikacin": ("阿米卡星", "amikacinum"),
    "ciprofloxacin": ("环丙沙星", "ciprofloxacinum"),
    "levofloxacin": ("左氧氟沙星", "levofloxacinum"),
    "moxifloxacin": ("莫西沙星", "moxifloxacinum"),
    "clarithromycin": ("克拉霉素", "clarithromycinum"),
    "erythromycin": ("红霉素", "erythromycinum"),
    "doxycycline": ("多西环素", "doxycyclinum"),
    "tetracycline": ("四环素", "tetracyclinum"),
    "clindamycin": ("克林霉素", "clindamycinum"),
    "metronidazole": ("甲硝唑", "metronidazolum"),
    "vancomycin": ("万古霉素", "vancomycinum"),
    "linezolid": ("利奈唑胺", "linezolidum"),
    "trimethoprim sulfamethoxazole": ("复方磺胺甲噁唑", "co-trimoxazolum"),
    "nitrofurantoin": ("呋喃妥因", "nitrofurantoinum"),
    "rifampicin": ("利福平", "rifampicinum"),
    "isoniazid": ("异烟肼", "isoniazidum"),
    "ethambutol": ("乙胺丁醇", "ethambutolum"),
    "pyrazinamide": ("吡嗪酰胺", "pyrazinamidum"),
    "chloramphenicol": ("氯霉素", "chloramphenicolum"),

    # ------------------------------------------------------------------
    # Drugs — antifungal / antiviral / antiparasitic (INN)
    # ------------------------------------------------------------------
    "fluconazole": ("氟康唑", "fluconazolum"),
    "itraconazole": ("伊曲康唑", "itraconazolum"),
    "ketoconazole": ("酮康唑", "ketoconazolum"),
    "amphotericin b": ("两性霉素B", "amphotericinum B"),
    "nystatin": ("制霉菌素", "nystatinum"),
    "terbinafine": ("特比萘芬", "terbinafinum"),
    "acyclovir": ("阿昔洛韦", "aciclovirum"),
    "valacyclovir": ("伐昔洛韦", "valaciclovirum"),
    "oseltamivir": ("奥司他韦", "oseltamivirum"),
    "ganciclovir": ("更昔洛韦", "ganciclovirum"),
    "ribavirin": ("利巴韦林", "ribavirinum"),
    "tenofovir": ("替诺福韦", "tenofovirum"),
    "lamivudine": ("拉米夫定", "lamivudinum"),
    "entecavir": ("恩替卡韦", "entecavirum"),
    "zidovudine": ("齐多夫定", "zidovudinum"),
    "efavirenz": ("依非韦伦", "efavirenzum"),
    "remdesivir": ("瑞德西韦", "remdesivirum"),
    "artemether lumefantrine": ("蒿甲醚-苯芴醇", "artemetherum/lumefantrinum"),
    "artesunate": ("青蒿琥酯", "artesunatum"),
    "chloroquine": ("氯喹", "chloroquinum"),
    "hydroxychloroquine": ("羟氯喹", "hydroxychloroquinum"),
    "primaquine": ("伯氨喹", "primaquinum"),
    "albendazole": ("阿苯达唑", "albendazolum"),
    "mebendazole": ("甲苯咪唑", "mebendazolum"),
    "ivermectin": ("伊维菌素", "ivermectinum"),
    "praziquantel": ("吡喹酮", "praziquantelum"),

    # ------------------------------------------------------------------
    # Drugs — analgesics / anti-inflammatory (INN)
    # ------------------------------------------------------------------
    "diclofenac": ("双氯芬酸", "diclofenacum"),
    "naproxen": ("萘普生", "naproxenum"),
    "ketorolac": ("酮咯酸", "ketorolacum"),
    "celecoxib": ("塞来昔布", "celecoxibum"),
    "indomethacin": ("吲哚美辛", "indometacinum"),
    "tramadol": ("曲马多", "tramadolum"),
    "fentanyl": ("芬太尼", "fentanylum"),
    "oxycodone": ("羟考酮", "oxycodonum"),
    "pethidine": ("哌替啶", "pethidinum"),
    "naloxone": ("纳洛酮", "naloxonum"),
    "gabapentin": ("加巴喷丁", "gabapentinum"),
    "pregabalin": ("普瑞巴林", "pregabalinum"),
    "colchicine": ("秋水仙碱", "colchicinum"),
    "allopurinol": ("别嘌醇", "allopurinolum"),
    "lidocaine": ("利多卡因", "lidocainum"),
    "bupivacaine": ("布比卡因", "bupivacainum"),

    # ------------------------------------------------------------------
    # Drugs — cardiovascular / antihypertensive / diuretic (INN)
    # ------------------------------------------------------------------
    "enalapril": ("依那普利", "enalaprilum"),
    "ramipril": ("雷米普利", "ramiprilum"),
    "captopril": ("卡托普利", "captoprilum"),
    "valsartan": ("缬沙坦", "valsartanum"),
    "telmisartan": ("替米沙坦", "telmisartanum"),
    "candesartan": ("坎地沙坦", "candesartanum"),
    "nifedipine": ("硝苯地平", "nifedipinum"),
    "diltiazem": ("地尔硫卓", "diltiazemum"),
    "verapamil": ("维拉帕米", "verapamilum"),
    "atenolol": ("阿替洛尔", "atenololum"),
    "bisoprolol": ("比索洛尔", "bisoprololum"),
    "carvedilol": ("卡维地洛", "carvedilolum"),
    "propranolol": ("普萘洛尔", "propranololum"),
    "hydrochlorothiazide": ("氢氯噻嗪", "hydrochlorothiazidum"),
    "spironolactone": ("螺内酯", "spironolactonum"),
    "indapamide": ("吲达帕胺", "indapamidum"),
    "digoxin": ("地高辛", "digoxinum"),
    "amiodarone": ("胺碘酮", "amiodaronum"),
    "nitroglycerin": ("硝酸甘油", "glyceryli trinitras"),
    "isosorbide dinitrate": ("硝酸异山梨酯", "isosorbidi dinitras"),
    "simvastatin": ("辛伐他汀", "simvastatinum"),
    "rosuvastatin": ("瑞舒伐他汀", "rosuvastatinum"),
    "pravastatin": ("普伐他汀", "pravastatinum"),
    "ezetimibe": ("依折麦布", "ezetimibum"),
    "fenofibrate": ("非诺贝特", "fenofibratum"),
    "clopidogrel": ("氯吡格雷", "clopidogrelum"),
    "ticagrelor": ("替格瑞洛", "ticagrelorum"),
    "epinephrine": ("肾上腺素", "epinephrinum"),
    "norepinephrine": ("去甲肾上腺素", "norepinephrinum"),
    "dopamine": ("多巴胺", "dopaminum"),
    "dobutamine": ("多巴酚丁胺", "dobutaminum"),

    # ------------------------------------------------------------------
    # Drugs — anticoagulants (INN)
    # ------------------------------------------------------------------
    "enoxaparin": ("依诺肝素", "enoxaparinum"),
    "rivaroxaban": ("利伐沙班", "rivaroxabanum"),
    "apixaban": ("阿哌沙班", "apixabanum"),
    "dabigatran": ("达比加群", "dabigatranum"),
    "low molecular weight heparin": ("低分子肝素", "low molecular weight heparin"),

    # ------------------------------------------------------------------
    # Drugs — endocrine / diabetes (INN)
    # ------------------------------------------------------------------
    "glimepiride": ("格列美脲", "glimepiridum"),
    "gliclazide": ("格列齐特", "gliclazidum"),
    "glipizide": ("格列吡嗪", "glipizidum"),
    "glibenclamide": ("格列本脲", "glibenclamidum"),
    "sitagliptin": ("西格列汀", "sitagliptinum"),
    "empagliflozin": ("恩格列净", "empagliflozinum"),
    "dapagliflozin": ("达格列净", "dapagliflozinum"),
    "pioglitazone": ("吡格列酮", "pioglitazonum"),
    "acarbose": ("阿卡波糖", "acarbosum"),
    "liraglutide": ("利拉鲁肽", "liraglutidum"),
    "insulin glargine": ("甘精胰岛素", "insulinum glarginum"),
    "insulin aspart": ("门冬胰岛素", "insulinum aspartum"),
    "levothyroxine": ("左甲状腺素", "levothyroxinum"),
    "methimazole": ("甲巯咪唑", "thiamazolum"),
    "propylthiouracil": ("丙硫氧嘧啶", "propylthiouracilum"),
    "hydrocortisone": ("氢化可的松", "hydrocortisonum"),
    "methylprednisolone": ("甲泼尼龙", "methylprednisolonum"),
    "fludrocortisone": ("氟氢可的松", "fludrocortisonum"),

    # ------------------------------------------------------------------
    # Drugs — GI / respiratory / allergy (INN)
    # ------------------------------------------------------------------
    "pantoprazole": ("泮托拉唑", "pantoprazolum"),
    "esomeprazole": ("艾司奥美拉唑", "esomeprazolum"),
    "lansoprazole": ("兰索拉唑", "lansoprazolum"),
    "rabeprazole": ("雷贝拉唑", "rabeprazolum"),
    "ranitidine": ("雷尼替丁", "ranitidinum"),
    "famotidine": ("法莫替丁", "famotidinum"),
    "domperidone": ("多潘立酮", "domperidonum"),
    "metoclopramide": ("甲氧氯普胺", "metoclopramidum"),
    "ondansetron": ("昂丹司琼", "ondansetronum"),
    "loperamide": ("洛哌丁胺", "loperamidum"),
    "lactulose": ("乳果糖", "lactulosum"),
    "bisacodyl": ("比沙可啶", "bisacodylum"),
    "mesalazine": ("美沙拉嗪", "mesalazinum"),
    "ursodeoxycholic acid": ("熊去氧胆酸", "acidum ursodeoxycholicum"),
    "montelukast": ("孟鲁司特", "montelukastum"),
    "budesonide": ("布地奈德", "budesonidum"),
    "fluticasone": ("氟替卡松", "fluticasonum"),
    "ipratropium": ("异丙托溴铵", "ipratropii bromidum"),
    "tiotropium": ("噻托溴铵", "tiotropii bromidum"),
    "theophylline": ("茶碱", "theophyllinum"),
    "cetirizine": ("西替利嗪", "cetirizinum"),
    "loratadine": ("氯雷他定", "loratadinum"),
    "fexofenadine": ("非索非那定", "fexofenadinum"),
    "diphenhydramine": ("苯海拉明", "diphenhydraminum"),
    "chlorpheniramine": ("氯苯那敏", "chlorphenaminum"),
    "dextromethorphan": ("右美沙芬", "dextromethorphanum"),
    "guaifenesin": ("愈创甘油醚", "guaifenesinum"),
    "pseudoephedrine": ("伪麻黄碱", "pseudoephedrinum"),
    "ambroxol": ("氨溴索", "ambroxolum"),
    "acetylcysteine": ("乙酰半胱氨酸", "acetylcysteinum"),

    # ------------------------------------------------------------------
    # Drugs — psychotropic / neuro (INN)
    # ------------------------------------------------------------------
    "sertraline": ("舍曲林", "sertralinum"),
    "fluoxetine": ("氟西汀", "fluoxetinum"),
    "paroxetine": ("帕罗西汀", "paroxetinum"),
    "escitalopram": ("艾司西酞普兰", "escitalopramum"),
    "citalopram": ("西酞普兰", "citalopramum"),
    "venlafaxine": ("文拉法辛", "venlafaxinum"),
    "duloxetine": ("度洛西汀", "duloxetinum"),
    "amitriptyline": ("阿米替林", "amitriptylinum"),
    "mirtazapine": ("米氮平", "mirtazapinum"),
    "bupropion": ("安非他酮", "bupropionum"),
    "lithium carbonate": ("碳酸锂", "lithii carbonas"),
    "valproate": ("丙戊酸盐", "acidum valproicum"),
    "carbamazepine": ("卡马西平", "carbamazepinum"),
    "lamotrigine": ("拉莫三嗪", "lamotriginum"),
    "levetiracetam": ("左乙拉西坦", "levetiracetamum"),
    "phenytoin": ("苯妥英", "phenytoinum"),
    "phenobarbital": ("苯巴比妥", "phenobarbitalum"),
    "haloperidol": ("氟哌啶醇", "haloperidolum"),
    "risperidone": ("利培酮", "risperidonum"),
    "olanzapine": ("奥氮平", "olanzapinum"),
    "quetiapine": ("喹硫平", "quetiapinum"),
    "aripiprazole": ("阿立哌唑", "aripiprazolum"),
    "clozapine": ("氯氮平", "clozapinum"),
    "lorazepam": ("劳拉西泮", "lorazepamum"),
    "alprazolam": ("阿普唑仑", "alprazolamum"),
    "clonazepam": ("氯硝西泮", "clonazepamum"),
    "midazolam": ("咪达唑仑", "midazolamum"),
    "zolpidem": ("唑吡坦", "zolpidemum"),
    "levodopa": ("左旋多巴", "levodopum"),
    "donepezil": ("多奈哌齐", "donepezilum"),

    # ------------------------------------------------------------------
    # Drugs — oncology / immune / other (INN)
    # ------------------------------------------------------------------
    "methotrexate": ("甲氨蝶呤", "methotrexatum"),
    "cyclophosphamide": ("环磷酰胺", "cyclophosphamidum"),
    "cisplatin": ("顺铂", "cisplatinum"),
    "carboplatin": ("卡铂", "carboplatinum"),
    "doxorubicin": ("多柔比星", "doxorubicinum"),
    "paclitaxel": ("紫杉醇", "paclitaxelum"),
    "fluorouracil": ("氟尿嘧啶", "fluorouracilum"),
    "tamoxifen": ("他莫昔芬", "tamoxifenum"),
    "imatinib": ("伊马替尼", "imatinibum"),
    "rituximab": ("利妥昔单抗", "rituximabum"),
    "azathioprine": ("硫唑嘌呤", "azathioprinum"),
    "cyclosporine": ("环孢素", "ciclosporinum"),
    "tacrolimus": ("他克莫司", "tacrolimusum"),
    "mycophenolate mofetil": ("吗替麦考酚酯", "mycophenolas mofetil"),
    "adalimumab": ("阿达木单抗", "adalimumabum"),
    "infliximab": ("英夫利西单抗", "infliximabum"),
    "ondansetron antiemetic": ("止吐用昂丹司琼", "ondansetronum"),

    # ------------------------------------------------------------------
    # Drugs — supplements / electrolytes / misc (INN)
    # ------------------------------------------------------------------
    "folic acid": ("叶酸", "acidum folicum"),
    "ferrous sulfate": ("硫酸亚铁", "ferrosi sulfas"),
    "calcium carbonate": ("碳酸钙", "calcii carbonas"),
    "vitamin b12": ("维生素B12", "cyanocobalaminum"),
    "vitamin c": ("维生素C", "acidum ascorbicum"),
    "vitamin k": ("维生素K", "phytomenadionum"),
    "potassium chloride": ("氯化钾", "kalii chloridum"),
    "magnesium sulfate": ("硫酸镁", "magnesii sulfas"),
    "oral rehydration salts": ("口服补液盐", "oral rehydration salts"),
    "normal saline": ("生理盐水", "natrii chloridi solutio"),
    "dextrose solution": ("葡萄糖溶液", "dextrose solution"),
    "activated charcoal": ("活性炭", "carbo activatus"),
    "sodium bicarbonate": ("碳酸氢钠", "natrii hydrogenocarbonas"),

    # ------------------------------------------------------------------
    # Lab tests & panels
    # ------------------------------------------------------------------
    "complete blood count": ("全血细胞计数", "complete blood count"),
    "cbc": ("血常规", "complete blood count"),
    "c reactive protein": ("C反应蛋白", "C-reactive protein"),
    "erythrocyte sedimentation rate": ("红细胞沉降率", "erythrocyte sedimentation rate"),
    "esr": ("血沉", "erythrocyte sedimentation rate"),
    "hemoglobin a1c": ("糖化血红蛋白", "haemoglobin A1c"),
    "hba1c": ("糖化血红蛋白", "haemoglobin A1c"),
    "fasting blood glucose": ("空腹血糖", "fasting blood glucose"),
    "oral glucose tolerance test": ("口服葡萄糖耐量试验", "oral glucose tolerance test"),
    "serum creatinine": ("血清肌酐", "serum creatinine"),
    "blood urea nitrogen": ("血尿素氮", "blood urea nitrogen"),
    "estimated glomerular filtration rate": ("估算肾小球滤过率", "estimated glomerular filtration rate"),
    "alanine aminotransferase": ("丙氨酸氨基转移酶", "alanine aminotransferase"),
    "aspartate aminotransferase": ("天冬氨酸氨基转移酶", "aspartate aminotransferase"),
    "alkaline phosphatase": ("碱性磷酸酶", "alkaline phosphatase"),
    "gamma glutamyl transferase": ("γ-谷氨酰转移酶", "gamma-glutamyl transferase"),
    "total bilirubin": ("总胆红素", "total bilirubin"),
    "direct bilirubin": ("直接胆红素", "direct bilirubin"),
    "serum albumin": ("血清白蛋白", "serum albumin"),
    "liver function test": ("肝功能检查", "liver function test"),
    "renal function test": ("肾功能检查", "renal function test"),
    "lipid panel": ("血脂检查", "lipid panel"),
    "ldl cholesterol": ("低密度脂蛋白胆固醇", "low-density lipoprotein cholesterol"),
    "hdl cholesterol": ("高密度脂蛋白胆固醇", "high-density lipoprotein cholesterol"),
    "troponin": ("肌钙蛋白", "troponin"),
    "creatine kinase": ("肌酸激酶", "creatine kinase"),
    "brain natriuretic peptide": ("脑钠肽", "brain natriuretic peptide"),
    "d dimer": ("D-二聚体", "D-dimer"),
    "international normalized ratio": ("国际标准化比值", "international normalised ratio"),
    "inr": ("国际标准化比值", "international normalised ratio"),
    "prothrombin time": ("凝血酶原时间", "prothrombin time"),
    "activated partial thromboplastin time": ("活化部分凝血活酶时间", "activated partial thromboplastin time"),
    "fibrinogen": ("纤维蛋白原", "fibrinogen"),
    "electrolyte panel": ("电解质检查", "electrolyte panel"),
    "serum sodium": ("血清钠", "serum sodium"),
    "serum potassium": ("血清钾", "serum potassium"),
    "serum calcium": ("血清钙", "serum calcium"),
    "thyroid stimulating hormone": ("促甲状腺激素", "thyroid-stimulating hormone"),
    "free t4": ("游离甲状腺素", "free thyroxine"),
    "free t3": ("游离三碘甲状腺原氨酸", "free triiodothyronine"),
    "arterial blood gas": ("动脉血气", "arterial blood gas"),
    "lactate": ("乳酸", "lactate"),
    "procalcitonin": ("降钙素原", "procalcitonin"),
    "blood culture test": ("血培养", "blood culture"),
    "urine culture": ("尿培养", "urine culture"),
    "stool culture": ("粪便培养", "stool culture"),
    "sputum culture": ("痰培养", "sputum culture"),
    "urinalysis": ("尿液分析", "urinalysis"),
    "fecal occult blood test": ("粪便隐血试验", "faecal occult blood test"),
    "stool test": ("大便常规", "stool examination"),
    "white blood cell differential": ("白细胞分类计数", "white blood cell differential"),
    "reticulocyte count": ("网织红细胞计数", "reticulocyte count"),
    "ferritin": ("铁蛋白", "ferritin"),
    "serum iron": ("血清铁", "serum iron"),
    "vitamin d level": ("维生素D水平", "vitamin D level"),
    "uric acid": ("尿酸", "uric acid"),
    "amylase": ("淀粉酶", "amylase"),
    "lipase": ("脂肪酶", "lipase"),
    "prostate specific antigen": ("前列腺特异性抗原", "prostate-specific antigen"),
    "psa test": ("前列腺特异性抗原检测", "prostate-specific antigen test"),
    "carcinoembryonic antigen": ("癌胚抗原", "carcinoembryonic antigen"),
    "alpha fetoprotein": ("甲胎蛋白", "alpha-fetoprotein"),
    "tumor marker": ("肿瘤标志物", "tumour marker"),
    "blood type test": ("血型检测", "blood typing"),
    "cross match": ("交叉配血", "cross-matching"),
    "hiv test": ("艾滋病病毒检测", "HIV test"),
    "hepatitis panel": ("肝炎系列检查", "hepatitis panel"),
    "rapid antigen test": ("快速抗原检测", "rapid antigen test"),
    "pcr test": ("核酸检测", "polymerase chain reaction test"),
    "nucleic acid test": ("核酸检测", "nucleic acid test"),
    "antibody test": ("抗体检测", "antibody test"),
    "blood smear": ("血涂片", "blood smear"),
    "bone marrow biopsy": ("骨髓活检", "bone marrow biopsy"),
    "pap smear": ("巴氏涂片", "Papanicolaou smear"),
    "biopsy tissue": ("组织活检", "tissue biopsy"),
    "culture and sensitivity": ("培养加药敏", "culture and sensitivity"),

    # ------------------------------------------------------------------
    # Imaging
    # ------------------------------------------------------------------
    "computed tomography": ("计算机断层扫描", "computed tomography"),
    "magnetic resonance imaging": ("磁共振成像", "magnetic resonance imaging"),
    "positron emission tomography": ("正电子发射断层扫描", "positron emission tomography"),
    "pet scan": ("PET扫描", "positron emission tomography"),
    "pet ct": ("PET-CT", "positron emission tomography-computed tomography"),
    "chest x ray": ("胸部X线", "chest radiograph"),
    "abdominal x ray": ("腹部X线", "abdominal radiograph"),
    "radiograph": ("X线片", "radiograph"),
    "ultrasound scan": ("超声检查", "ultrasonography"),
    "doppler ultrasound": ("多普勒超声", "Doppler ultrasonography"),
    "echocardiography": ("超声心动图", "echocardiography"),
    "echocardiogram": ("心脏超声", "echocardiogram"),
    "angiography": ("血管造影", "angiography"),
    "coronary angiography": ("冠状动脉造影", "coronary angiography"),
    "ct angiography": ("CT血管造影", "computed tomography angiography"),
    "mammography": ("乳腺X线摄影", "mammography"),
    "mammogram": ("乳腺钼靶", "mammogram"),
    "bone scan": ("骨扫描", "bone scintigraphy"),
    "bone density scan": ("骨密度扫描", "bone densitometry"),
    "dexa scan": ("双能X线吸收测定", "dual-energy X-ray absorptiometry"),
    "fluoroscopy": ("透视", "fluoroscopy"),
    "barium swallow": ("钡餐造影", "barium swallow"),
    "barium enema": ("钡灌肠", "barium enema"),
    "intravenous pyelogram": ("静脉肾盂造影", "intravenous pyelogram"),
    "contrast agent": ("造影剂", "contrast medium"),
    "nuclear medicine scan": ("核医学扫描", "nuclear medicine scan"),
    "thyroid scan": ("甲状腺扫描", "thyroid scintigraphy"),
    "ventilation perfusion scan": ("通气灌注扫描", "ventilation-perfusion scan"),
    "electroencephalogram": ("脑电图", "electroencephalogram"),
    "eeg": ("脑电图", "electroencephalogram"),
    "electromyography": ("肌电图", "electromyography"),
    "emg": ("肌电图", "electromyography"),
    "holter monitor": ("动态心电图监测", "Holter monitor"),
    "stress test cardiac": ("心脏负荷试验", "cardiac stress test"),
    "pulmonary function test": ("肺功能检查", "pulmonary function test"),
    "spirometry": ("肺量计检查", "spirometry"),

    # ------------------------------------------------------------------
    # Procedures & treatments
    # ------------------------------------------------------------------
    "lumbar puncture": ("腰椎穿刺", "punctio lumbalis"),
    "spinal tap": ("脊椎穿刺", "lumbar puncture"),
    "thoracentesis": ("胸腔穿刺", "thoracentesis"),
    "paracentesis": ("腹腔穿刺", "paracentesis"),
    "pericardiocentesis": ("心包穿刺", "pericardiocentesis"),
    "bone marrow aspiration": ("骨髓穿刺", "bone marrow aspiration"),
    "catheterization": ("导管插入术", "catheterisation"),
    "urinary catheterization": ("导尿", "urinary catheterisation"),
    "cardiac catheterization": ("心导管检查", "cardiac catheterisation"),
    "central venous catheter": ("中心静脉导管", "central venous catheter"),
    "endotracheal intubation": ("气管插管", "endotracheal intubation"),
    "tracheostomy": ("气管切开术", "tracheostomy"),
    "mechanical ventilation": ("机械通气", "mechanical ventilation"),
    "cardiopulmonary resuscitation": ("心肺复苏", "cardiopulmonary resuscitation"),
    "defibrillation": ("除颤", "defibrillation"),
    "cardioversion": ("电复律", "cardioversion"),
    "pacemaker": ("起搏器", "pacemaker"),
    "angioplasty": ("血管成形术", "angioplasty"),
    "percutaneous coronary intervention": ("经皮冠状动脉介入", "percutaneous coronary intervention"),
    "coronary stent": ("冠状动脉支架", "coronary stent"),
    "coronary artery bypass graft": ("冠状动脉旁路移植术", "coronary artery bypass graft"),
    "hemodialysis": ("血液透析", "haemodialysis"),
    "peritoneal dialysis": ("腹膜透析", "peritoneal dialysis"),
    "plasmapheresis": ("血浆置换", "plasmapheresis"),
    "blood transfusion procedure": ("输血操作", "blood transfusion"),
    "laparoscopy": ("腹腔镜检查", "laparoscopy"),
    "laparotomy": ("剖腹术", "laparotomy"),
    "arthroscopy": ("关节镜检查", "arthroscopy"),
    "bronchoscopy": ("支气管镜检查", "bronchoscopy"),
    "cystoscopy": ("膀胱镜检查", "cystoscopy"),
    "sigmoidoscopy": ("乙状结肠镜检查", "sigmoidoscopy"),
    "upper endoscopy": ("上消化道内镜检查", "oesophagogastroduodenoscopy"),
    "ercp": ("内镜逆行胰胆管造影", "endoscopic retrograde cholangiopancreatography"),
    "polypectomy": ("息肉切除术", "polypectomy"),
    "appendectomy": ("阑尾切除术", "appendectomy"),
    "cholecystectomy": ("胆囊切除术", "cholecystectomy"),
    "hysterectomy": ("子宫切除术", "hysterectomy"),
    "mastectomy": ("乳房切除术", "mastectomy"),
    "lumpectomy": ("肿块切除术", "lumpectomy"),
    "tonsillectomy": ("扁桃体切除术", "tonsillectomy"),
    "thyroidectomy": ("甲状腺切除术", "thyroidectomy"),
    "splenectomy": ("脾切除术", "splenectomy"),
    "nephrectomy": ("肾切除术", "nephrectomy"),
    "prostatectomy": ("前列腺切除术", "prostatectomy"),
    "hernia repair": ("疝修补术", "herniorrhaphy"),
    "amputation": ("截肢", "amputation"),
    "skin graft": ("皮肤移植", "skin graft"),
    "joint replacement": ("关节置换", "joint replacement"),
    "hip replacement": ("髋关节置换", "hip arthroplasty"),
    "knee replacement": ("膝关节置换", "knee arthroplasty"),
    "cataract surgery": ("白内障手术", "cataract surgery"),
    "lasik surgery": ("准分子激光原位角膜磨镶术", "LASIK"),
    "stent placement": ("支架置入", "stent placement"),
    "drainage procedure": ("引流术", "drainage"),
    "incision and drainage": ("切开引流", "incision and drainage"),
    "debridement": ("清创术", "debridement"),
    "suturing": ("缝合", "suturing"),
    "wound dressing": ("伤口换药", "wound dressing"),
    "cauterization": ("烧灼术", "cauterisation"),
    "cryotherapy": ("冷冻治疗", "cryotherapy"),
    "phototherapy": ("光疗", "phototherapy"),
    "radiofrequency ablation": ("射频消融", "radiofrequency ablation"),
    "lithotripsy": ("碎石术", "lithotripsy"),
    "nebulization": ("雾化治疗", "nebulisation"),
    "oxygen therapy": ("氧疗", "oxygen therapy"),
    "blood pressure monitoring": ("血压监测", "blood pressure monitoring"),
    "fasting before surgery": ("术前禁食", "preoperative fasting"),
    "general anesthesia": ("全身麻醉", "general anaesthesia"),
    "local anesthesia": ("局部麻醉", "local anaesthesia"),
    "regional anesthesia": ("区域麻醉", "regional anaesthesia"),
    "sedation": ("镇静", "sedation"),
    "transfusion reaction": ("输血反应", "transfusion reaction"),
    "organ donation": ("器官捐献", "organ donation"),
    "bone marrow transplant": ("骨髓移植", "bone marrow transplant"),
    "stem cell transplant": ("干细胞移植", "stem cell transplant"),

    # ------------------------------------------------------------------
    # Anatomy — organs / systems
    # ------------------------------------------------------------------
    "heart muscle": ("心肌", "myocardium"),
    "aorta": ("主动脉", "aorta"),
    "vena cava": ("腔静脉", "vena cava"),
    "pulmonary artery": ("肺动脉", "arteria pulmonalis"),
    "coronary artery": ("冠状动脉", "arteria coronaria"),
    "capillary": ("毛细血管", "capillaris"),
    "trachea": ("气管", "trachea"),
    "bronchus": ("支气管", "bronchus"),
    "alveolus": ("肺泡", "alveolus"),
    "diaphragm": ("膈肌", "diaphragma"),
    "pleura": ("胸膜", "pleura"),
    "larynx": ("喉", "larynx"),
    "pharynx": ("咽", "pharynx"),
    "esophagus": ("食管", "oesophagus"),
    "duodenum": ("十二指肠", "duodenum"),
    "jejunum": ("空肠", "jejunum"),
    "ileum": ("回肠", "ileum"),
    "cecum": ("盲肠", "caecum"),
    "rectum": ("直肠", "rectum"),
    "anus": ("肛门", "anus"),
    "small intestine": ("小肠", "intestinum tenue"),
    "large intestine": ("大肠", "intestinum crassum"),
    "bile duct": ("胆管", "ductus choledochus"),
    "ureter": ("输尿管", "ureter"),
    "urethra": ("尿道", "urethra"),
    "adrenal gland": ("肾上腺", "glandula suprarenalis"),
    "pituitary gland": ("垂体", "glandula pituitaria"),
    "thyroid gland": ("甲状腺", "glandula thyroidea"),
    "parathyroid gland": ("甲状旁腺", "glandula parathyroidea"),
    "lymph node": ("淋巴结", "nodus lymphoideus"),
    "tonsil": ("扁桃体", "tonsilla"),
    "thymus": ("胸腺", "thymus"),
    "salivary gland": ("唾液腺", "glandula salivaria"),
    "cervix": ("子宫颈", "cervix uteri"),
    "vagina": ("阴道", "vagina"),
    "fallopian tube": ("输卵管", "tuba uterina"),
    "placenta": ("胎盘", "placenta"),
    "testis": ("睾丸", "testis"),
    "epididymis": ("附睾", "epididymis"),
    "prostate gland": ("前列腺", "prostata"),
    "penis": ("阴茎", "penis"),
    "breast tissue": ("乳腺组织", "glandula mammaria"),

    # ------------------------------------------------------------------
    # Anatomy — nervous / brain regions
    # ------------------------------------------------------------------
    "cerebrum": ("大脑", "cerebrum"),
    "cerebellum": ("小脑", "cerebellum"),
    "brainstem": ("脑干", "truncus cerebri"),
    "spinal cord": ("脊髓", "medulla spinalis"),
    "meninges": ("脑膜", "meninges"),
    "cerebrospinal fluid": ("脑脊液", "liquor cerebrospinalis"),
    "frontal lobe": ("额叶", "lobus frontalis"),
    "temporal lobe": ("颞叶", "lobus temporalis"),
    "parietal lobe": ("顶叶", "lobus parietalis"),
    "occipital lobe": ("枕叶", "lobus occipitalis"),
    "optic nerve": ("视神经", "nervus opticus"),
    "facial nerve": ("面神经", "nervus facialis"),
    "vagus nerve": ("迷走神经", "nervus vagus"),
    "sciatic nerve": ("坐骨神经", "nervus ischiadicus"),
    "median nerve": ("正中神经", "nervus medianus"),
    "spinal nerve": ("脊神经", "nervus spinalis"),
    "peripheral nerve": ("周围神经", "nervus periphericus"),

    # ------------------------------------------------------------------
    # Anatomy — bones / joints / muscles
    # ------------------------------------------------------------------
    "skull": ("颅骨", "cranium"),
    "vertebra": ("椎骨", "vertebra"),
    "spinal column": ("脊柱", "columna vertebralis"),
    "rib": ("肋骨", "costa"),
    "sternum": ("胸骨", "sternum"),
    "clavicle": ("锁骨", "clavicula"),
    "scapula": ("肩胛骨", "scapula"),
    "humerus": ("肱骨", "humerus"),
    "radius bone": ("桡骨", "radius"),
    "ulna": ("尺骨", "ulna"),
    "pelvis": ("骨盆", "pelvis"),
    "femur": ("股骨", "femur"),
    "patella": ("髌骨", "patella"),
    "tibia": ("胫骨", "tibia"),
    "fibula": ("腓骨", "fibula"),
    "cartilage": ("软骨", "cartilago"),
    "ligament": ("韧带", "ligamentum"),
    "tendon": ("肌腱", "tendo"),
    "skeletal muscle": ("骨骼肌", "musculus"),
    "biceps": ("二头肌", "musculus biceps"),
    "quadriceps": ("股四头肌", "musculus quadriceps"),
    "shoulder joint": ("肩关节", "articulatio humeri"),
    "hip joint": ("髋关节", "articulatio coxae"),
    "knee joint": ("膝关节", "articulatio genus"),
    "elbow joint": ("肘关节", "articulatio cubiti"),
    "wrist joint": ("腕关节", "articulatio radiocarpea"),
    "ankle joint": ("踝关节", "articulatio talocruralis"),

    # ------------------------------------------------------------------
    # Anatomy — surface regions
    # ------------------------------------------------------------------
    "abdomen": ("腹部", "abdomen"),
    "thorax": ("胸部", "thorax"),
    "groin": ("腹股沟", "regio inguinalis"),
    "flank": ("腰胁部", "regio lateralis"),
    "armpit": ("腋窝", "axilla"),
    "buttock": ("臀部", "regio glutealis"),
    "scalp": ("头皮", "scalp"),
    "forehead": ("前额", "frons"),
    "temple": ("太阳穴", "tempora"),
    "jaw": ("下颌", "mandibula"),
    "collarbone": ("锁骨", "clavicula"),
    "calf": ("小腿", "sura"),
    "shin": ("胫部", "shin"),
    "heel": ("足跟", "calx"),
    "sole of foot": ("足底", "planta pedis"),
    "palm of hand": ("手掌", "palma manus"),

    # ------------------------------------------------------------------
    # Departments / specialties & hospital-visit vocabulary
    # ------------------------------------------------------------------
    "emergency department": ("急诊科", "emergency department"),
    "outpatient department": ("门诊部", "outpatient department"),
    "inpatient department": ("住院部", "inpatient department"),
    "registration desk": ("挂号处", "registration desk"),
    "triage": ("分诊", "triage"),
    "fever clinic": ("发热门诊", "fever clinic"),
    "respiratory department": ("呼吸科", "department of respiratory medicine"),
    "cardiovascular department": ("心血管科", "department of cardiology"),
    "neurosurgery department": ("神经外科", "department of neurosurgery"),
    "thoracic surgery": ("胸外科", "thoracic surgery"),
    "vascular surgery": ("血管外科", "vascular surgery"),
    "plastic surgery": ("整形外科", "plastic surgery"),
    "burn department": ("烧伤科", "burn department"),
    "hematology department": ("血液科", "department of haematology"),
    "rheumatology department": ("风湿免疫科", "department of rheumatology"),
    "infectious disease department": ("感染科", "department of infectious diseases"),
    "geriatrics department": ("老年病科", "department of geriatrics"),
    "pediatric department": ("儿科", "department of paediatrics"),
    "neonatology department": ("新生儿科", "department of neonatology"),
    "obstetrics department": ("产科", "department of obstetrics"),
    "gynecology department": ("妇科", "department of gynaecology"),
    "andrology department": ("男科", "department of andrology"),
    "ent department": ("耳鼻喉科", "department of otolaryngology"),
    "stomatology department": ("口腔科", "department of stomatology"),
    "dental department": ("牙科", "dental department"),
    "pain management department": ("疼痛科", "department of pain management"),
    "anesthesiology department": ("麻醉科", "department of anaesthesiology"),
    "intensive care unit ward": ("重症监护病房", "intensive care unit"),
    "coronary care unit": ("冠心病监护病房", "coronary care unit"),
    "neonatal intensive care unit": ("新生儿重症监护病房", "neonatal intensive care unit"),
    "blood bank": ("血库", "blood bank"),
    "laboratory department": ("检验科", "department of laboratory medicine"),
    "imaging department": ("影像科", "department of medical imaging"),
    "pathology department": ("病理科", "department of pathology"),
    "nutrition department": ("营养科", "department of nutrition"),
    "traditional chinese medicine department": ("中医科", "department of traditional Chinese medicine"),
    "physical examination center": ("体检中心", "physical examination centre"),
    "nursing station": ("护士站", "nursing station"),
    "operating theater": ("手术室", "operating theatre"),
    "recovery room": ("复苏室", "post-anaesthesia care unit"),
    "isolation ward": ("隔离病房", "isolation ward"),
    "day surgery unit": ("日间手术中心", "day surgery unit"),
    "self service kiosk": ("自助机", "self-service kiosk"),
    "appointment number": ("预约号", "appointment number"),
    "queue number": ("排队号", "queue number"),
    "medical guidance desk": ("导诊台", "medical guidance desk"),
    "cashier window": ("收费窗口", "cashier"),
    "medical insurance window": ("医保窗口", "medical insurance counter"),
    "specialist clinic": ("专家门诊", "specialist clinic"),
    "general clinic": ("普通门诊", "general clinic"),
    "follow up visit": ("复诊", "follow-up visit"),
    "first visit": ("初诊", "first visit"),
    "hospital admission": ("入院", "hospital admission"),
    "hospital discharge": ("出院", "hospital discharge"),
    "discharge summary": ("出院小结", "discharge summary"),
    "medical report": ("检查报告", "medical report"),
    "lab report": ("化验单", "laboratory report"),
    "prescription slip": ("处方单", "prescription slip"),
    "case history": ("病历", "case history"),
    "outpatient card": ("就诊卡", "outpatient card"),
    "health insurance card china": ("医保卡", "medical insurance card"),
    "patient identification": ("患者身份信息", "patient identification"),
    "informed consent form": ("知情同意书", "informed consent form"),
    "wristband patient": ("患者腕带", "patient wristband"),
    "visiting hours": ("探视时间", "visiting hours"),
    "accompanying family member": ("陪护家属", "accompanying family member"),
    "ward round": ("查房", "ward round"),
    "attending physician": ("主治医师", "attending physician"),
    "chief physician": ("主任医师", "chief physician"),
    "resident doctor": ("住院医师", "resident physician"),
    "head nurse": ("护士长", "head nurse"),
    "medical assistant": ("医助", "medical assistant"),
    "interpreter service": ("翻译服务", "interpreter service"),

    # ------------------------------------------------------------------
    # Patient <-> clinician phrases
    # ------------------------------------------------------------------
    "i am allergic to penicillin": ("我对青霉素过敏", "I am allergic to penicillin"),
    "i have no known allergies": ("我没有已知的过敏史", "I have no known allergies"),
    "where does it hurt": ("哪里疼", "where does it hurt"),
    "show me where it hurts": ("指给我看哪里疼", "show me where it hurts"),
    "on a scale of one to ten": ("从一到十打分", "on a scale of one to ten"),
    "rate your pain": ("给您的疼痛评分", "rate your pain"),
    "how long have you had this": ("这个症状有多久了", "how long have you had this"),
    "when did the symptoms start": ("症状什么时候开始的", "when did the symptoms start"),
    "does it hurt here": ("这里疼吗", "does it hurt here"),
    "take a deep breath": ("深呼吸", "take a deep breath"),
    "hold your breath": ("屏住呼吸", "hold your breath"),
    "breathe normally": ("正常呼吸", "breathe normally"),
    "open your mouth": ("张开嘴", "open your mouth"),
    "stick out your tongue": ("伸出舌头", "stick out your tongue"),
    "roll up your sleeve": ("卷起袖子", "roll up your sleeve"),
    "lie down please": ("请躺下", "lie down please"),
    "sit up please": ("请坐起来", "sit up please"),
    "make a fist": ("握拳", "make a fist"),
    "i feel dizzy": ("我感到头晕", "I feel dizzy"),
    "i feel nauseous": ("我感到恶心", "I feel nauseous"),
    "i cannot breathe": ("我无法呼吸", "I cannot breathe"),
    "i have chest pain": ("我胸口疼", "I have chest pain"),
    "i have a fever": ("我发烧了", "I have a fever"),
    "i feel weak": ("我感到虚弱", "I feel weak"),
    "i am in pain": ("我很疼", "I am in pain"),
    "the pain is sharp": ("是刺痛", "the pain is sharp"),
    "the pain is dull": ("是钝痛", "the pain is dull"),
    "the pain comes and goes": ("疼痛时有时无", "the pain comes and goes"),
    "the pain is constant": ("一直在疼", "the pain is constant"),
    "i am taking medication": ("我在服药", "I am taking medication"),
    "what medications do you take": ("您在服用什么药", "what medications do you take"),
    "are you pregnant": ("您怀孕了吗", "are you pregnant"),
    "do you have any allergies": ("您有过敏史吗", "do you have any allergies"),
    "have you had surgery before": ("您以前做过手术吗", "have you had surgery before"),
    "do you smoke": ("您吸烟吗", "do you smoke"),
    "do you drink alcohol": ("您喝酒吗", "do you drink alcohol"),
    "i need to see a doctor": ("我需要看医生", "I need to see a doctor"),
    "is it serious": ("严重吗", "is it serious"),
    "do i need surgery": ("我需要手术吗", "do I need surgery"),
    "how do i take this medicine": ("这个药怎么吃", "how do I take this medicine"),
    "take twice a day": ("一天两次", "take twice a day"),
    "take after meals": ("饭后服用", "take after meals"),
    "take before meals": ("饭前服用", "take before meals"),
    "take on an empty stomach": ("空腹服用", "take on an empty stomach"),
    "do not drive after taking": ("服药后请勿驾车", "do not drive after taking"),
    "is this contagious": ("这个会传染吗", "is this contagious"),
    "when can i go home": ("我什么时候能回家", "when can I go home"),
    "i feel much better": ("我感觉好多了", "I feel much better"),
    "please call an ambulance": ("请叫救护车", "please call an ambulance"),
    "where is the nearest hospital": ("最近的医院在哪里", "where is the nearest hospital"),
    "i lost consciousness": ("我曾失去意识", "I lost consciousness"),
    "i have a chronic illness": ("我有慢性病", "I have a chronic illness"),
    "i am diabetic": ("我有糖尿病", "I am diabetic"),
    "i have high blood pressure": ("我有高血压", "I have high blood pressure"),
    "i need a refill": ("我需要续药", "I need a refill"),
    "fasting required": ("需要空腹", "fasting required"),
    "no food or drink before test": ("检查前禁食禁水", "nil by mouth before the test"),
}
