"""TransMed core data module.
Hospitals, triage rules, medications, insurance info, and medical terms.
"""
from __future__ import annotations

# ---- Hospital list -------------------------------------------------------
HOSPITALS = [
    {"id": "pumch", "name": "Peking Union Medical College Hospital", "name_zh": "北京协和医院",
     "address": "1 Shuaifuyuan, Dongcheng District, Beijing", "address_zh": "北京市东城区王府井帅府园1号",
     "phone": "+86 10 6915 6177", "hours": "Mon-Fri 08:00-17:00, Emergency 24/7",
     "rating": 4.9, "lat": 39.9094, "lng": 116.4165, "distance_km": 1.2, "wait_minutes": 25,
     "specialties": ["Internal Medicine", "Cardiology", "Neurology", "Pediatrics", "Oncology"],
     "departments": [("Internal Medicine", "内科", 20), ("Cardiology", "心内科", 15),
                     ("Neurology", "神经内科", 18), ("Pediatrics", "儿科", 12),
                     ("Emergency", "急诊", 5)],
     "languages": ["English", "Chinese", "Japanese"]},
    {"id": "ufh", "name": "United Family Hospital Beijing", "name_zh": "北京和睦家医院",
     "address": "2 Jiangtai Road, Chaoyang District, Beijing", "address_zh": "北京市朝阳区将台路2号",
     "phone": "+86 10 5927 7000", "hours": "Mon-Sun 08:00-20:00, Emergency 24/7",
     "rating": 4.95, "lat": 39.9754, "lng": 116.4677, "distance_km": 7.5, "wait_minutes": 5,
     "specialties": ["Family Medicine", "Pediatrics", "Obstetrics & Gynecology", "Dental", "Emergency"],
     "departments": [("Family Medicine", "全科", 3), ("Pediatrics", "儿科", 5),
                     ("Obstetrics & Gynecology", "妇产科", 8), ("Dental", "口腔科", 10),
                     ("Emergency", "急诊", 2), ("Cardiology", "心内科", 12),
                     ("Orthopedics", "骨科", 10), ("Dermatology", "皮肤科", 12)],
     "languages": ["English", "Chinese", "Japanese", "Korean", "French", "German"]},
    {"id": "bjh", "name": "Beijing Hospital (International Medical Center)", "name_zh": "北京医院国际医疗中心",
     "address": "1 Dongdan North Street, Dongcheng District", "address_zh": "北京市东城区东单北大街1号",
     "phone": "+86 10 6513 2266", "hours": "Mon-Fri 08:00-17:00",
     "rating": 4.8, "lat": 39.9112, "lng": 116.4193, "distance_km": 2.1, "wait_minutes": 20,
     "specialties": ["Geriatrics", "Cardiology", "Endocrinology", "Neurology"],
     "departments": [("Geriatrics", "老年医学", 25), ("Cardiology", "心内科", 20),
                     ("Endocrinology", "内分泌科", 18), ("Neurology", "神经内科", 22),
                     ("General Medicine", "全科", 15)],
     "languages": ["English", "Chinese"]},
    {"id": "amcare", "name": "Amcare Women & Children's Hospital", "name_zh": "美中宜和妇儿医院",
     "address": "9 Fangyuan West Road, Chaoyang District", "address_zh": "北京市朝阳区芳园西路9号",
     "phone": "+86 10 6434 0434", "hours": "Mon-Sun 08:30-20:00",
     "rating": 4.85, "lat": 39.9757, "lng": 116.4798, "distance_km": 8.3, "wait_minutes": 8,
     "specialties": ["Obstetrics", "Gynecology", "Pediatrics", "Pediatric Surgery"],
     "departments": [("Obstetrics", "产科", 10), ("Gynecology", "妇科", 10),
                     ("Pediatrics", "儿科", 8), ("Pediatric Surgery", "小儿外科", 15)],
     "languages": ["English", "Chinese", "Japanese"]},
    {"id": "hku", "name": "The University of Hong Kong-Shenzhen Hospital (IMC)", "name_zh": "香港大学深圳医院国际医疗中心",
     "address": "1 Haiyuan 1st Road, Futian District, Shenzhen", "address_zh": "深圳市福田区海园一路1号",
     "phone": "+86 755 8691 3333", "hours": "Mon-Sun 08:30-17:30, Emergency 24/7",
     "rating": 4.75, "lat": 22.5357, "lng": 114.0608, "distance_km": 25.0, "wait_minutes": 15,
     "specialties": ["Cardiology", "Oncology", "Orthopedics", "General Medicine", "Pediatrics"],
     "departments": [("Cardiology", "心内科", 18), ("Oncology", "肿瘤科", 25),
                     ("Orthopedics", "骨科", 15), ("General Medicine", "全科", 10),
                     ("Pediatrics", "儿科", 12), ("Emergency", "急诊", 5)],
     "languages": ["English", "Chinese", "Cantonese"]},
    {"id": "raffles", "name": "Raffles Medical Beijing Clinic", "name_zh": "北京莱佛士医疗",
     "address": "3/F, Beijing SK Tower, 6A Jiuxianqiao Road, Chaoyang District", "address_zh": "北京市朝阳区酒仙桥路甲6号SK大厦3层",
     "phone": "+86 10 6505 2288", "hours": "Mon-Fri 08:30-19:00, Sat 09:00-13:00",
     "rating": 4.7, "lat": 39.9775, "lng": 116.4914, "distance_km": 6.8, "wait_minutes": 10,
     "specialties": ["Family Medicine", "Pediatrics", "Dental", "Dermatology", "Travel Medicine"],
     "departments": [("Family Medicine", "全科", 5), ("Pediatrics", "儿科", 8),
                     ("Dental", "口腔科", 10), ("Dermatology", "皮肤科", 12),
                     ("Travel Medicine", "旅行医学", 5)],
     "languages": ["English", "Chinese", "Japanese", "Malay"]},
]


# ============================================================================
# Specialty keyword mapping: maps English/Chinese aliases → canonical specialty.
# Used by both triage (symptom → dept) and recommendation (symptom → hospital).
# ============================================================================
SPECIALTY_ALIASES: dict[str, list[str]] = {
    "Internal Medicine": [
        "internal medicine", "general internal medicine", "internal med",
        "内科", "普通内科", "内科学", "general medicine", "medicine"],
    "Family Medicine": [
        "family medicine", "family practice", "family doctor", "general practice",
        "全科", "全科医学", "家庭医学", "gp", "primary care"],
    "Cardiology": [
        "cardiology", "cardiac", "heart", "cardiovascular",
        "心内科", "心脏内科", "心脏科", "心血管"],
    "Neurology": [
        "neurology", "neurological", "brain", "nervous system",
        "神经内科", "神经科", "脑科"],
    "Pediatrics": [
        "pediatrics", "pediatric", "paediatrics", "child", "children", "baby", "infant", "toddler", "kid",
        "儿科", "小儿科", "儿童医学"],
    "Pediatric Surgery": [
        "pediatric surgery", "paediatric surgery", "小儿外科", "儿童外科"],
    "Oncology": [
        "oncology", "cancer", "tumor", "tumour", "chemotherapy",
        "肿瘤科", "肿瘤学", "癌症"],
    "Obstetrics & Gynecology": [
        "obstetrics", "gynecology", "gynaecology", "obstetrics and gynecology", "ob-gyn", "obgyn", "ob/gyn",
        "pregnancy", "prenatal", "antenatal", "labor", "delivery",
        "妇产科", "产科", "妇科", "产科医学"],
    "Gynecology": [
        "gynecology", "gynaecology", "妇科", "妇女保健"],
    "Geriatrics": [
        "geriatrics", "geriatric", "elderly", "senior", "old age", "aging",
        "老年医学", "老年科", "老年病科"],
    "Endocrinology": [
        "endocrinology", "endocrine", "diabetes", "thyroid", "hormone", "hormonal",
        "内分泌科", "内分泌"],
    "Pulmonary / Respiratory": [
        "pulmonary", "respiratory", "respiration", "lung", "pulmonology", "respirology", "copd", "asthma",
        "呼吸内科", "呼吸科", "肺科", "肺病科"],
    "Gastroenterology": [
        "gastroenterology", "gastrointestinal", "gi", "stomach", "gastric", "intestine", "bowel", "colon", "liver", "hepatology", "digestive",
        "消化内科", "消化科", "胃肠科", "肝病科"],
    "Orthopedics": [
        "orthopedics", "orthopaedics", "orthopedic", "orthopaedic", "bone", "skeletal", "joint", "musculoskeletal",
        "骨科", "矫形外科", "骨伤科"],
    "Rheumatology": [
        "rheumatology", "rheumatic", "arthritis", "rheumatism",
        "风湿免疫科", "风湿科"],
    "Dental": [
        "dental", "dentistry", "dentist", "tooth", "teeth", "oral", "mouth",
        "口腔科", "牙科", "口腔医学"],
    "Dermatology": [
        "dermatology", "dermatological", "skin",
        "皮肤科", "皮肤医学"],
    "Ophthalmology": [
        "ophthalmology", "eye", "vision", "visual", "ocular",
        "眼科", "眼科学"],
    "ENT": [
        "ent", "otolaryngology", "otorhinolaryngology", "ear nose throat", "ear, nose and throat",
        "ear", "nose", "throat", "sinus", "larynx", "pharynx",
        "耳鼻喉科", "耳鼻咽喉科", "五官科"],
    "Urology": [
        "urology", "urological", "urinary", "bladder", "kidney", "urine",
        "泌尿外科", "泌尿科"],
    "Nephrology": [
        "nephrology", "renal", "kidney",
        "肾内科", "肾脏科"],
    "Allergy & Immunology": [
        "allergy", "allergic", "allergy and immunology", "immunology", "hypersensitivity",
        "变态反应科", "过敏科", "免疫科"],
    "Infectious Diseases": [
        "infectious disease", "infectious diseases", "infection", "infective",
        "感染科", "传染病科"],
    "Mental Health / Psychiatry": [
        "mental health", "psychiatry", "psychiatric", "psychological", "psychology", "psychotherapist",
        "depression", "anxiety", "stress", "panic", "psychologist",
        "心理科", "精神科", "心理医学科", "心理咨询", "精神病学"],
    "Physiotherapy / Rehabilitation": [
        "physiotherapy", "physical therapy", "physical medicine", "rehabilitation", "rehab",
        "康复理疗科", "康复医学科", "理疗科"],
    "Emergency": [
        "emergency", "emergency medicine", "er", "icu", "critical care", "trauma", "accident",
        "急诊", "急诊科", "急诊医学科", "重症医学", "重症监护"],
    "Plastic Surgery": [
        "plastic surgery", "plastic and reconstructive", "reconstructive", "cosmetic",
        "整形外科", "整形科"],
    "Travel Medicine": [
        "travel medicine", "travel health", "travel clinic", "traveler",
        "旅行医学", "旅行健康"],
    "Traditional Chinese Medicine": [
        "traditional chinese medicine", "tcm", "chinese medicine", "herbal medicine",
        "acupuncture", "herbal",
        "中医", "中医科", "中医内科", "中药", "针灸", "传统医学"],
    "Hematology": [
        "hematology", "blood", "hematologist",
        "血液科", "血液内科"],
    "Sports Medicine": [
        "sports medicine", "sports injury", "sport medicine",
        "运动医学", "运动医学科"],
    "Cardiovascular Surgery": [
        "cardiovascular surgery", "cardiac surgery", "heart surgery",
        "心脏外科", "心血管外科"],
    "General Surgery": [
        "general surgery", "surgery", "surgical",
        "外科", "普通外科", "普外科"],
    "Neurosurgery": [
        "neurosurgery", "neuro surgery", "brain surgery",
        "神经外科", "脑外科"],
    "Oral Surgery": [
        "oral surgery", "oral maxillofacial",
        "口腔外科", "口腔颌面外科"],
    "Surgical Oncology": [
        "surgical oncology", "cancer surgery",
        "肿瘤外科"],
}


# ---------------------------------------------------------------------------
# Symptom → specialty mapping: lists of keywords (en/zh) that signal each specialty.
# Order matters: first match has highest priority (but all contribute score).
# ---------------------------------------------------------------------------
SYMPTOM_TO_SPECIALTIES: dict[str, dict] = {
    # -- Cardiovascular --
    "chest pain": {"specialties": ["Cardiology", "Emergency"], "weight": 100, "urgent": True},
    "heart attack": {"specialties": ["Cardiology", "Emergency"], "weight": 150, "urgent": True},
    "myocardial infarction": {"specialties": ["Cardiology", "Emergency"], "weight": 150, "urgent": True},
    "palpitations": {"specialties": ["Cardiology"], "weight": 60, "urgent": False},
    "heart racing": {"specialties": ["Cardiology"], "weight": 55, "urgent": False},
    "high blood pressure": {"specialties": ["Cardiology", "Internal Medicine"], "weight": 80, "urgent": False},
    "hypertension": {"specialties": ["Cardiology", "Internal Medicine"], "weight": 80, "urgent": False},
    "low blood pressure": {"specialties": ["Cardiology", "Internal Medicine"], "weight": 60, "urgent": False},
    "hypotension": {"specialties": ["Cardiology", "Internal Medicine"], "weight": 60, "urgent": False},
    "shortness of breath": {"specialties": ["Pulmonary / Respiratory", "Cardiology", "Emergency"], "weight": 120, "urgent": True},
    "difficulty breathing": {"specialties": ["Pulmonary / Respiratory", "Emergency"], "weight": 110, "urgent": True},
    "wheezing": {"specialties": ["Pulmonary / Respiratory"], "weight": 90, "urgent": False},
    # -- Respiratory --
    "cough": {"specialties": ["Pulmonary / Respiratory", "Internal Medicine", "Family Medicine"], "weight": 70, "urgent": False},
    "asthma": {"specialties": ["Pulmonary / Respiratory"], "weight": 90, "urgent": False},
    "sputum": {"specialties": ["Pulmonary / Respiratory"], "weight": 60, "urgent": False},
    "phlegm": {"specialties": ["Pulmonary / Respiratory"], "weight": 55, "urgent": False},
    "pneumonia": {"specialties": ["Pulmonary / Respiratory", "Emergency"], "weight": 110, "urgent": True},
    "bronchitis": {"specialties": ["Pulmonary / Respiratory", "Internal Medicine"], "weight": 80, "urgent": False},
    "tuberculosis": {"specialties": ["Pulmonary / Respiratory", "Infectious Diseases"], "weight": 100, "urgent": False},
    # -- Neurology --
    "headache": {"specialties": ["Neurology", "Internal Medicine", "Family Medicine"], "weight": 65, "urgent": False},
    "migraine": {"specialties": ["Neurology"], "weight": 90, "urgent": False},
    "dizziness": {"specialties": ["Neurology", "ENT", "Cardiology"], "weight": 70, "urgent": False},
    "vertigo": {"specialties": ["Neurology", "ENT"], "weight": 85, "urgent": False},
    "stroke": {"specialties": ["Neurology", "Emergency"], "weight": 180, "urgent": True},
    "seizure": {"specialties": ["Neurology", "Emergency"], "weight": 150, "urgent": True},
    "epilepsy": {"specialties": ["Neurology"], "weight": 100, "urgent": False},
    "fainting": {"specialties": ["Neurology", "Cardiology", "Emergency"], "weight": 120, "urgent": True},
    "syncope": {"specialties": ["Neurology", "Cardiology"], "weight": 100, "urgent": True},
    "numbness": {"specialties": ["Neurology", "Orthopedics"], "weight": 60, "urgent": False},
    "tingling": {"specialties": ["Neurology"], "weight": 50, "urgent": False},
    # -- Gastrointestinal --
    "stomach pain": {"specialties": ["Gastroenterology", "Internal Medicine", "Family Medicine"], "weight": 70, "urgent": False},
    "abdominal pain": {"specialties": ["Gastroenterology", "Internal Medicine"], "weight": 75, "urgent": False},
    "diarrhea": {"specialties": ["Gastroenterology", "Infectious Diseases"], "weight": 70, "urgent": False},
    "diarrhoea": {"specialties": ["Gastroenterology"], "weight": 65, "urgent": False},
    "nausea": {"specialties": ["Gastroenterology", "Internal Medicine"], "weight": 55, "urgent": False},
    "vomiting": {"specialties": ["Gastroenterology", "Emergency"], "weight": 80, "urgent": False},
    "constipation": {"specialties": ["Gastroenterology", "Family Medicine"], "weight": 45, "urgent": False},
    "bloody stool": {"specialties": ["Gastroenterology", "Emergency"], "weight": 130, "urgent": True},
    "blood in stool": {"specialties": ["Gastroenterology", "Emergency"], "weight": 130, "urgent": True},
    "heartburn": {"specialties": ["Gastroenterology", "Internal Medicine"], "weight": 55, "urgent": False},
    "reflux": {"specialties": ["Gastroenterology"], "weight": 60, "urgent": False},
    "gastritis": {"specialties": ["Gastroenterology"], "weight": 70, "urgent": False},
    "ulcer": {"specialties": ["Gastroenterology"], "weight": 70, "urgent": False},
    "liver": {"specialties": ["Gastroenterology"], "weight": 75, "urgent": False},
    # -- Musculoskeletal --
    "back pain": {"specialties": ["Orthopedics", "Physiotherapy / Rehabilitation", "Rheumatology"], "weight": 80, "urgent": False},
    "lower back pain": {"specialties": ["Orthopedics", "Physiotherapy / Rehabilitation"], "weight": 85, "urgent": False},
    "neck pain": {"specialties": ["Orthopedics", "Neurology", "Rheumatology"], "weight": 75, "urgent": False},
    "joint pain": {"specialties": ["Rheumatology", "Orthopedics"], "weight": 80, "urgent": False},
    "knee pain": {"specialties": ["Orthopedics", "Sports Medicine"], "weight": 80, "urgent": False},
    "shoulder pain": {"specialties": ["Orthopedics", "Sports Medicine"], "weight": 80, "urgent": False},
    "ankle pain": {"specialties": ["Orthopedics", "Sports Medicine"], "weight": 75, "urgent": False},
    "swollen": {"specialties": ["Orthopedics", "Rheumatology", "Internal Medicine"], "weight": 65, "urgent": False},
    "arthritis": {"specialties": ["Rheumatology", "Orthopedics"], "weight": 90, "urgent": False},
    "muscle pain": {"specialties": ["Orthopedics", "Rheumatology", "Family Medicine"], "weight": 55, "urgent": False},
    "sports injury": {"specialties": ["Sports Medicine", "Orthopedics", "Physiotherapy / Rehabilitation"], "weight": 90, "urgent": False},
    "injury": {"specialties": ["Orthopedics", "Emergency"], "weight": 90, "urgent": False},
    "sprain": {"specialties": ["Orthopedics", "Physiotherapy / Rehabilitation"], "weight": 70, "urgent": False},
    "fracture": {"specialties": ["Orthopedics", "Emergency"], "weight": 150, "urgent": True},
    "broken bone": {"specialties": ["Orthopedics", "Emergency"], "weight": 150, "urgent": True},
    # -- Dental / oral --
    "tooth pain": {"specialties": ["Dental"], "weight": 100, "urgent": False},
    "toothache": {"specialties": ["Dental"], "weight": 100, "urgent": False},
    "dental pain": {"specialties": ["Dental"], "weight": 95, "urgent": False},
    "gum": {"specialties": ["Dental"], "weight": 70, "urgent": False},
    # -- Ear, nose, throat --
    "ear pain": {"specialties": ["ENT"], "weight": 85, "urgent": False},
    "hearing loss": {"specialties": ["ENT"], "weight": 80, "urgent": False},
    "sore throat": {"specialties": ["ENT", "Internal Medicine", "Family Medicine"], "weight": 60, "urgent": False},
    "runny nose": {"specialties": ["ENT", "Internal Medicine", "Family Medicine"], "weight": 45, "urgent": False},
    "stuffy nose": {"specialties": ["ENT", "Internal Medicine"], "weight": 45, "urgent": False},
    "nasal congestion": {"specialties": ["ENT"], "weight": 50, "urgent": False},
    "sinus": {"specialties": ["ENT"], "weight": 55, "urgent": False},
    "tinnitus": {"specialties": ["ENT", "Neurology"], "weight": 70, "urgent": False},
    # -- Eye --
    "eye pain": {"specialties": ["Ophthalmology"], "weight": 90, "urgent": False},
    "blurred vision": {"specialties": ["Ophthalmology", "Neurology"], "weight": 90, "urgent": True},
    "vision loss": {"specialties": ["Ophthalmology", "Emergency", "Neurology"], "weight": 130, "urgent": True},
    "conjunctivitis": {"specialties": ["Ophthalmology"], "weight": 70, "urgent": False},
    "pink eye": {"specialties": ["Ophthalmology"], "weight": 65, "urgent": False},
    # -- Skin --
    "skin rash": {"specialties": ["Dermatology"], "weight": 90, "urgent": False},
    "rash": {"specialties": ["Dermatology", "Infectious Diseases"], "weight": 85, "urgent": False},
    "itching": {"specialties": ["Dermatology", "Allergy & Immunology"], "weight": 70, "urgent": False},
    "itchy": {"specialties": ["Dermatology", "Allergy & Immunology"], "weight": 65, "urgent": False},
    "eczema": {"specialties": ["Dermatology"], "weight": 85, "urgent": False},
    "acne": {"specialties": ["Dermatology"], "weight": 50, "urgent": False},
    # -- Allergy --
    "allergy": {"specialties": ["Allergy & Immunology", "Emergency"], "weight": 90, "urgent": False},
    "allergic": {"specialties": ["Allergy & Immunology"], "weight": 80, "urgent": False},
    "anaphylaxis": {"specialties": ["Emergency", "Allergy & Immunology"], "weight": 180, "urgent": True},
    "hives": {"specialties": ["Dermatology", "Allergy & Immunology"], "weight": 75, "urgent": False},
    # -- Infectious / systemic --
    "fever": {"specialties": ["Internal Medicine", "Infectious Diseases", "Family Medicine"], "weight": 75, "urgent": False},
    "high fever": {"specialties": ["Infectious Diseases", "Emergency", "Internal Medicine"], "weight": 120, "urgent": True},
    "temperature": {"specialties": ["Internal Medicine", "Family Medicine"], "weight": 50, "urgent": False},
    "flu": {"specialties": ["Internal Medicine", "Family Medicine"], "weight": 65, "urgent": False},
    "influenza": {"specialties": ["Internal Medicine", "Infectious Diseases"], "weight": 85, "urgent": False},
    "cold": {"specialties": ["Internal Medicine", "Family Medicine"], "weight": 40, "urgent": False},
    "common cold": {"specialties": ["Internal Medicine", "Family Medicine"], "weight": 40, "urgent": False},
    "covid": {"specialties": ["Infectious Diseases", "Pulmonary / Respiratory", "Emergency"], "weight": 110, "urgent": False},
    # -- Endocrine --
    "diabetes": {"specialties": ["Endocrinology", "Internal Medicine"], "weight": 95, "urgent": False},
    "thyroid": {"specialties": ["Endocrinology"], "weight": 80, "urgent": False},
    "hormone": {"specialties": ["Endocrinology"], "weight": 65, "urgent": False},
    "weight loss": {"specialties": ["Endocrinology", "Oncology", "Internal Medicine"], "weight": 70, "urgent": False},
    "weight gain": {"specialties": ["Endocrinology", "Internal Medicine"], "weight": 50, "urgent": False},
    "fatigue": {"specialties": ["Internal Medicine", "Endocrinology", "Family Medicine"], "weight": 50, "urgent": False},
    "tired": {"specialties": ["Internal Medicine", "Family Medicine"], "weight": 40, "urgent": False},
    # -- Urology / Renal --
    "urinary pain": {"specialties": ["Urology"], "weight": 80, "urgent": False},
    "blood in urine": {"specialties": ["Urology", "Nephrology"], "weight": 110, "urgent": False},
    "hematuria": {"specialties": ["Urology", "Nephrology"], "weight": 110, "urgent": False},
    "uti": {"specialties": ["Urology", "Infectious Diseases"], "weight": 85, "urgent": False},
    "urinary tract infection": {"specialties": ["Urology", "Infectious Diseases"], "weight": 85, "urgent": False},
    "kidney pain": {"specialties": ["Nephrology", "Urology"], "weight": 90, "urgent": False},
    "kidney stone": {"specialties": ["Urology", "Nephrology"], "weight": 100, "urgent": False},
    # -- OB/GYN --
    "pregnancy": {"specialties": ["Obstetrics & Gynecology"], "weight": 120, "urgent": False},
    "pregnant": {"specialties": ["Obstetrics & Gynecology"], "weight": 110, "urgent": False},
    "vaginal bleeding": {"specialties": ["Obstetrics & Gynecology", "Emergency"], "weight": 140, "urgent": True},
    "menstrual pain": {"specialties": ["Obstetrics & Gynecology"], "weight": 70, "urgent": False},
    "period pain": {"specialties": ["Obstetrics & Gynecology"], "weight": 65, "urgent": False},
    "menopause": {"specialties": ["Obstetrics & Gynecology", "Endocrinology"], "weight": 60, "urgent": False},
    # -- Pediatrics --
    "child fever": {"specialties": ["Pediatrics"], "weight": 110, "urgent": True},
    "child vomiting": {"specialties": ["Pediatrics", "Gastroenterology"], "weight": 85, "urgent": False},
    "child": {"specialties": ["Pediatrics", "Family Medicine"], "weight": 50, "urgent": False},
    "baby": {"specialties": ["Pediatrics"], "weight": 60, "urgent": False},
    "infant": {"specialties": ["Pediatrics"], "weight": 60, "urgent": False},
    # -- Mental health --
    "anxiety": {"specialties": ["Mental Health / Psychiatry"], "weight": 95, "urgent": False},
    "depression": {"specialties": ["Mental Health / Psychiatry"], "weight": 100, "urgent": True},
    "insomnia": {"specialties": ["Mental Health / Psychiatry", "Neurology"], "weight": 60, "urgent": False},
    "stress": {"specialties": ["Mental Health / Psychiatry", "Family Medicine"], "weight": 50, "urgent": False},
    "panic": {"specialties": ["Mental Health / Psychiatry", "Emergency"], "weight": 110, "urgent": False},
    "suicide": {"specialties": ["Mental Health / Psychiatry", "Emergency"], "weight": 200, "urgent": True},
    # -- Geriatrics / senior --
    "elderly": {"specialties": ["Geriatrics", "Internal Medicine"], "weight": 70, "urgent": False},
    "senior": {"specialties": ["Geriatrics"], "weight": 55, "urgent": False},
    "dementia": {"specialties": ["Geriatrics", "Neurology", "Mental Health / Psychiatry"], "weight": 100, "urgent": False},
    "alzheimer": {"specialties": ["Geriatrics", "Neurology"], "weight": 110, "urgent": False},
    "parkinson": {"specialties": ["Geriatrics", "Neurology"], "weight": 110, "urgent": False},
    # -- Cancer / oncology --
    "cancer": {"specialties": ["Oncology"], "weight": 140, "urgent": False},
    "tumor": {"specialties": ["Oncology"], "weight": 120, "urgent": False},
    "chemotherapy": {"specialties": ["Oncology"], "weight": 110, "urgent": False},
    # -- Trauma / emergency --
    "trauma": {"specialties": ["Emergency"], "weight": 150, "urgent": True},
    "accident": {"specialties": ["Emergency", "Orthopedics"], "weight": 130, "urgent": True},
    "bleeding": {"specialties": ["Emergency"], "weight": 160, "urgent": True},
    "burn": {"specialties": ["Emergency", "Plastic Surgery"], "weight": 140, "urgent": True},
    "animal bite": {"specialties": ["Emergency", "Infectious Diseases"], "weight": 150, "urgent": True},
    "dog bite": {"specialties": ["Emergency", "Infectious Diseases"], "weight": 140, "urgent": True},
    "poisoning": {"specialties": ["Emergency"], "weight": 180, "urgent": True},
    "choking": {"specialties": ["Emergency"], "weight": 180, "urgent": True},
    # -- Travel --
    "traveler": {"specialties": ["Travel Medicine", "Family Medicine"], "weight": 80, "urgent": False},
    "travel medicine": {"specialties": ["Travel Medicine"], "weight": 90, "urgent": False},
    "vaccine": {"specialties": ["Travel Medicine", "Infectious Diseases", "Family Medicine"], "weight": 70, "urgent": False},
    "yellow fever": {"specialties": ["Travel Medicine", "Infectious Diseases"], "weight": 100, "urgent": False},
}


# ---------------------------------------------------------------------------
# Per-hospital specialty strength score. 0-100. "80" = very strong, "40" = available but not focus.
# Missing entries default to 50 if hospital lists the specialty, 10 otherwise.
# ---------------------------------------------------------------------------
HOSPITAL_STRENGTH: dict[str, dict[str, int]] = {
    "pumch": {
        "Internal Medicine": 90, "Cardiology": 90, "Neurology": 95, "Pediatrics": 75,
        "Oncology": 90, "Endocrinology": 85, "Gastroenterology": 85, "Pulmonary / Respiratory": 80,
        "Rheumatology": 75, "Infectious Diseases": 85, "Nephrology": 75, "Geriatrics": 80,
        "Emergency": 90,
    },
    "ufh": {
        "Family Medicine": 95, "Pediatrics": 90, "Obstetrics & Gynecology": 90,
        "Gynecology": 85, "Dental": 85, "Emergency": 85, "Cardiology": 70,
        "Orthopedics": 75, "Dermatology": 80, "Internal Medicine": 75,
        "Mental Health / Psychiatry": 70, "Endocrinology": 70, "Ophthalmology": 65,
        "ENT": 65, "Travel Medicine": 85,
    },
    "bjh": {
        "Geriatrics": 95, "Cardiology": 85, "Endocrinology": 90, "Neurology": 80,
        "Internal Medicine": 90, "Oncology": 75, "Rheumatology": 75, "Nephrology": 75,
        "Pulmonary / Respiratory": 75,
    },
    "amcare": {
        "Obstetrics & Gynecology": 95, "Gynecology": 95, "Pediatrics": 90,
        "Pediatric Surgery": 85, "Dental": 70, "Family Medicine": 70,
    },
    "hku": {
        "Cardiology": 90, "Oncology": 95, "Orthopedics": 85, "Internal Medicine": 80,
        "Pediatrics": 75, "Emergency": 85, "Gastroenterology": 80,
        "Pulmonary / Respiratory": 75, "Infectious Diseases": 80,
    },
    "raffles": {
        "Family Medicine": 90, "Pediatrics": 75, "Dental": 85, "Dermatology": 85,
        "Travel Medicine": 95, "Internal Medicine": 70, "Allergy & Immunology": 70,
    },
}


# ---- Urgent symptoms (aggregate from new mapping) ------------------------
URGENT_SYMPTOMS: set[str] = {k for k, v in SYMPTOM_TO_SPECIALTIES.items() if v.get("urgent")}






# ---- Triage rules: symptom → department + advice + urgency flag ----------
TRIAGE_RULES = {
    "headache": ("Neurology", "神经内科",
                 "If severe, sudden, or with vision changes/fever — seek urgent care. Otherwise, neurology consultation recommended.",
                 "如剧烈、突发，或伴视力变化/发热，请紧急就医；否则建议神经内科就诊。", True),
    "fever": ("Internal Medicine", "内科",
              "Monitor temperature. If >39°C, with shortness of breath or confusion — seek urgent care.",
              "监测体温。如高于39℃、伴呼吸困难或意识模糊，请紧急就医。", False),
    "cough": ("Pulmonary / Respiratory", "呼吸内科",
              "If accompanied by fever, shortness of breath, or chest pain — seek urgent evaluation.",
              "如伴发热、气短或胸痛，建议紧急评估。", False),
    "shortness of breath": ("Pulmonary / Cardiology", "呼吸内科 / 心内科",
                            "Seek emergency care immediately. Do not drive yourself.",
                            "立即前往急诊。请勿自行驾车。", True),
    "chest pain": ("Cardiology / Emergency", "心内科 / 急诊",
                   "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Call 120.",
                   "🚨 立即前往急诊或拨打120。", True),
    "heart attack": ("Cardiology / Emergency", "心内科 / 急诊",
                     "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Call 120. Chew aspirin if available and not allergic.",
                     "🚨 立即前往急诊或拨打120。如无过敏，可嚼服阿司匹林。", True),
    "stroke": ("Neurology / Emergency", "神经内科 / 急诊",
               "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Time is brain — every minute matters.",
               "🚨 立即前往急诊或拨打120。时间就是大脑——每一分钟都至关重要。", True),
    "stomach pain": ("Gastroenterology", "消化内科",
                     "If severe, persistent, or with bloody stools/vomiting — emergency.",
                     "如剧烈、持续，或伴便血/呕血，请紧急就医。", False),
    "diarrhea": ("Gastroenterology", "消化内科",
                 "Stay hydrated. If blood in stools, high fever, or dehydration — see a doctor.",
                 "保持补水。如出现便血、高热或脱水，请就医。", False),
    "nausea": ("Gastroenterology / Internal Medicine", "消化内科 / 内科",
               "Rest and hydrate. If persistent or with severe abdominal pain, seek care.",
               "休息并补水。若持续或伴剧烈腹痛，请就医。", False),
    "vomiting": ("Gastroenterology / Emergency", "消化内科 / 急诊",
                 "If with blood, severe headache, or confusion — go to emergency.",
                 "如伴呕血、剧烈头痛或意识模糊，请前往急诊。", False),
    "back pain": ("Orthopedics / Physiotherapy", "骨科 / 康复理疗科",
                  "Rest, avoid heavy lifting. If with leg numbness, bladder issues, or after trauma — urgent.",
                  "休息，避免负重。如伴下肢麻木、排尿困难或外伤后，请紧急就医。", False),
    "neck pain": ("Orthopedics / Neurology", "骨科 / 神经内科",
                  "If with fever, stiff neck, and sensitivity to light — emergency (possible meningitis).",
                  "如伴发热、颈强直、畏光——需紧急评估（可能脑膜炎）。", True),
    "skin rash": ("Dermatology", "皮肤科",
                  "Avoid scratching. If with fever, blistering, or mucosal involvement — urgent care.",
                  "避免搔抓。如伴发热、水疱或黏膜受累——请紧急就医。", False),
    "itching": ("Dermatology / Allergy", "皮肤科 / 变态反应科",
                "Try cold compresses. If widespread swelling or difficulty breathing — emergency.",
                "冷敷缓解。如全身肿胀或呼吸困难，需急诊。", False),
    "allergy": ("Allergy & Immunology / Emergency", "变态反应科 / 急诊",
                "Use antihistamine if available. If anaphylaxis (swelling, difficulty breathing) — use EpiPen and go to ER.",
                "可用抗组胺药。如过敏反应（肿胀、呼吸困难）——使用肾上腺素笔并前往急诊。", True),
    "tooth pain": ("Dental", "口腔科",
                   "Avoid hot/cold stimuli. Seek dental appointment within 24-48 hours.",
                   "避免冷热刺激。24-48小时内看牙医。", False),
    "toothache": ("Dental", "口腔科",
                  "Avoid hot/cold stimuli. Seek dental appointment within 24-48 hours.",
                  "避免冷热刺激。24-48小时内看牙医。", False),
    "joint pain": ("Rheumatology / Orthopedics", "风湿免疫科 / 骨科",
                   "Rest and apply ice. If swollen, red, and hot — seek evaluation (possible infection/gout).",
                   "休息并冰敷。如关节红肿热——请就医（可能感染/痛风）。", False),
    "ear pain": ("ENT", "耳鼻喉科",
                 "If severe, with hearing loss or discharge — ENT evaluation within 24 hours.",
                 "如剧烈、伴听力下降或流脓——24小时内看耳鼻喉科。", False),
    "sore throat": ("ENT / Internal Medicine", "耳鼻喉科 / 内科",
                    "Warm fluids and rest. If difficulty breathing, drooling, or high fever — urgent.",
                    "温饮休息。如呼吸困难、流口水或高热——请急诊。", False),
    "runny nose": ("ENT / Internal Medicine", "耳鼻喉科 / 内科",
                   "Likely viral URI. Rest, fluids. If >10 days or with high fever, consult a physician.",
                   "多为病毒性上感。休息补水。如超过10天或高热，请就医。", False),
    "eye pain": ("Ophthalmology", "眼科",
                 "If with vision changes, flashes of light, or trauma — urgent ophthalmology care.",
                 "如伴视力变化、闪光感或外伤——请紧急眼科就诊。", False),
    "blurred vision": ("Ophthalmology / Neurology", "眼科 / 神经内科",
                       "If sudden onset — seek urgent medical evaluation (possible stroke or retinal issue).",
                       "如突然发生——请紧急就医（可能中风或视网膜问题）。", True),
    "dizziness": ("Neurology / ENT / Cardiology", "神经内科 / 耳鼻喉科 / 心内科",
                  "Sit or lie down. If with chest pain, shortness of breath, or focal weakness — emergency.",
                  "坐下或躺下。如伴胸痛、气短或单侧无力——急诊。", False),
    "fainting": ("Cardiology / Neurology / Emergency", "心内科 / 神经内科 / 急诊",
                 "🚨 Seek emergency evaluation — possible cardiac or neurological cause.",
                 "🚨 紧急就医评估——可能心脏或神经系统原因。", True),
    "palpitations": ("Cardiology", "心内科",
                     "If with chest pain, shortness of breath, or dizziness — seek urgent evaluation.",
                     "如伴胸痛、气短或头晕——请紧急评估。", False),
    "high blood pressure": ("Cardiology", "心内科",
                            "Monitor at home. If >180/120 with symptoms — seek emergency care (hypertensive crisis).",
                            "居家监测。如高于180/120且有症状——请急诊（高血压危象）。", True),
    "fatigue": ("Internal Medicine / Endocrinology", "内科 / 内分泌科",
                "Could be anemia, thyroid, infection, or other. Blood work recommended.",
                "可能贫血、甲状腺、感染或其他。建议验血。", False),
    "weight loss": ("Internal Medicine / Endocrinology / Oncology", "内科 / 内分泌科 / 肿瘤科",
                    "Unintentional weight loss needs evaluation. Consult internal medicine.",
                    "非刻意体重减轻需评估。请咨询内科。", False),
    "insomnia": ("Mental Health / Neurology", "心理科 / 神经内科",
                 "Sleep hygiene first. If persistent with mood changes — mental health consultation.",
                 "先改善睡眠卫生。如持续并伴情绪变化——请心理科咨询。", False),
    "anxiety": ("Mental Health / Psychiatry", "心理科 / 精神科",
                "Deep breathing exercises. If panic attacks, self-harm thoughts, or persistent — professional help.",
                "深呼吸练习。如恐慌发作、自伤念头或持续——请专业帮助。", False),
    "depression": ("Mental Health / Psychiatry", "心理科 / 精神科",
                   "Please reach out to a mental health professional. If self-harm thoughts, call emergency or a crisis hotline.",
                   "请联系心理健康专业人士。如有自伤念头，请拨打急诊或心理援助热线。", True),
    "cold": ("Internal Medicine / Family Medicine", "内科 / 全科",
             "Rest and fluids. If symptoms worsen or persist beyond 10 days, consult a physician.",
             "休息补水。如症状恶化或超过10天，请咨询医生。", False),
    "flu": ("Internal Medicine / Family Medicine", "内科 / 全科",
            "Rest, fluids, fever control. If difficulty breathing or chest pain — emergency care.",
            "休息、补水、退热。如呼吸困难或胸痛——急诊。", False),
    "urinary pain": ("Urology", "泌尿外科",
                     "Likely UTI. Drink water. If with fever/back pain — seek medical evaluation.",
                     "可能尿路感染。多喝水。如伴发热/腰痛——就医。", False),
    "constipation": ("Gastroenterology / Family Medicine", "消化内科 / 全科",
                     "Increase fiber and fluids. If persistent with severe pain, consult a physician.",
                     "增加纤维和水分。如持续伴剧烈疼痛，请咨询医生。", False),
    "bloody stool": ("Gastroenterology / Emergency", "消化内科 / 急诊",
                     "🚨 Seek medical evaluation immediately.",
                     "🚨 立即就医评估。", True),
    "blood in urine": ("Urology / Nephrology", "泌尿外科 / 肾内科",
                       "Seek medical evaluation — various causes from infection to stones or more serious conditions.",
                       "就医评估——原因从感染到结石或更严重情况不等。", False),
    "pregnancy": ("Obstetrics & Gynecology", "妇产科",
                  "Prenatal care should begin within the first trimester. Schedule an OB visit.",
                  "产前检查应在孕早期开始。预约产科就诊。", False),
    "vaginal bleeding": ("Obstetrics & Gynecology / Emergency", "妇产科 / 急诊",
                         "If pregnant — emergency evaluation immediately. If not pregnant — gynecology visit.",
                         "如怀孕——立即急诊评估。如未怀孕——妇科就诊。", True),
    "child fever": ("Pediatrics", "儿科",
                    "Monitor closely. Infants under 3 months with fever need urgent evaluation.",
                    "密切监测。3个月以下婴儿发热需紧急评估。", True),
    "child vomiting": ("Pediatrics", "儿科",
                       "Keep hydrated with small frequent sips. If lethargic, bloody vomit, or unable to drink — emergency.",
                       "少量多次补水。如嗜睡、呕血或无法饮水——急诊。", False),
    "injury": ("Orthopedics / Emergency", "骨科 / 急诊",
               "Immobilize the area. Apply ice. If obvious deformity, inability to move, or severe pain — emergency.",
               "固定受伤部位。冰敷。如明显畸形、无法活动或剧痛——急诊。", False),
    "sprain": ("Orthopedics / Physiotherapy", "骨科 / 康复理疗科",
               "RICE: Rest, Ice, Compression, Elevation. If cannot bear weight — X-ray needed.",
               "RICE原则：休息、冰敷、加压、抬高。如无法承重——需X光。", False),
    "fracture": ("Orthopedics / Emergency", "骨科 / 急诊",
                 "🚨 Immobilize and go to emergency immediately.",
                 "🚨 固定伤处并立即前往急诊。", True),
    "burn": ("Emergency / Plastic Surgery", "急诊 / 整形外科",
             "Cool running water for 10-20 minutes. Do NOT apply ice, butter, or toothpaste. Cover with sterile dressing.",
             "流动冷水冲洗10-20分钟。切勿涂冰、黄油或牙膏。无菌敷料覆盖。", True),
    "animal bite": ("Emergency / Infectious Diseases", "急诊 / 感染科",
                    "🚨 Wash wound thoroughly with soap and water for 15 minutes. Seek emergency care for rabies PEP and antibiotics.",
                    "🚨 用肥皂水彻底冲洗伤口15分钟。急诊处理狂犬病暴露和抗生素。", True),
    "suicide": ("Mental Health / Emergency", "心理科 / 急诊",
                "🚨 CALL EMERGENCY SERVICES (120) OR A CRISIS HOTLINE IMMEDIATELY. You are not alone.",
                "🚨 立即拨打120或心理援助热线。你并不孤单。", True),
    "bleeding": ("Emergency", "急诊",
                 "Apply direct pressure with clean cloth. If bleeding is heavy or doesn't stop — emergency immediately.",
                 "用干净布料直接加压。如出血量大或不止——立即急诊。", True),
    "trauma": ("Emergency / Surgery", "急诊 / 外科",
               "🚨 Do not move the person. Call 120 immediately.",
               "🚨 不要移动伤者。立即拨打120。", True),
    "poisoning": ("Emergency", "急诊",
                  "🚨 Call 120 immediately. If possible, bring the container/substance with you.",
                  "🚨 立即拨打120。如可能，携带致毒物包装。", True),
    "choking": ("Emergency", "急诊",
                "🚨 If unable to speak/breathe — perform Heimlich maneuver and call 120.",
                "🚨 如无法说话/呼吸——实施海姆立克急救法并拨打120。", True),
    "diabetes": ("Endocrinology", "内分泌科",
                 "Regular blood sugar monitoring. If very high/low with confusion — emergency.",
                 "定期血糖监测。如血糖过高/过低伴意识模糊——急诊。", False),
    "asthma": ("Pulmonary / Emergency", "呼吸内科 / 急诊",
               "Use rescue inhaler. If severe attack, lips/fingernails blue, or unable to speak — emergency.",
               "使用急救吸入剂。如严重发作、嘴唇/指甲发绀或无法说话——急诊。", True),
}


# ---- Urgent symptoms list (subset of triage keys flagged urgent) ---------
URGENT_SYMPTOMS = {k for k, v in TRIAGE_RULES.items() if v[4]}


# ---- Medications ----------------------------------------------------------
MEDICATIONS = {
    # Analgesics / Fever reducers
    "paracetamol": {
        "name": "Paracetamol (Acetaminophen)", "name_zh": "对乙酰氨基酚（扑热息痛）",
        "category": "Pain relief / Fever reducer", "category_zh": "止痛 / 退热",
        "dosage": "500mg every 6 hours as needed. Maximum 4000mg/day.",
        "dosage_zh": "按需每6小时500mg。每日最大4000mg。",
        "warnings": ["Do NOT exceed daily dose — risk of severe liver damage",
                     "Avoid with liver disease or regular alcohol use",
                     "Check other medications — many contain paracetamol"],
        "warnings_zh": ["严禁超量——有严重肝损伤风险", "肝病或经常饮酒者慎用",
                        "检查其他药物——许多含对乙酰氨基酚"],
        "side_effects": ["Nausea (rare)", "Liver damage (overdose)"],
        "rx_required": False, "price_cny": 20,
    },
    "ibuprofen": {
        "name": "Ibuprofen", "name_zh": "布洛芬",
        "category": "NSAID — Anti-inflammatory / Pain / Fever",
        "category_zh": "非甾体抗炎药——抗炎/止痛/退热",
        "dosage": "200-400mg every 6-8 hours with food. Maximum 1200mg/day (OTC).",
        "dosage_zh": "随餐服用200-400mg，每6-8小时一次。每日最大1200mg。",
        "warnings": ["Take with food — can cause stomach irritation/ulcers",
                     "Avoid if: active ulcer, kidney disease, asthma worsened by NSAIDs, last trimester of pregnancy",
                     "May increase risk of heart attack/stroke with long-term use"],
        "warnings_zh": ["随餐服用——可能刺激胃黏膜/引起溃疡",
                        "禁用：活动性溃疡、肾病、NSAID诱发哮喘、妊娠末三个月",
                        "长期使用可能增加心脏病发作/中风风险"],
        "side_effects": ["Stomach upset", "Nausea", "Dizziness", "Headache"],
        "rx_required": False, "price_cny": 25,
    },
    "aspirin": {
        "name": "Aspirin (Acetylsalicylic Acid)", "name_zh": "阿司匹林",
        "category": "Anti-platelet / Pain / Fever", "category_zh": "抗血小板/止痛/退热",
        "dosage": "Heart protection: 75-100mg daily. Pain/fever: 325-650mg every 4-6 hours.",
        "dosage_zh": "心脏保护：每日75-100mg。止痛/退热：325-650mg每4-6小时。",
        "warnings": ["Do NOT give to children under 16 (Reye's syndrome risk)",
                     "Increases bleeding risk — tell doctors/dentists before procedures"],
        "warnings_zh": ["16岁以下儿童禁用（瑞氏综合征）",
                        "增加出血风险——手术/牙科前告知医生"],
        "side_effects": ["Stomach irritation", "Increased bleeding", "Nausea"],
        "rx_required": False, "price_cny": 15,
    },
    # Antihistamines
    "loratadine": {
        "name": "Loratadine", "name_zh": "氯雷他定",
        "category": "Non-drowsy Antihistamine", "category_zh": "无镇静抗组胺药",
        "dosage": "10mg once daily.", "dosage_zh": "每日一次10mg。",
        "warnings": ["Generally well-tolerated. Rare drowsiness in some individuals."],
        "warnings_zh": ["一般耐受性良好。少数人可能嗜睡。"],
        "side_effects": ["Headache (rare)", "Dry mouth (rare)"],
        "rx_required": False, "price_cny": 30,
    },
    "cetirizine": {
        "name": "Cetirizine", "name_zh": "西替利嗪",
        "category": "Antihistamine", "category_zh": "抗组胺药",
        "dosage": "10mg once daily. May cause drowsiness.",
        "dosage_zh": "每日一次10mg。可能嗜睡——初期避免驾驶。",
        "warnings": ["Avoid alcohol and driving while adjusting to the medication"],
        "warnings_zh": ["避免饮酒和驾驶"],
        "side_effects": ["Drowsiness", "Dry mouth", "Headache"],
        "rx_required": False, "price_cny": 28,
    },
    # Stomach / GI
    "omeprazole": {
        "name": "Omeprazole", "name_zh": "奥美拉唑",
        "category": "Proton Pump Inhibitor (PPI) — Acid reducer",
        "category_zh": "质子泵抑制剂——抑酸药",
        "dosage": "20mg once daily before breakfast.", "dosage_zh": "早餐前每日一次20mg。",
        "warnings": ["Take 30-60 minutes before eating (before breakfast best)",
                     "Long-term use (>1 year) may increase bone fracture and B12 deficiency risk"],
        "warnings_zh": ["餐前30-60分钟服用（早餐前最佳）",
                        "长期使用（>1年）可能增加骨折和B12缺乏风险"],
        "side_effects": ["Headache", "Diarrhea", "Nausea"],
        "rx_required": False, "price_cny": 35,
    },
    # Cardiology
    "lisinopril": {
        "name": "Lisinopril", "name_zh": "赖诺普利",
        "category": "ACE Inhibitor — High blood pressure / Heart failure",
        "category_zh": "ACE抑制剂——降压/心衰",
        "dosage": "10-40mg once daily, as prescribed.", "dosage_zh": "遵医嘱每日一次10-40mg。",
        "warnings": ["Do NOT take if pregnant — can cause fetal harm/death",
                     "Dry cough is common (10-20%). If bothersome, consult doctor for alternative"],
        "warnings_zh": ["孕期禁用——可致胎儿损害/死亡", "干咳常见（10-20%）——如困扰请咨询医生换药"],
        "side_effects": ["Dry cough", "Dizziness", "Low blood pressure", "Headache"],
        "rx_required": True, "price_cny": 45,
    },
    "atorvastatin": {
        "name": "Atorvastatin", "name_zh": "阿托伐他汀",
        "category": "Statin — Cholesterol-lowering", "category_zh": "他汀类——降胆固醇",
        "dosage": "10-80mg once daily, usually in the evening.",
        "dosage_zh": "每日一次10-80mg，通常晚间服用。",
        "warnings": ["Report unexplained muscle pain/weakness to doctor immediately",
                     "Liver function monitoring required periodically",
                     "Avoid grapefruit/grapefruit juice — increases drug levels"],
        "warnings_zh": ["如有不明原因肌肉疼痛/无力请立即告知医生",
                        "需定期监测肝功能", "避免西柚/西柚汁——显著升高药物浓度"],
        "side_effects": ["Muscle pain", "Headache", "Nausea", "Diarrhea"],
        "rx_required": True, "price_cny": 55,
    },
    # Diabetes
    "metformin": {
        "name": "Metformin", "name_zh": "二甲双胍",
        "category": "Biguanide — Type 2 Diabetes", "category_zh": "双胍类——2型糖尿病",
        "dosage": "500-850mg 2-3 times daily with meals, as prescribed.",
        "dosage_zh": "遵医嘱随餐服用500-850mg，每日2-3次。",
        "warnings": ["Take with meals to reduce stomach upset",
                     "Stop before contrast imaging exams — tell doctors",
                     "Risk of lactic acidosis (rare, but serious) — seek help if severe muscle pain/fatigue"],
        "warnings_zh": ["随餐服用以减少胃部不适",
                        "造影检查前停药——告知医生",
                        "乳酸酸中毒风险（罕见但严重）——如严重肌肉疼痛/疲劳请就医"],
        "side_effects": ["Nausea", "Diarrhea", "Abdominal bloating", "Metallic taste"],
        "rx_required": True, "price_cny": 20,
    },
    # Respiratory
    "albuterol_salbutamol": {
        "name": "Albuterol (Salbutamol)", "name_zh": "沙丁胺醇（舒喘灵）",
        "category": "Bronchodilator — Asthma / COPD rescue inhaler",
        "category_zh": "支气管扩张剂——哮喘/慢阻肺急救吸入剂",
        "dosage": "1-2 puffs every 4-6 hours as needed for acute symptoms. For severe attack — 4-8 puffs every 20 min for 3 doses, then 1-4 puffs every 1-4 hours.",
        "dosage_zh": "急性症状：每4-6小时1-2喷。严重发作：每20分钟4-8喷，3次后改为每1-4小时1-4喷。",
        "warnings": ["This is a RESCUE inhaler — not for daily long-term control",
                     "If needing more than 2 doses/week for relief — consult doctor for controller medication",
                     "Shake well before each use; rinse mouth after use"],
        "warnings_zh": ["这是急救吸入剂——不用于日常长期控制",
                        "如每周需超过2次缓解——请咨询医生使用控制剂",
                        "每次使用前摇匀；使用后漱口"],
        "side_effects": ["Fast heart rate", "Tremor", "Nervousness", "Headache"],
        "rx_required": True, "price_cny": 70,
    },
    # Antibiotics (common prescriptions for travelers)
    "amoxicillin": {
        "name": "Amoxicillin", "name_zh": "阿莫西林",
        "category": "Penicillin Antibiotic", "category_zh": "青霉素类抗生素",
        "dosage": "500mg three times daily — complete the full course even if feeling better.",
        "dosage_zh": "500mg每日3次——即使症状好转也须服满疗程。",
        "warnings": ["⚠️ Penicillin allergy: Do NOT take if allergic (rash, swelling, anaphylaxis)",
                     "Complete the FULL course — stopping early causes antibiotic resistance",
                     "Diarrhea is common. If severe watery/bloody, contact doctor immediately"],
        "warnings_zh": ["⚠️ 青霉素过敏：如过敏（皮疹、肿胀、过敏反应）请勿服用",
                        "服满完整疗程——过早停药导致耐药",
                        "腹泻常见。如严重水样/血便，请立即就医"],
        "side_effects": ["Diarrhea", "Nausea", "Rash", "Yeast infection"],
        "rx_required": True, "price_cny": 35,
    },
    # Anti-diarrheal (OTC travel essential)
    "loperamide": {
        "name": "Loperamide", "name_zh": "洛哌丁胺（易蒙停）",
        "category": "Anti-diarrheal", "category_zh": "止泻药",
        "dosage": "2 tablets after first loose stool, then 1 tablet after each subsequent loose stool. Maximum 8 tablets/day. Do not take for more than 2 days without consulting a doctor.",
        "dosage_zh": "首次稀便后2片，之后每次稀便后1片。每日最大8片。如超过2天未缓解请就医。",
        "warnings": ["Do NOT take if you have fever/blood in stools or if diarrhea is from infection (will trap bacteria)",
                     "Stay hydrated — this only slows diarrhea, does not treat the cause",
                     "May cause constipation if overused"],
        "warnings_zh": ["如有发热/便血或感染性腹泻禁用——会困住细菌",
                        "保持补水——本品仅减缓腹泻，不治疗病因",
                        "过度使用可能便秘"],
        "side_effects": ["Constipation", "Drowsiness", "Dry mouth"],
        "rx_required": False, "price_cny": 15,
    },
    # Sleep / sedating antihistamine (common traveler aid)
    "diphenhydramine": {
        "name": "Diphenhydramine", "name_zh": "苯海拉明",
        "category": "First-generation Antihistamine / Sedating", "category_zh": "第一代抗组胺药/镇静",
        "dosage": "25-50mg at bedtime for sleep. Every 4-6 hours for allergy symptoms (maximum 300mg/day).",
        "dosage_zh": "睡前25-50mg用于睡眠。过敏症状每4-6小时（每日最大300mg）。",
        "warnings": ["Causes drowsiness — do NOT drive or operate machinery",
                     "Avoid alcohol — increases sedation",
                     "Not recommended in elderly (increased confusion/fall risk)"],
        "warnings_zh": ["引起嗜睡——请勿驾驶或操作机械",
                        "避免酒精——增强镇静",
                        "老年不推荐（增加意识混乱和跌倒风险）"],
        "side_effects": ["Drowsiness", "Dry mouth", "Blurred vision", "Constipation"],
        "rx_required": False, "price_cny": 18,
    },
    # Vitamin D (very common deficiency in northern China)
    "vitamin_d": {
        "name": "Vitamin D3 (Cholecalciferol)", "name_zh": "维生素D3（胆钙化醇）",
        "category": "Vitamin supplement", "category_zh": "维生素补充剂",
        "dosage": "1000-2000 IU (25-50mcg) once daily.", "dosage_zh": "每日一次1000-2000国际单位（25-50微克）。",
        "warnings": ["Important for bone health and immune function",
                     "Very common deficiency in winter / indoor lifestyle — test blood level if possible"],
        "warnings_zh": ["对骨骼健康和免疫功能重要",
                        "冬季/室内生活方式非常常见缺乏——可能的话验血检查"],
        "side_effects": ["Well-tolerated at recommended doses. Excess may cause kidney stones."],
        "rx_required": False, "price_cny": 40,
    },
    # Protonix/Pantoprazole (another PPI, commonly prescribed)
    "pantoprazole": {
        "name": "Pantoprazole", "name_zh": "泮托拉唑",
        "category": "Proton Pump Inhibitor (PPI) — Acid reducer",
        "category_zh": "质子泵抑制剂——抑酸药",
        "dosage": "40mg once daily before breakfast.", "dosage_zh": "早餐前每日一次40mg。",
        "warnings": ["Same warnings as omeprazole — do not stop abruptly after long-term use"],
        "warnings_zh": ["与奥美拉唑相同警告——长期使用后勿突然停药"],
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Abdominal pain"],
        "rx_required": False, "price_cny": 55,
    },
    # Antipsychotic / Mental health example
    "sertraline": {
        "name": "Sertraline", "name_zh": "舍曲林",
        "category": "SSRI Antidepressant — Depression / Anxiety / OCD / PTSD",
        "category_zh": "SSRI类抗抑郁药——抑郁/焦虑/强迫症/创伤后应激障碍",
        "dosage": "50-200mg once daily in the morning or evening.",
        "dosage_zh": "每日一次50-200mg，早晨或晚上。",
        "warnings": ["⚠️ May increase suicidal thoughts in young adults during first few weeks — monitor closely",
                     "Do NOT stop abruptly — must taper gradually under medical supervision",
                     "Takes 4-6 weeks for full effect — do not stop early because of side effects",
                     "Avoid alcohol — increases drowsiness and depression risk"],
        "warnings_zh": ["⚠️ 年轻人开始几周可能增加自杀念头——密切监测",
                        "勿突然停药——必须在医疗监督下逐渐减量",
                        "4-6周达到完全效果——不要因副作用过早停药",
                        "避免酒精——增加嗜睡和抑郁风险"],
        "side_effects": ["Nausea", "Insomnia or drowsiness", "Sexual side effects", "Headache", "Dry mouth"],
        "rx_required": True, "price_cny": 80,
    },
}


# ---- Insurance providers (removed) ---------------------------------------


# ---- Medical terms dictionary (English -> Chinese + Latin) ----------------
# Used by translator.py as an overlay on top of general-purpose translation.
MEDICAL_TERMS = {
    "headache": ("头痛", "cephalalgia"),
    "migraine": ("偏头痛", "migraine"),
    "fever": ("发热", "febris"),
    "high temperature": ("体温升高", "febris"),
    "cough": ("咳嗽", "tussis"),
    "shortness of breath": ("呼吸困难", "dyspnea"),
    "difficulty breathing": ("呼吸困难", "dyspnea"),
    "chest pain": ("胸痛", "dolor pectoris"),
    "heart attack": ("心脏病发作", "infarctus myocardii"),
    "stroke": ("中风", "apoplexia / ictus cerebrovascularis"),
    "nausea": ("恶心", "nausea"),
    "vomiting": ("呕吐", "vomitus"),
    "stomach pain": ("胃痛", "dolor abdominis"),
    "abdominal pain": ("腹痛", "dolor abdominis"),
    "diarrhea": ("腹泻", "diarrhoea"),
    "constipation": ("便秘", "constipatio"),
    "blood in stool": ("便血", "haematochezia"),
    "bloody stool": ("便血", "haematochezia"),
    "back pain": ("背痛", "dolor dorsi"),
    "neck pain": ("颈痛", "dolor cervicis"),
    "muscle pain": ("肌肉痛", "myalgia"),
    "joint pain": ("关节痛", "arthralgia"),
    "skin rash": ("皮疹", "exanthema"),
    "rash": ("皮疹", "exanthema"),
    "itching": ("瘙痒", "pruritus"),
    "hives": ("荨麻疹", "urticaria"),
    "allergy": ("过敏", "allergia"),
    "allergic reaction": ("过敏反应", "reactio allergica"),
    "anaphylaxis": ("过敏性休克", "anaphylaxis"),
    "dizziness": ("头晕", "vertigo"),
    "lightheadedness": ("头晕目眩", "lipothymia"),
    "fainting": ("晕厥", "syncope"),
    "palpitations": ("心悸", "palpitatio"),
    "high blood pressure": ("高血压", "hypertensio"),
    "hypertension": ("高血压", "hypertensio"),
    "low blood pressure": ("低血压", "hypotensio"),
    "fatigue": ("疲劳", "lassitudo"),
    "tiredness": ("疲倦", "lassitudo"),
    "weakness": ("无力", "debilitas"),
    "weight loss": ("体重减轻", "decrementum ponderis"),
    "weight gain": ("体重增加", "incrementum ponderis"),
    "insomnia": ("失眠", "insomnia"),
    "anxiety": ("焦虑", "anxietas"),
    "depression": ("抑郁", "depressio"),
    "sore throat": ("咽喉痛", "pharyngodynia"),
    "runny nose": ("流鼻涕", "rhinorrhoea"),
    "stuffy nose": ("鼻塞", "congestio nasi"),
    "sneezing": ("打喷嚏", "sternutatio"),
    "ear pain": ("耳痛", "otalgia"),
    "ear infection": ("耳朵感染", "otitis"),
    "tooth pain": ("牙痛", "dolor dentium"),
    "toothache": ("牙痛", "dolor dentium"),
    "eye pain": ("眼痛", "ophthalmalgia"),
    "blurred vision": ("视力模糊", "visio confusa"),
    "double vision": ("复视", "diplopia"),
    "red eye": ("红眼", "oculus ruber"),
    "burning sensation": ("烧灼感", "sensio ardens"),
    "tingling": ("麻刺感", "paresthesia"),
    "numbness": ("麻木", "hypoesthesia"),
    "swelling": ("肿胀", "tumor"),
    "inflammation": ("炎症", "inflammatio"),
    "injury": ("受伤", "injurium"),
    "wound": ("伤口", "vulnus"),
    "bruise": ("淤青", "contusio"),
    "bleeding": ("出血", "haemorrhagia"),
    "sprain": ("扭伤", "distorsio"),
    "fracture": ("骨折", "fractura"),
    "burn": ("烧伤", "ustio"),
    "animal bite": ("动物咬伤", "morsus animalis"),
    "dog bite": ("狗咬伤", "morsus canis"),
    "cat bite": ("猫咬伤", "morsus felis"),
    "snake bite": ("蛇咬伤", "morsus serpentis"),
    "poisoning": ("中毒", "intoxicatio"),
    "choking": ("窒息", "suffocatio"),
    "trauma": ("创伤", "trauma"),
    "asthma": ("哮喘", "asthma"),
    "wheezing": ("喘息", "wheezing"),
    "pneumonia": ("肺炎", "pneumonia"),
    "bronchitis": ("支气管炎", "bronchitis"),
    "tuberculosis": ("结核病", "tuberculosis"),
    "diabetes": ("糖尿病", "diabetes mellitus"),
    "diabetes type 1": ("1型糖尿病", "diabetes mellitus typus 1"),
    "diabetes type 2": ("2型糖尿病", "diabetes mellitus typus 2"),
    "thyroid": ("甲状腺", "glandula thyreoidea"),
    "hyperthyroidism": ("甲状腺功能亢进", "hyperthyreoidismus"),
    "hypothyroidism": ("甲状腺功能减退", "hypothyreoidismus"),
    "heart disease": ("心脏病", "cardiopathia"),
    "coronary artery disease": ("冠心病", "morbi coronarii arteriarum"),
    "heart failure": ("心力衰竭", "insufficientia cardiaca"),
    "arrhythmia": ("心律不齐", "arrhythmia"),
    "atrial fibrillation": ("心房颤动", "fibrillatio atrialium"),
    "kidney disease": ("肾病", "nephropathia"),
    "liver disease": ("肝病", "hepatopathia"),
    "hepatitis": ("肝炎", "hepatitis"),
    "cirrhosis": ("肝硬化", "cirrhosis hepatis"),
    "cancer": ("癌症", "cancer"),
    "tumor": ("肿瘤", "tumor"),
    "malignant": ("恶性", "malignus"),
    "benign": ("良性", "benignus"),
    "ulcer": ("溃疡", "ulcus"),
    "gastritis": ("胃炎", "gastritis"),
    "gastroenteritis": ("胃肠炎", "gastroenteritis"),
    "appendicitis": ("阑尾炎", "appendicitis"),
    "hernia": ("疝气", "hernia"),
    "hemorrhoids": ("痔疮", "haemorrhoides"),
    "piles": ("痔疮", "haemorrhoides"),
    "arthritis": ("关节炎", "arthritis"),
    "osteoarthritis": ("骨关节炎", "osteoarthritis"),
    "rheumatoid arthritis": ("类风湿关节炎", "arthritis rheumatoidea"),
    "gout": ("痛风", "podagra"),
    "osteoporosis": ("骨质疏松症", "osteoporosis"),
    "anemia": ("贫血", "anaemia"),
    "iron deficiency": ("缺铁", "defectus ferri"),
    "vitamin d deficiency": ("维生素D缺乏", "defectus vitaminis D"),
    "cholesterol": ("胆固醇", "cholesterolum"),
    "high cholesterol": ("高胆固醇", "hypercholesterolaemia"),
    "triglycerides": ("甘油三酯", "triglycerida"),
    "stroke risk": ("中风风险", "ictus cerebrovascularis periculum"),
    "dementia": ("痴呆", "dementia"),
    "alzheimer": ("阿尔茨海默病", "morbus Alzheimer"),
    "parkinson": ("帕金森病", "morbus Parkinson"),
    "epilepsy": ("癫痫", "epilepsia"),
    "seizure": ("发作（癫痫）", "epileptica concussio"),
    "migraine headache": ("偏头痛发作", "cephalalgia migrainosa"),
    "pregnancy": ("怀孕", "graviditas"),
    "pregnant": ("怀孕的", "gravida"),
    "miscarriage": ("流产", "abortus spontaneus"),
    "vaginal bleeding": ("阴道出血", "haemorrhagia vaginalis"),
    "morning sickness": ("晨吐", "vomitus matutinus"),
    "labor": ("分娩", "partus"),
    "childbirth": ("分娩", "partus"),
    "menstruation": ("月经", "menstruatio"),
    "menopause": ("更年期", "menopausa"),
    "contraception": ("避孕", "contraceptio"),
    "birth control": ("节育", "anticonceptio"),
    "condom": ("避孕套", "condomus"),
    "sexually transmitted disease": ("性传播疾病", "morbus sexualiter transmissus"),
    "std": ("性传播疾病", "morbus sexualiter transmissus"),
    "hiv": ("艾滋病毒", "HIV"),
    "aids": ("艾滋病", "AIDS"),
    "hospital": ("医院", "hospitalis"),
    "clinic": ("诊所", "clinica"),
    "doctor": ("医生", "medicus"),
    "physician": ("医师", "physicus"),
    "nurse": ("护士", "nutrix"),
    "pharmacist": ("药剂师", "pharmacista"),
    "pharmacy": ("药房", "officina pharmaceutica"),
    "drugstore": ("药店", "officina pharmaceutica"),
    "prescription": ("处方", "praescriptio"),
    "medicine": ("药品", "medicamentum"),
    "medication": ("药物", "medicamentum"),
    "pill": ("药片", "pilula"),
    "tablet": ("片剂", "tabella"),
    "capsule": ("胶囊", "capsula"),
    "ointment": ("药膏", "unguentum"),
    "cream": ("乳膏", "cremor"),
    "drops": ("滴剂", "guttae"),
    "injection": ("注射", "iniectio"),
    "syringe": ("注射器", "syringa"),
    "needle": ("针", "acus"),
    "dressing": ("敷料", "sphacelarium"),
    "bandage": ("绷带", "vitta"),
    "gauze": ("纱布", "carbasus"),
    "suture": ("缝合", "sutura"),
    "stitch": ("缝线", "sutura"),
    "cast": ("石膏", "emplastrum gypsum"),
    "crutches": ("拐杖", "baculi auxiliares"),
    "wheelchair": ("轮椅", "sella curulata ambulatoria"),
    "ambulance": ("救护车", "ambulancia"),
    "emergency room": ("急诊室", "taberna urgentiae"),
    "icu": ("重症监护室", "unitas curae intensivae"),
    "intensive care unit": ("重症监护室", "unitas curae intensivae"),
    "operating room": ("手术室", "cubiculum chirurgicum"),
    "surgery": ("外科手术", "chirurgia"),
    "operation": ("手术", "operatio"),
    "x-ray": ("X光检查", "radiographia"),
    "ct scan": ("CT扫描", "tomographia computata"),
    "mri": ("核磁共振成像", "magneticum resonantiae imaginatio"),
    "ultrasound": ("超声波检查", "ultrasonographia"),
    "blood test": ("验血", "examen sanguinis"),
    "urine test": ("验尿", "examen urinae"),
    "blood pressure": ("血压", "pressio sanguinis"),
    "pulse": ("脉搏", "pulsus"),
    "temperature": ("体温", "temperatura"),
    "heart rate": ("心率", "frequentia cardiaca"),
    "respiratory rate": ("呼吸频率", "frequentia respiratoria"),
    "oxygen saturation": ("血氧饱和度", "saturatio oxygenii"),
    "blood sugar": ("血糖", "glucosum sanguinis"),
    "glucose": ("葡萄糖", "glucosum"),
    "insulin": ("胰岛素", "insulina"),
    "vaccination": ("疫苗接种", "vaccinatio"),
    "vaccine": ("疫苗", "vaccinum"),
    "immunization": ("免疫接种", "immunisatio"),
    "flu shot": ("流感疫苗", "vaccinum influenzae"),
    "covid vaccine": ("新冠疫苗", "vaccinum COVID-19"),
    "rabies": ("狂犬病", "rabies"),
    "malaria": ("疟疾", "malaria"),
    "dengue": ("登革热", "dengue"),
    "yellow fever": ("黄热病", "febris flava"),
    "tetanus": ("破伤风", "tetanus"),
    "chickenpox": ("水痘", "varicella"),
    "measles": ("麻疹", "morbilli"),
    "mumps": ("腮腺炎", "parotitis epidemica"),
    "rubella": ("风疹", "rubella"),
    "polio": ("小儿麻痹症", "poliomyelitis"),
    "common cold": ("普通感冒", "rhinopharyngitis acuta"),
    "influenza": ("流行性感冒", "influenza"),
    "flu": ("流感", "influenza"),
    "coronavirus": ("冠状病毒", "coronavirus"),
    "covid": ("新冠病毒", "COVID-19"),
    "sinus infection": ("鼻窦感染", "sinusitis"),
    "sinusitis": ("鼻窦炎", "sinusitis"),
    "ear infection": ("耳部感染", "otitis"),
    "conjunctivitis": ("结膜炎", "conjunctivitis"),
    "pink eye": ("红眼病", "conjunctivitis"),
    "stye": ("麦粒肿", "hordeolum"),
    "dandruff": ("头皮屑", "pityriasis capitis"),
    "acne": ("痤疮", "acne"),
    "psoriasis": ("牛皮癣", "psoriasis"),
    "eczema": ("湿疹", "eczema"),
    "urinary tract infection": ("尿路感染", "infectio tractus urinarii"),
    "uti": ("尿路感染", "infectio tractus urinarii"),
    "kidney stone": ("肾结石", "calculus renalis"),
    "gallstone": ("胆结石", "calculus biliaris"),
    "bladder infection": ("膀胱感染", "cystitis"),
    "prostate": ("前列腺", "prostata"),
    "erectile dysfunction": ("勃起功能障碍", "dysfunction erectilis"),
    "testicular pain": ("睾丸疼痛", "dolor testicularis"),
    "appendix": ("阑尾", "appendix vermiformis"),
    "herpes": ("疱疹", "herpes"),
    "cold sore": ("唇疱疹", "herpes labialis"),
    "shingles": ("带状疱疹", "herpes zoster"),
    "wart": ("疣", "verruca"),
    "fungal infection": ("真菌感染", "infectio fungalis"),
    "athlete foot": ("脚气", "pedis athletae"),
    "ringworm": ("癣", "tinea"),
    "lice": ("头虱", "pediculi"),
    "scabies": ("疥疮", "scabies"),
    "allergy testing": ("过敏测试", "testis allergiae"),
    "food allergy": ("食物过敏", "allergia ciborum"),
    "peanut allergy": ("花生过敏", "allergia arachis"),
    "milk allergy": ("牛奶过敏", "allergia lactis"),
    "lactose intolerance": ("乳糖不耐受", "intolerantia lactosi"),
    "gluten intolerance": ("麸质不耐受", "intolerantia gluteni"),
    "celiac disease": ("乳糜泻", "morbus coeliacus"),
    "first aid": ("急救", "auxilium primum"),
    "cpr": ("心肺复苏", "reanimatio cardiopulmonalis"),
    "heimlich maneuver": ("海姆立克急救法", "maneuver Heimlich"),
    "antibiotic": ("抗生素", "antibioticum"),
    "antibiotic resistance": ("抗生素耐药性", "resistentia antibiotica"),
    "pain killer": ("止痛药", "analgesicum"),
    "analgesic": ("镇痛剂", "analgesicum"),
    "anti inflammatory": ("消炎药", "antiinflammatorium"),
    "ibuprofen": ("布洛芬", "ibuprofenum"),
    "paracetamol": ("对乙酰氨基酚", "paracetamolum"),
    "acetaminophen": ("对乙酰氨基酚", "acetaminophenum"),
    "aspirin": ("阿司匹林", "acidum acetylsalicylicum"),
    "antihistamine": ("抗组胺药", "antihistaminicum"),
    "steroid": ("类固醇", "steroidum"),
    "corticosteroid": ("糖皮质激素", "corticosteroidum"),
    "insulin": ("胰岛素", "insulina"),
    "inhaler": ("吸入剂", "inhalator"),
    "vitamin": ("维生素", "vitamina"),
    "supplement": ("补充剂", "supplementum"),
    "blood type": ("血型", "typus sanguinis"),
    "blood group": ("血型", "typus sanguinis"),
    "blood donation": ("献血", "donatio sanguinis"),
    "organ transplant": ("器官移植", "transplantatio organi"),
    "dialysis": ("透析", "dialysis"),
    "chemotherapy": ("化疗", "chemotherapia"),
    "radiation therapy": ("放疗", "radiotherapia"),
    "physical therapy": ("物理治疗", "therapia physica"),
    "rehabilitation": ("康复", "rehabilitatio"),
    "counseling": ("心理咨询", "consilium psychologicum"),
    "therapy": ("治疗", "therapia"),
    "treatment": ("治疗", "tractatio"),
    "diagnosis": ("诊断", "diagnosis"),
    "prognosis": ("预后", "prognosis"),
    "symptom": ("症状", "symptoma"),
    "sign": ("体征", "signum"),
    "chronic": ("慢性", "chronicus"),
    "acute": ("急性", "acutus"),
    "bacterial": ("细菌性", "bacterialis"),
    "viral": ("病毒性", "viralis"),
    "infectious": ("传染性", "infectiosus"),
    "contagious": ("传染性", "contagiosus"),
    "epidemic": ("流行病", "epidemia"),
    "pandemic": ("大流行病", "pandemia"),
    "quarantine": ("隔离", "quarantina"),
    "isolation": ("隔离", "isolatio"),
    "medical certificate": ("医疗证明", "certificatum medicum"),
    "prescription refill": ("处方续药", "renovatio praescriptionis"),
    "generic drug": ("仿制药", "medicamentum genericum"),
    "brand name": ("品牌药", "nomen notum"),
    "side effect": ("副作用", "effectus secundarius"),
    "dosage": ("剂量", "dosis"),
    "dosage form": ("剂型", "forma dosis"),
    "over the counter": ("非处方药", "sine praescriptione"),
    "otc": ("非处方药", "sine praescriptione"),
    "medical record": ("病历", "commentarium medicum"),
    "medical history": ("病史", "historia medicorum"),
    "allergy list": ("过敏列表", "index allergiarum"),
    "insurance card": ("保险卡", "cardis assecurationis"),
    "policy number": ("保单号", "numerus consilii"),
    "pre authorization": ("预授权", "praeauctoritas"),
    "direct billing": ("直付", "exsolutio directa"),
    "claim form": ("索赔表", "formula petitionis"),
    "reimbursement": ("报销", "refectio"),
    "deductible": ("免赔额", "deductibile"),
    "co payment": ("自付额", "co-pagamentum"),
    "out of pocket": ("自掏腰包", "ex propria pecunia"),
    "in network": ("网络内医院", "in retis"),
    "out of network": ("网络外医院", "extra retem"),
    "medical evacuation": ("医疗转运", "evacuatio medica"),
    "repatriation": ("遣返", "repatriatio"),
    "second opinion": ("第二诊疗意见", "secundum consilium medicum"),
    "general practitioner": ("全科医生", "medicus generalis"),
    "gp": ("全科医生", "medicus generalis"),
    "specialist": ("专科医生", "specialista"),
    "pediatrician": ("儿科医生", "pediatricus"),
    "obstetrician": ("产科医生", "obstetricius"),
    "gynecologist": ("妇科医生", "gynecologus"),
    "cardiologist": ("心脏科医生", "cardiologus"),
    "neurologist": ("神经科医生", "neurologus"),
    "orthopedic surgeon": ("骨科医生", "chirurgus orthopaedius"),
    "dermatologist": ("皮肤科医生", "dermatologus"),
    "ophthalmologist": ("眼科医生", "ophthalmologus"),
    "psychiatrist": ("精神科医生", "psychiatr"),
    "psychologist": ("心理学家", "psychologus"),
    "dentist": ("牙医", "dentista"),
    "surgeon": ("外科医生", "chirurgus"),
    "anesthesiologist": ("麻醉科医生", "anesthesiologus"),
    "radiologist": ("放射科医生", "radiologus"),
    "pathologist": ("病理科医生", "pathologus"),
    "pharmacy in chinese hospital": ("中国医院的药房", "officina pharmaceutica in hospitali sinensi"),
    "emergency": ("急诊", "urgentia"),
    "medical emergency": ("医疗紧急情况", "urgentia medica"),
    "call 120": ("拨打120", "voca 120"),
    "appointment": ("预约", "constitutum"),
    "consultation": ("会诊", "consultatio"),
    "follow up": ("随访", "sequela"),
    "referral": ("转诊", "recommendatio"),
    "check up": ("体检", "examen medicum generale"),
    "annual physical": ("年度体检", "examen physicum annuum"),
    "health screening": ("健康筛查", "exploratio salutaris"),
    "tcm": ("中医", "medicina tradita Sinensis"),
    "acupuncture": ("针灸", "acupunctura"),
    "herbal medicine": ("草药", "medicamentum herbale"),
    "massage": ("按摩", "massagium"),
    "yoga": ("瑜伽", "yoga"),
    "meditation": ("冥想", "meditatio"),
    # ---- Expansion 2026-06: high-frequency clinical vocabulary (symptoms, anatomy,
    # conditions, WHO essential medicines, labs, procedures, departments, hospital admin).
    # Format: english -> (中文, latin/INN). Sources: ICD-10/11 chapter terms, WHO Model
    # List of Essential Medicines, common bilingual clinical glossaries. ----
    # --- symptoms / signs ---
    "chills": ("寒战", "rigores"),
    "shivering": ("发抖", "tremor frigoris"),
    "sweating": ("出汗", "sudoratio"),
    "night sweats": ("盗汗", "sudores nocturni"),
    "weight loss": ("体重减轻", "deminutio ponderis"),
    "weight gain": ("体重增加", "auctus ponderis"),
    "loss of appetite": ("食欲不振", "anorexia"),
    "sore throat": ("咽喉痛", "pharyngodynia"),
    "runny nose": ("流涕", "rhinorrhoea"),
    "nasal congestion": ("鼻塞", "obstructio nasi"),
    "sneezing": ("打喷嚏", "sternutatio"),
    "wheezing": ("喘息", "sibilus"),
    "coughing up blood": ("咯血", "haemoptysis"),
    "heartburn": ("烧心", "pyrosis"),
    "bloating": ("腹胀", "meteorismus"),
    "indigestion": ("消化不良", "dyspepsia"),
    "blood in urine": ("血尿", "haematuria"),
    "painful urination": ("排尿疼痛", "dysuria"),
    "frequent urination": ("尿频", "pollakiuria"),
    "urinary urgency": ("尿急", "urgentia mingendi"),
    "incontinence": ("失禁", "incontinentia"),
    "swelling": ("肿胀", "tumor"),
    "edema": ("水肿", "oedema"),
    "numbness": ("麻木", "hypaesthesia"),
    "tingling": ("刺痛感", "paraesthesia"),
    "blurred vision": ("视力模糊", "visus obscuratus"),
    "double vision": ("复视", "diplopia"),
    "ringing in ears": ("耳鸣", "tinnitus"),
    "hearing loss": ("听力下降", "hypoacusis"),
    "seizure": ("癫痫发作", "convulsio epileptica"),
    "convulsion": ("抽搐", "convulsio"),
    "tremor": ("震颤", "tremor"),
    "confusion": ("意识模糊", "confusio mentis"),
    "memory loss": ("记忆减退", "amnesia"),
    "insomnia": ("失眠", "insomnia"),
    "anxiety": ("焦虑", "anxietas"),
    "depressed mood": ("情绪低落", "humor depressus"),
    "jaundice": ("黄疸", "icterus"),
    "dehydration": ("脱水", "deshydratio"),
    "dry mouth": ("口干", "xerostomia"),
    "blood pressure": ("血压", "tensio arterialis"),
    "irregular heartbeat": ("心律不齐", "arrhythmia"),
    "chest tightness": ("胸闷", "oppressio pectoris"),
    "abdominal cramps": ("腹部绞痛", "tormina abdominis"),
    "loss of consciousness": ("意识丧失", "amissio conscientiae"),
    # --- anatomy ---
    "brain": ("脑", "cerebrum"),
    "throat": ("咽喉", "pharynx"),
    "lung": ("肺", "pulmo"),
    "heart": ("心脏", "cor"),
    "liver": ("肝", "hepar"),
    "gallbladder": ("胆囊", "vesica fellea"),
    "stomach": ("胃", "gaster"),
    "intestine": ("肠", "intestinum"),
    "colon": ("结肠", "colon"),
    "kidney": ("肾", "ren"),
    "bladder": ("膀胱", "vesica urinaria"),
    "pancreas": ("胰腺", "pancreas"),
    "spleen": ("脾", "lien"),
    "spine": ("脊柱", "columna vertebralis"),
    "bone": ("骨", "os"),
    "joint": ("关节", "articulatio"),
    "artery": ("动脉", "arteria"),
    "vein": ("静脉", "vena"),
    "nerve": ("神经", "nervus"),
    "thyroid": ("甲状腺", "glandula thyroidea"),
    "prostate": ("前列腺", "prostata"),
    "uterus": ("子宫", "uterus"),
    "ovary": ("卵巢", "ovarium"),
    # --- conditions / diseases ---
    "diabetes": ("糖尿病", "diabetes mellitus"),
    "type 2 diabetes": ("2型糖尿病", "diabetes mellitus typi II"),
    "asthma": ("哮喘", "asthma"),
    "pneumonia": ("肺炎", "pneumonia"),
    "bronchitis": ("支气管炎", "bronchitis"),
    "copd": ("慢性阻塞性肺疾病", "morbus pulmonis obstructivus chronicus"),
    "tuberculosis": ("结核病", "tuberculosis"),
    "hepatitis": ("肝炎", "hepatitis"),
    "cirrhosis": ("肝硬化", "cirrhosis hepatis"),
    "gastritis": ("胃炎", "gastritis"),
    "peptic ulcer": ("消化性溃疡", "ulcus pepticum"),
    "appendicitis": ("阑尾炎", "appendicitis"),
    "gallstones": ("胆结石", "cholelithiasis"),
    "kidney stones": ("肾结石", "nephrolithiasis"),
    "urinary tract infection": ("尿路感染", "infectio tractus urinarii"),
    "anemia": ("贫血", "anaemia"),
    "leukemia": ("白血病", "leukaemia"),
    "lymphoma": ("淋巴瘤", "lymphoma"),
    "arthritis": ("关节炎", "arthritis"),
    "osteoporosis": ("骨质疏松", "osteoporosis"),
    "gout": ("痛风", "arthritis urica"),
    "epilepsy": ("癫痫", "epilepsia"),
    "parkinson's disease": ("帕金森病", "morbus Parkinsoni"),
    "alzheimer's disease": ("阿尔茨海默病", "morbus Alzheimeri"),
    "schizophrenia": ("精神分裂症", "schizophrenia"),
    "hypothyroidism": ("甲状腺功能减退", "hypothyreoidismus"),
    "hyperthyroidism": ("甲状腺功能亢进", "hyperthyreoidismus"),
    "coronary heart disease": ("冠心病", "morbus cordis coronarius"),
    "heart failure": ("心力衰竭", "insufficientia cordis"),
    "atrial fibrillation": ("心房颤动", "fibrillatio atrialis"),
    "sepsis": ("脓毒症", "sepsis"),
    "covid-19": ("新型冠状病毒感染", "COVID-19"),
    "influenza": ("流行性感冒", "influenza"),
    "conjunctivitis": ("结膜炎", "conjunctivitis"),
    "otitis media": ("中耳炎", "otitis media"),
    "sinusitis": ("鼻窦炎", "sinusitis"),
    "eczema": ("湿疹", "eczema"),
    "psoriasis": ("银屑病", "psoriasis"),
    # --- medicines (WHO essential medicines / common INN) ---
    "paracetamol": ("对乙酰氨基酚", "paracetamolum"),
    "acetaminophen": ("对乙酰氨基酚", "paracetamolum"),
    "ibuprofen": ("布洛芬", "ibuprofenum"),
    "aspirin": ("阿司匹林", "acidum acetylsalicylicum"),
    "amoxicillin": ("阿莫西林", "amoxicillinum"),
    "azithromycin": ("阿奇霉素", "azithromycinum"),
    "ceftriaxone": ("头孢曲松", "ceftriaxonum"),
    "metformin": ("二甲双胍", "metforminum"),
    "insulin": ("胰岛素", "insulinum"),
    "atorvastatin": ("阿托伐他汀", "atorvastatinum"),
    "amlodipine": ("氨氯地平", "amlodipinum"),
    "lisinopril": ("赖诺普利", "lisinoprilum"),
    "losartan": ("氯沙坦", "losartanum"),
    "omeprazole": ("奥美拉唑", "omeprazolum"),
    "salbutamol": ("沙丁胺醇", "salbutamolum"),
    "albuterol": ("沙丁胺醇", "salbutamolum"),
    "prednisone": ("泼尼松", "prednisonum"),
    "morphine": ("吗啡", "morphinum"),
    "codeine": ("可待因", "codeinum"),
    "warfarin": ("华法林", "warfarinum"),
    "heparin": ("肝素", "heparinum"),
    "furosemide": ("呋塞米", "furosemidum"),
    "metoprolol": ("美托洛尔", "metoprololum"),
    "diazepam": ("地西泮", "diazepamum"),
    "dexamethasone": ("地塞米松", "dexamethasonum"),
    "antibiotic": ("抗生素", "antibioticum"),
    "painkiller": ("止痛药", "analgeticum"),
    "antipyretic": ("退烧药", "antipyreticum"),
    "antihistamine": ("抗组胺药", "antihistaminicum"),
    # --- labs / imaging / tests ---
    "blood test": ("血液检查", "examen sanguinis"),
    "urine test": ("尿液检查", "examen urinae"),
    "x-ray": ("X光", "radiographia"),
    "ct scan": ("CT扫描", "tomographia computata"),
    "mri": ("磁共振成像", "imaging per resonantiam magneticam"),
    "ultrasound": ("超声", "ultrasonographia"),
    "electrocardiogram": ("心电图", "electrocardiographia"),
    "blood sugar": ("血糖", "glycaemia"),
    "cholesterol": ("胆固醇", "cholesterolum"),
    "hemoglobin": ("血红蛋白", "haemoglobinum"),
    "white blood cell count": ("白细胞计数", "numerus leucocytorum"),
    "platelet count": ("血小板计数", "numerus thrombocytorum"),
    "biopsy": ("活检", "biopsia"),
    "endoscopy": ("内镜检查", "endoscopia"),
    "colonoscopy": ("结肠镜检查", "colonoscopia"),
    "gastroscopy": ("胃镜检查", "gastroscopia"),
    "blood culture": ("血培养", "cultura sanguinis"),
    # --- procedures / treatments ---
    "surgery": ("手术", "chirurgia"),
    "operation": ("手术", "operatio"),
    "injection": ("注射", "injectio"),
    "infusion": ("输液", "infusio"),
    "iv drip": ("静脉滴注", "infusio intravenosa"),
    "vaccination": ("疫苗接种", "vaccinatio"),
    "dialysis": ("透析", "dialysis"),
    "blood transfusion": ("输血", "transfusio sanguinis"),
    "intubation": ("插管", "intubatio"),
    "cpr": ("心肺复苏", "resuscitatio cardiopulmonalis"),
    "chemotherapy": ("化疗", "chemotherapia"),
    "radiotherapy": ("放疗", "radiotherapia"),
    "physical therapy": ("物理治疗", "therapia physica"),
    "anesthesia": ("麻醉", "anaesthesia"),
    "sutures": ("缝合", "sutura"),
    "cast": ("石膏固定", "gypsum"),
    # --- departments ---
    "internal medicine": ("内科", "medicina interna"),
    "general surgery": ("普外科", "chirurgia generalis"),
    "cardiology department": ("心内科", "departmentum cardiologiae"),
    "neurology department": ("神经内科", "departmentum neurologiae"),
    "oncology department": ("肿瘤科", "departmentum oncologiae"),
    "orthopedics department": ("骨科", "departmentum orthopaediae"),
    "dermatology department": ("皮肤科", "departmentum dermatologiae"),
    "ophthalmology department": ("眼科", "departmentum ophthalmologiae"),
    "otolaryngology": ("耳鼻喉科", "oto-rhino-laryngologia"),
    "urology department": ("泌尿外科", "departmentum urologiae"),
    "gastroenterology department": ("消化内科", "departmentum gastroenterologiae"),
    "endocrinology department": ("内分泌科", "departmentum endocrinologiae"),
    "nephrology department": ("肾内科", "departmentum nephrologiae"),
    "psychiatry department": ("精神科", "departmentum psychiatriae"),
    "anesthesiology": ("麻醉科", "anaesthesiologia"),
    "radiology department": ("放射科", "departmentum radiologiae"),
    "rehabilitation department": ("康复科", "departmentum rehabilitationis"),
    "obstetrics": ("产科", "obstetricia"),
    # --- hospital admin / visit flow ---
    "registration": ("挂号", "inscriptio"),
    "outpatient": ("门诊", "ambulatorium"),
    "inpatient": ("住院", "degens in nosocomio"),
    "emergency room": ("急诊室", "cubiculum urgentiae"),
    "intensive care unit": ("重症监护室", "unitas curae intensivae"),
    "ward": ("病房", "cubiculum aegrotorum"),
    "prescription": ("处方", "praescriptio"),
    "referral": ("转诊", "remissio ad specialistam"),
    "appointment": ("预约", "constitutum"),
    "medical record": ("病历", "tabula medica"),
    "health insurance": ("医疗保险", "assecuratio sanitatis"),
    "discharge": ("出院", "dimissio"),
    "admission": ("入院", "admissio"),
    "informed consent": ("知情同意", "consensus informatus"),
    "medical certificate": ("诊断证明", "certificatum medicum"),
    "copayment": ("自付费用", "solutio propria"),
}

