"""TransMed core data module.
Hospitals, triage rules, medications, insurance info, and medical terms.
"""
from __future__ import annotations

# ---- Hospital list -------------------------------------------------------
HOSPITALS = [
    {"id": "pumch", "name": "Peking Union Medical College Hospital", "name_zh": "北京协和医院",
     "address": "1 Shuaifuyuan, Dongcheng District, Beijing", "address_zh": "北京市东城区王府井帅府园1号",
     "phone": "+86 10 6915 6177", "hours": "Mon-Fri 08:00-17:00, Emergency 24/7",
     "rating": 4.9, "lat": 39.9094, "lng": 116.4165, "distance_km": 1.2, "wait_minutes": 25,
     "specialties": ["Internal Medicine", "Cardiology", "Neurology", "Pediatrics", "Oncology"],
     "insurance": ["BUPA", "Cigna", "MSH", "Ping An"],
     "departments": [("Internal Medicine", "内科", 20), ("Cardiology", "心内科", 15),
                     ("Neurology", "神经内科", 18), ("Pediatrics", "儿科", 12),
                     ("Emergency", "急诊", 5)],
     "languages": ["English", "Chinese", "Japanese"]},
    {"id": "ufh", "name": "United Family Hospital Beijing", "name_zh": "北京和睦家医院",
     "address": "2 Jiangtai Road, Chaoyang District, Beijing", "address_zh": "北京市朝阳区将台路2号",
     "phone": "+86 10 5927 7000", "hours": "Mon-Sun 08:00-20:00, Emergency 24/7",
     "rating": 4.95, "lat": 39.9754, "lng": 116.4677, "distance_km": 7.5, "wait_minutes": 5,
     "specialties": ["Family Medicine", "Pediatrics", "Obstetrics & Gynecology", "Dental", "Emergency"],
     "insurance": ["BUPA", "Cigna", "Aetna", "MSH", "Allianz", "Ping An", "International SOS"],
     "departments": [("Family Medicine", "全科", 3), ("Pediatrics", "儿科", 5),
                     ("Obstetrics & Gynecology", "妇产科", 8), ("Dental", "口腔科", 10),
                     ("Emergency", "急诊", 2), ("Cardiology", "心内科", 12),
                     ("Orthopedics", "骨科", 10), ("Dermatology", "皮肤科", 12)],
     "languages": ["English", "Chinese", "Japanese", "Korean", "French", "German"]},
    {"id": "bjh", "name": "Beijing Hospital (International Medical Center)", "name_zh": "北京医院国际医疗中心",
     "address": "1 Dongdan North Street, Dongcheng District", "address_zh": "北京市东城区东单北大街1号",
     "phone": "+86 10 6513 2266", "hours": "Mon-Fri 08:00-17:00",
     "rating": 4.8, "lat": 39.9112, "lng": 116.4193, "distance_km": 2.1, "wait_minutes": 20,
     "specialties": ["Geriatrics", "Cardiology", "Endocrinology", "Neurology"],
     "insurance": ["BUPA", "Aetna", "Allianz", "Ping An"],
     "departments": [("Geriatrics", "老年医学", 25), ("Cardiology", "心内科", 20),
                     ("Endocrinology", "内分泌科", 18), ("Neurology", "神经内科", 22),
                     ("General Medicine", "全科", 15)],
     "languages": ["English", "Chinese"]},
    {"id": "amcare", "name": "Amcare Women & Children's Hospital", "name_zh": "美中宜和妇儿医院",
     "address": "9 Fangyuan West Road, Chaoyang District", "address_zh": "北京市朝阳区芳园西路9号",
     "phone": "+86 10 6434 0434", "hours": "Mon-Sun 08:30-20:00",
     "rating": 4.85, "lat": 39.9757, "lng": 116.4798, "distance_km": 8.3, "wait_minutes": 8,
     "specialties": ["Obstetrics", "Gynecology", "Pediatrics", "Pediatric Surgery"],
     "insurance": ["Cigna", "BUPA", "MSH", "Aetna", "Ping An"],
     "departments": [("Obstetrics", "产科", 10), ("Gynecology", "妇科", 10),
                     ("Pediatrics", "儿科", 8), ("Pediatric Surgery", "小儿外科", 15)],
     "languages": ["English", "Chinese", "Japanese"]},
    {"id": "hku", "name": "The University of Hong Kong-Shenzhen Hospital (IMC)", "name_zh": "香港大学深圳医院国际医疗中心",
     "address": "1 Haiyuan 1st Road, Futian District, Shenzhen", "address_zh": "深圳市福田区海园一路1号",
     "phone": "+86 755 8691 3333", "hours": "Mon-Sun 08:30-17:30, Emergency 24/7",
     "rating": 4.75, "lat": 22.5357, "lng": 114.0608, "distance_km": 25.0, "wait_minutes": 15,
     "specialties": ["Cardiology", "Oncology", "Orthopedics", "General Medicine", "Pediatrics"],
     "insurance": ["Cigna", "BUPA", "MSH", "Aetna", "Allianz"],
     "departments": [("Cardiology", "心内科", 18), ("Oncology", "肿瘤科", 25),
                     ("Orthopedics", "骨科", 15), ("General Medicine", "全科", 10),
                     ("Pediatrics", "儿科", 12), ("Emergency", "急诊", 5)],
     "languages": ["English", "Chinese", "Cantonese"]},
    {"id": "raffles", "name": "Raffles Medical Beijing Clinic", "name_zh": "北京莱佛士医疗",
     "address": "3/F, Beijing SK Tower, 6A Jiuxianqiao Road, Chaoyang District", "address_zh": "北京市朝阳区酒仙桥路甲6号SK大厦3层",
     "phone": "+86 10 6505 2288", "hours": "Mon-Fri 08:30-19:00, Sat 09:00-13:00",
     "rating": 4.7, "lat": 39.9775, "lng": 116.4914, "distance_km": 6.8, "wait_minutes": 10,
     "specialties": ["Family Medicine", "Pediatrics", "Dental", "Dermatology", "Travel Medicine"],
     "insurance": ["Cigna", "BUPA", "MSH", "Aetna", "Allianz", "AXA PPP", "International SOS"],
     "departments": [("Family Medicine", "全科", 5), ("Pediatrics", "儿科", 8),
                     ("Dental", "口腔科", 10), ("Dermatology", "皮肤科", 12),
                     ("Travel Medicine", "旅行医学", 5)],
     "languages": ["English", "Chinese", "Japanese", "Malay"]},
]


# ---- Indoor navigation map (representative hospital layout) --------------
# 坐标系：viewBox 0 0 1000 600，每个节点放置真实房间中心
INDOOR_MAP = {
    "nodes": [
        # 1 楼 - 主走廊（横向）
        {"id": "entrance", "label": "Main Entrance / 正门", "floor": 1, "x": 80, "y": 300},
        {"id": "info", "label": "Information / 咨询台", "floor": 1, "x": 220, "y": 300},
        {"id": "registration", "label": "Registration / 挂号处", "floor": 1, "x": 360, "y": 300},
        {"id": "hall", "label": "Central Hall / 中央大厅", "floor": 1, "x": 500, "y": 300},
        {"id": "elevator", "label": "Elevators / 电梯", "floor": 1, "x": 640, "y": 300},
        {"id": "cafe", "label": "Café & Shop / 咖啡厅", "floor": 1, "x": 780, "y": 300},
        {"id": "pharmacy", "label": "Pharmacy / 药房", "floor": 1, "x": 920, "y": 300},

        # 1 楼 - 北区（科室）
        {"id": "gp", "label": "Family Medicine / 全科", "floor": 1, "x": 220, "y": 130},
        {"id": "pediatrics", "label": "Pediatrics / 儿科", "floor": 1, "x": 360, "y": 130},
        {"id": "obgyn", "label": "Obstetrics & Gynecology / 妇产科", "floor": 1, "x": 500, "y": 130},
        {"id": "emergency", "label": "Emergency / 急诊", "floor": 1, "x": 920, "y": 130},

        # 1 楼 - 南区（辅助科室）
        {"id": "restroom", "label": "Restroom / 卫生间", "floor": 1, "x": 80, "y": 470},
        {"id": "lab", "label": "Laboratory / 检验科", "floor": 1, "x": 220, "y": 470},
        {"id": "imaging", "label": "Imaging (X-Ray/CT/MRI) / 影像科", "floor": 1, "x": 360, "y": 470},
        {"id": "dental", "label": "Dental / 口腔科", "floor": 1, "x": 500, "y": 470},
        {"id": "dermatology", "label": "Dermatology / 皮肤科", "floor": 1, "x": 640, "y": 470},
        {"id": "ent", "label": "ENT (Ear, Nose, Throat) / 耳鼻喉科", "floor": 1, "x": 780, "y": 470},

        # 2 楼（经电梯到达）
        {"id": "tcm", "label": "Traditional Chinese Medicine / 中医科", "floor": 2, "x": 220, "y": 570},
        {"id": "mental_health", "label": "Mental Health / 心理科", "floor": 2, "x": 360, "y": 570},
        {"id": "cardiology", "label": "Cardiology / 心内科", "floor": 2, "x": 500, "y": 570},
        {"id": "orthopedics", "label": "Orthopedics / 骨科", "floor": 2, "x": 640, "y": 570},
        {"id": "icu", "label": "ICU / 重症监护", "floor": 2, "x": 920, "y": 570},
    ],
    "paths": [
        # 主走廊（东西向）
        ("entrance", "info", "Walk straight into the lobby"),
        ("info", "registration", "Continue east; counter is on your right"),
        ("registration", "hall", "Central Hall ahead"),
        ("hall", "elevator", "Elevator bank on the right"),
        ("elevator", "cafe", "Cafe and convenience store"),
        ("cafe", "pharmacy", "Pharmacy at the east end"),

        # 北区连接（从主走廊向北）
        ("registration", "gp", "North wing — turn left to Family Medicine"),
        ("hall", "pediatrics", "North wing, second wing — Pediatrics"),
        ("hall", "obgyn", "North wing, third wing — Obstetrics and Gynecology"),
        ("hall", "emergency", "Walk east along the corridor to the red Emergency zone"),

        # 南区连接（从主走廊向南）
        ("entrance", "restroom", "Restroom near the west entrance"),
        ("hall", "lab", "South corridor, first door on left — Laboratory"),
        ("lab", "imaging", "Imaging suite next to the lab"),
        ("imaging", "dental", "Continue east along south corridor"),
        ("dental", "dermatology", "Dermatology next to Dental"),
        ("dermatology", "ent", "ENT at the end of south corridor"),
        ("lab", "pharmacy", "Pharmacy is two doors east from the lab"),

        # 2 楼（电梯向上）
        ("elevator", "tcm", "Take elevator to Floor 2 — Traditional Chinese Medicine"),
        ("elevator", "mental_health", "Take elevator to Floor 2, left wing — Mental Health"),
        ("elevator", "cardiology", "Take elevator to Floor 2, center wing — Cardiology"),
        ("elevator", "orthopedics", "Take elevator to Floor 2, right wing — Orthopedics"),
        ("elevator", "icu", "Take elevator to Floor 2, restricted east wing — ICU"),

        # 2 楼内部连通
        ("tcm", "mental_health", "Walk east along the Floor 2 corridor"),
        ("mental_health", "cardiology", "Continue east on Floor 2"),
        ("cardiology", "orthopedics", "Next department east on Floor 2"),
        ("orthopedics", "icu", "East end of Floor 2 — restricted access"),
    ],
}


# ---- Triage rules: symptom → department + advice + urgency flag ----------
TRIAGE_RULES = {
    "headache": ("Neurology", "神经内科",
                 "If severe, sudden, or with vision changes/fever — seek urgent care. Otherwise, neurology consultation recommended.",
                 "如剧烈、突发，或伴视力变化/发热，请紧急就医；否则建议神经内科就诊。", True),
    "fever": ("Internal Medicine", "内科",
              "Monitor temperature. If >39°C, with shortness of breath or confusion — seek urgent care.",
              "监测体温。如高于39℃、伴呼吸困难或意识模糊，请紧急就医。", False),
    "cough": ("Pulmonary / Respiratory", "呼吸内科",
              "If accompanied by fever, shortness of breath, or chest pain — seek urgent evaluation.",
              "如伴发热、气短或胸痛，建议紧急评估。", False),
    "shortness of breath": ("Pulmonary / Cardiology", "呼吸内科 / 心内科",
                            "Seek emergency care immediately. Do not drive yourself.",
                            "立即前往急诊。请勿自行驾车。", True),
    "chest pain": ("Cardiology / Emergency", "心内科 / 急诊",
                   "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Call 120.",
                   "🚨 立即前往急诊或拨打120。", True),
    "heart attack": ("Cardiology / Emergency", "心内科 / 急诊",
                     "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Call 120. Chew aspirin if available and not allergic.",
                     "🚨 立即前往急诊或拨打120。如无过敏，可嚼服阿司匹林。", True),
    "stroke": ("Neurology / Emergency", "神经内科 / 急诊",
               "🚨 SEEK EMERGENCY CARE IMMEDIATELY. Time is brain — every minute matters.",
               "🚨 立即前往急诊或拨打120。时间就是大脑——每一分钟都至关重要。", True),
    "stomach pain": ("Gastroenterology", "消化内科",
                     "If severe, persistent, or with bloody stools/vomiting — emergency.",
                     "如剧烈、持续，或伴便血/呕血，请紧急就医。", False),
    "diarrhea": ("Gastroenterology", "消化内科",
                 "Stay hydrated. If blood in stools, high fever, or dehydration — see a doctor.",
                 "保持补水。如出现便血、高热或脱水，请就医。", False),
    "nausea": ("Gastroenterology / Internal Medicine", "消化内科 / 内科",
               "Rest and hydrate. If persistent or with severe abdominal pain, seek care.",
               "休息并补水。若持续或伴剧烈腹痛，请就医。", False),
    "vomiting": ("Gastroenterology / Emergency", "消化内科 / 急诊",
                 "If with blood, severe headache, or confusion — go to emergency.",
                 "如伴呕血、剧烈头痛或意识模糊，请前往急诊。", False),
    "back pain": ("Orthopedics / Physiotherapy", "骨科 / 康复理疗科",
                  "Rest, avoid heavy lifting. If with leg numbness, bladder issues, or after trauma — urgent.",
                  "休息，避免负重。如伴下肢麻木、排尿困难或外伤后，请紧急就医。", False),
    "neck pain": ("Orthopedics / Neurology", "骨科 / 神经内科",
                  "If with fever, stiff neck, and sensitivity to light — emergency (possible meningitis).",
                  "如伴发热、颈强直、畏光——需紧急评估（可能脑膜炎）。", True),
    "skin rash": ("Dermatology", "皮肤科",
                  "Avoid scratching. If with fever, blistering, or mucosal involvement — urgent care.",
                  "避免搔抓。如伴发热、水疱或黏膜受累——请紧急就医。", False),
    "itching": ("Dermatology / Allergy", "皮肤科 / 变态反应科",
                "Try cold compresses. If widespread swelling or difficulty breathing — emergency.",
                "冷敷缓解。如全身肿胀或呼吸困难，需急诊。", False),
    "allergy": ("Allergy & Immunology / Emergency", "变态反应科 / 急诊",
                "Use antihistamine if available. If anaphylaxis (swelling, difficulty breathing) — use EpiPen and go to ER.",
                "可用抗组胺药。如过敏反应（肿胀、呼吸困难）——使用肾上腺素笔并前往急诊。", True),
    "tooth pain": ("Dental", "口腔科",
                   "Avoid hot/cold stimuli. Seek dental appointment within 24-48 hours.",
                   "避免冷热刺激。24-48小时内看牙医。", False),
    "toothache": ("Dental", "口腔科",
                  "Avoid hot/cold stimuli. Seek dental appointment within 24-48 hours.",
                  "避免冷热刺激。24-48小时内看牙医。", False),
    "joint pain": ("Rheumatology / Orthopedics", "风湿免疫科 / 骨科",
                   "Rest and apply ice. If swollen, red, and hot — seek evaluation (possible infection/gout).",
                   "休息并冰敷。如关节红肿热——请就医（可能感染/痛风）。", False),
    "ear pain": ("ENT", "耳鼻喉科",
                 "If severe, with hearing loss or discharge — ENT evaluation within 24 hours.",
                 "如剧烈、伴听力下降或流脓——24小时内看耳鼻喉科。", False),
    "sore throat": ("ENT / Internal Medicine", "耳鼻喉科 / 内科",
                    "Warm fluids and rest. If difficulty breathing, drooling, or high fever — urgent.",
                    "温饮休息。如呼吸困难、流口水或高热——请急诊。", False),
    "runny nose": ("ENT / Internal Medicine", "耳鼻喉科 / 内科",
                   "Likely viral URI. Rest, fluids. If >10 days or with high fever, consult a physician.",
                   "多为病毒性上感。休息补水。如超过10天或高热，请就医。", False),
    "eye pain": ("Ophthalmology", "眼科",
                 "If with vision changes, flashes of light, or trauma — urgent ophthalmology care.",
                 "如伴视力变化、闪光感或外伤——请紧急眼科就诊。", False),
    "blurred vision": ("Ophthalmology / Neurology", "眼科 / 神经内科",
                       "If sudden onset — seek urgent medical evaluation (possible stroke or retinal issue).",
                       "如突然发生——请紧急就医（可能中风或视网膜问题）。", True),
    "dizziness": ("Neurology / ENT / Cardiology", "神经内科 / 耳鼻喉科 / 心内科",
                  "Sit or lie down. If with chest pain, shortness of breath, or focal weakness — emergency.",
                  "坐下或躺下。如伴胸痛、气短或单侧无力——急诊。", False),
    "fainting": ("Cardiology / Neurology / Emergency", "心内科 / 神经内科 / 急诊",
                 "🚨 Seek emergency evaluation — possible cardiac or neurological cause.",
                 "🚨 紧急就医评估——可能心脏或神经系统原因。", True),
    "palpitations": ("Cardiology", "心内科",
                     "If with chest pain, shortness of breath, or dizziness — seek urgent evaluation.",
                     "如伴胸痛、气短或头晕——请紧急评估。", False),
    "high blood pressure": ("Cardiology", "心内科",
                            "Monitor at home. If >180/120 with symptoms — seek emergency care (hypertensive crisis).",
                            "居家监测。如高于180/120且有症状——请急诊（高血压危象）。", True),
    "fatigue": ("Internal Medicine / Endocrinology", "内科 / 内分泌科",
                "Could be anemia, thyroid, infection, or other. Blood work recommended.",
                "可能贫血、甲状腺、感染或其他。建议验血。", False),
    "weight loss": ("Internal Medicine / Endocrinology / Oncology", "内科 / 内分泌科 / 肿瘤科",
                    "Unintentional weight loss needs evaluation. Consult internal medicine.",
                    "非刻意体重减轻需评估。请咨询内科。", False),
    "insomnia": ("Mental Health / Neurology", "心理科 / 神经内科",
                 "Sleep hygiene first. If persistent with mood changes — mental health consultation.",
                 "先改善睡眠卫生。如持续并伴情绪变化——请心理科咨询。", False),
    "anxiety": ("Mental Health / Psychiatry", "心理科 / 精神科",
                "Deep breathing exercises. If panic attacks, self-harm thoughts, or persistent — professional help.",
                "深呼吸练习。如恐慌发作、自伤念头或持续——请专业帮助。", False),
    "depression": ("Mental Health / Psychiatry", "心理科 / 精神科",
                   "Please reach out to a mental health professional. If self-harm thoughts, call emergency or a crisis hotline.",
                   "请联系心理健康专业人士。如有自伤念头，请拨打急诊或心理援助热线。", True),
    "cold": ("Internal Medicine / Family Medicine", "内科 / 全科",
             "Rest and fluids. If symptoms worsen or persist beyond 10 days, consult a physician.",
             "休息补水。如症状恶化或超过10天，请咨询医生。", False),
    "flu": ("Internal Medicine / Family Medicine", "内科 / 全科",
            "Rest, fluids, fever control. If difficulty breathing or chest pain — emergency care.",
            "休息、补水、退热。如呼吸困难或胸痛——急诊。", False),
    "urinary pain": ("Urology", "泌尿外科",
                     "Likely UTI. Drink water. If with fever/back pain — seek medical evaluation.",
                     "可能尿路感染。多喝水。如伴发热/腰痛——就医。", False),
    "constipation": ("Gastroenterology / Family Medicine", "消化内科 / 全科",
                     "Increase fiber and fluids. If persistent with severe pain, consult a physician.",
                     "增加纤维和水分。如持续伴剧烈疼痛，请咨询医生。", False),
    "bloody stool": ("Gastroenterology / Emergency", "消化内科 / 急诊",
                     "🚨 Seek medical evaluation immediately.",
                     "🚨 立即就医评估。", True),
    "blood in urine": ("Urology / Nephrology", "泌尿外科 / 肾内科",
                       "Seek medical evaluation — various causes from infection to stones or more serious conditions.",
                       "就医评估——原因从感染到结石或更严重情况不等。", False),
    "pregnancy": ("Obstetrics & Gynecology", "妇产科",
                  "Prenatal care should begin within the first trimester. Schedule an OB visit.",
                  "产前检查应在孕早期开始。预约产科就诊。", False),
    "vaginal bleeding": ("Obstetrics & Gynecology / Emergency", "妇产科 / 急诊",
                         "If pregnant — emergency evaluation immediately. If not pregnant — gynecology visit.",
                         "如怀孕——立即急诊评估。如未怀孕——妇科就诊。", True),
    "child fever": ("Pediatrics", "儿科",
                    "Monitor closely. Infants under 3 months with fever need urgent evaluation.",
                    "密切监测。3个月以下婴儿发热需紧急评估。", True),
    "child vomiting": ("Pediatrics", "儿科",
                       "Keep hydrated with small frequent sips. If lethargic, bloody vomit, or unable to drink — emergency.",
                       "少量多次补水。如嗜睡、呕血或无法饮水——急诊。", False),
    "injury": ("Orthopedics / Emergency", "骨科 / 急诊",
               "Immobilize the area. Apply ice. If obvious deformity, inability to move, or severe pain — emergency.",
               "固定受伤部位。冰敷。如明显畸形、无法活动或剧痛——急诊。", False),
    "sprain": ("Orthopedics / Physiotherapy", "骨科 / 康复理疗科",
               "RICE: Rest, Ice, Compression, Elevation. If cannot bear weight — X-ray needed.",
               "RICE原则：休息、冰敷、加压、抬高。如无法承重——需X光。", False),
    "fracture": ("Orthopedics / Emergency", "骨科 / 急诊",
                 "🚨 Immobilize and go to emergency immediately.",
                 "🚨 固定伤处并立即前往急诊。", True),
    "burn": ("Emergency / Plastic Surgery", "急诊 / 整形外科",
             "Cool running water for 10-20 minutes. Do NOT apply ice, butter, or toothpaste. Cover with sterile dressing.",
             "流动冷水冲洗10-20分钟。切勿涂冰、黄油或牙膏。无菌敷料覆盖。", True),
    "animal bite": ("Emergency / Infectious Diseases", "急诊 / 感染科",
                    "🚨 Wash wound thoroughly with soap and water for 15 minutes. Seek emergency care for rabies PEP and antibiotics.",
                    "🚨 用肥皂水彻底冲洗伤口15分钟。急诊处理狂犬病暴露和抗生素。", True),
    "suicide": ("Mental Health / Emergency", "心理科 / 急诊",
                "🚨 CALL EMERGENCY SERVICES (120) OR A CRISIS HOTLINE IMMEDIATELY. You are not alone.",
                "🚨 立即拨打120或心理援助热线。你并不孤单。", True),
    "bleeding": ("Emergency", "急诊",
                 "Apply direct pressure with clean cloth. If bleeding is heavy or doesn't stop — emergency immediately.",
                 "用干净布料直接加压。如出血量大或不止——立即急诊。", True),
    "trauma": ("Emergency / Surgery", "急诊 / 外科",
               "🚨 Do not move the person. Call 120 immediately.",
               "🚨 不要移动伤者。立即拨打120。", True),
    "poisoning": ("Emergency", "急诊",
                  "🚨 Call 120 immediately. If possible, bring the container/substance with you.",
                  "🚨 立即拨打120。如可能，携带致毒物包装。", True),
    "choking": ("Emergency", "急诊",
                "🚨 If unable to speak/breathe — perform Heimlich maneuver and call 120.",
                "🚨 如无法说话/呼吸——实施海姆立克急救法并拨打120。", True),
    "diabetes": ("Endocrinology", "内分泌科",
                 "Regular blood sugar monitoring. If very high/low with confusion — emergency.",
                 "定期血糖监测。如血糖过高/过低伴意识模糊——急诊。", False),
    "asthma": ("Pulmonary / Emergency", "呼吸内科 / 急诊",
               "Use rescue inhaler. If severe attack, lips/fingernails blue, or unable to speak — emergency.",
               "使用急救吸入剂。如严重发作、嘴唇/指甲发绀或无法说话——急诊。", True),
}


# ---- Urgent symptoms list (subset of triage keys flagged urgent) ---------
URGENT_SYMPTOMS = {k for k, v in TRIAGE_RULES.items() if v[4]}


# ---- Medications ----------------------------------------------------------
MEDICATIONS = {
    # Analgesics / Fever reducers
    "paracetamol": {
        "name": "Paracetamol (Acetaminophen)", "name_zh": "对乙酰氨基酚（扑热息痛）",
        "category": "Pain relief / Fever reducer", "category_zh": "止痛 / 退热",
        "dosage": "500mg every 6 hours as needed. Maximum 4000mg/day.",
        "dosage_zh": "按需每6小时500mg。每日最大4000mg。",
        "warnings": ["Do NOT exceed daily dose — risk of severe liver damage",
                     "Avoid with liver disease or regular alcohol use",
                     "Check other medications — many contain paracetamol"],
        "warnings_zh": ["严禁超量——有严重肝损伤风险", "肝病或经常饮酒者慎用",
                        "检查其他药物——许多含对乙酰氨基酚"],
        "side_effects": ["Nausea (rare)", "Liver damage (overdose)"],
        "rx_required": False, "price_cny": 20,
    },
    "ibuprofen": {
        "name": "Ibuprofen", "name_zh": "布洛芬",
        "category": "NSAID — Anti-inflammatory / Pain / Fever",
        "category_zh": "非甾体抗炎药——抗炎/止痛/退热",
        "dosage": "200-400mg every 6-8 hours with food. Maximum 1200mg/day (OTC).",
        "dosage_zh": "随餐服用200-400mg，每6-8小时一次。每日最大1200mg。",
        "warnings": ["Take with food — can cause stomach irritation/ulcers",
                     "Avoid if: active ulcer, kidney disease, asthma worsened by NSAIDs, last trimester of pregnancy",
                     "May increase risk of heart attack/stroke with long-term use"],
        "warnings_zh": ["随餐服用——可能刺激胃黏膜/引起溃疡",
                        "禁用：活动性溃疡、肾病、NSAID诱发哮喘、妊娠末三个月",
                        "长期使用可能增加心脏病发作/中风风险"],
        "side_effects": ["Stomach upset", "Nausea", "Dizziness", "Headache"],
        "rx_required": False, "price_cny": 25,
    },
    "aspirin": {
        "name": "Aspirin (Acetylsalicylic Acid)", "name_zh": "阿司匹林",
        "category": "Anti-platelet / Pain / Fever", "category_zh": "抗血小板/止痛/退热",
        "dosage": "Heart protection: 75-100mg daily. Pain/fever: 325-650mg every 4-6 hours.",
        "dosage_zh": "心脏保护：每日75-100mg。止痛/退热：325-650mg每4-6小时。",
        "warnings": ["Do NOT give to children under 16 (Reye's syndrome risk)",
                     "Increases bleeding risk — tell doctors/dentists before procedures"],
        "warnings_zh": ["16岁以下儿童禁用（瑞氏综合征）",
                        "增加出血风险——手术/牙科前告知医生"],
        "side_effects": ["Stomach irritation", "Increased bleeding", "Nausea"],
        "rx_required": False, "price_cny": 15,
    },
    # Antihistamines
    "loratadine": {
        "name": "Loratadine", "name_zh": "氯雷他定",
        "category": "Non-drowsy Antihistamine", "category_zh": "无镇静抗组胺药",
        "dosage": "10mg once daily.", "dosage_zh": "每日一次10mg。",
        "warnings": ["Generally well-tolerated. Rare drowsiness in some individuals."],
        "warnings_zh": ["一般耐受性良好。少数人可能嗜睡。"],
        "side_effects": ["Headache (rare)", "Dry mouth (rare)"],
        "rx_required": False, "price_cny": 30,
    },
    "cetirizine": {
        "name": "Cetirizine", "name_zh": "西替利嗪",
        "category": "Antihistamine", "category_zh": "抗组胺药",
        "dosage": "10mg once daily. May cause drowsiness.",
        "dosage_zh": "每日一次10mg。可能嗜睡——初期避免驾驶。",
        "warnings": ["Avoid alcohol and driving while adjusting to the medication"],
        "warnings_zh": ["避免饮酒和驾驶"],
        "side_effects": ["Drowsiness", "Dry mouth", "Headache"],
        "rx_required": False, "price_cny": 28,
    },
    # Stomach / GI
    "omeprazole": {
        "name": "Omeprazole", "name_zh": "奥美拉唑",
        "category": "Proton Pump Inhibitor (PPI) — Acid reducer",
        "category_zh": "质子泵抑制剂——抑酸药",
        "dosage": "20mg once daily before breakfast.", "dosage_zh": "早餐前每日一次20mg。",
        "warnings": ["Take 30-60 minutes before eating (before breakfast best)",
                     "Long-term use (>1 year) may increase bone fracture and B12 deficiency risk"],
        "warnings_zh": ["餐前30-60分钟服用（早餐前最佳）",
                        "长期使用（>1年）可能增加骨折和B12缺乏风险"],
        "side_effects": ["Headache", "Diarrhea", "Nausea"],
        "rx_required": False, "price_cny": 35,
    },
    # Cardiology
    "lisinopril": {
        "name": "Lisinopril", "name_zh": "赖诺普利",
        "category": "ACE Inhibitor — High blood pressure / Heart failure",
        "category_zh": "ACE抑制剂——降压/心衰",
        "dosage": "10-40mg once daily, as prescribed.", "dosage_zh": "遵医嘱每日一次10-40mg。",
        "warnings": ["Do NOT take if pregnant — can cause fetal harm/death",
                     "Dry cough is common (10-20%). If bothersome, consult doctor for alternative"],
        "warnings_zh": ["孕期禁用——可致胎儿损害/死亡", "干咳常见（10-20%）——如困扰请咨询医生换药"],
        "side_effects": ["Dry cough", "Dizziness", "Low blood pressure", "Headache"],
        "rx_required": True, "price_cny": 45,
    },
    "atorvastatin": {
        "name": "Atorvastatin", "name_zh": "阿托伐他汀",
        "category": "Statin — Cholesterol-lowering", "category_zh": "他汀类——降胆固醇",
        "dosage": "10-80mg once daily, usually in the evening.",
        "dosage_zh": "每日一次10-80mg，通常晚间服用。",
        "warnings": ["Report unexplained muscle pain/weakness to doctor immediately",
                     "Liver function monitoring required periodically",
                     "Avoid grapefruit/grapefruit juice — increases drug levels"],
        "warnings_zh": ["如有不明原因肌肉疼痛/无力请立即告知医生",
                        "需定期监测肝功能", "避免西柚/西柚汁——显著升高药物浓度"],
        "side_effects": ["Muscle pain", "Headache", "Nausea", "Diarrhea"],
        "rx_required": True, "price_cny": 55,
    },
    # Diabetes
    "metformin": {
        "name": "Metformin", "name_zh": "二甲双胍",
        "category": "Biguanide — Type 2 Diabetes", "category_zh": "双胍类——2型糖尿病",
        "dosage": "500-850mg 2-3 times daily with meals, as prescribed.",
        "dosage_zh": "遵医嘱随餐服用500-850mg，每日2-3次。",
        "warnings": ["Take with meals to reduce stomach upset",
                     "Stop before contrast imaging exams — tell doctors",
                     "Risk of lactic acidosis (rare, but serious) — seek help if severe muscle pain/fatigue"],
        "warnings_zh": ["随餐服用以减少胃部不适",
                        "造影检查前停药——告知医生",
                        "乳酸酸中毒风险（罕见但严重）——如严重肌肉疼痛/疲劳请就医"],
        "side_effects": ["Nausea", "Diarrhea", "Abdominal bloating", "Metallic taste"],
        "rx_required": True, "price_cny": 20,
    },
    # Respiratory
    "albuterol_salbutamol": {
        "name": "Albuterol (Salbutamol)", "name_zh": "沙丁胺醇（舒喘灵）",
        "category": "Bronchodilator — Asthma / COPD rescue inhaler",
        "category_zh": "支气管扩张剂——哮喘/慢阻肺急救吸入剂",
        "dosage": "1-2 puffs every 4-6 hours as needed for acute symptoms. For severe attack — 4-8 puffs every 20 min for 3 doses, then 1-4 puffs every 1-4 hours.",
        "dosage_zh": "急性症状：每4-6小时1-2喷。严重发作：每20分钟4-8喷，3次后改为每1-4小时1-4喷。",
        "warnings": ["This is a RESCUE inhaler — not for daily long-term control",
                     "If needing more than 2 doses/week for relief — consult doctor for controller medication",
                     "Shake well before each use; rinse mouth after use"],
        "warnings_zh": ["这是急救吸入剂——不用于日常长期控制",
                        "如每周需超过2次缓解——请咨询医生使用控制剂",
                        "每次使用前摇匀；使用后漱口"],
        "side_effects": ["Fast heart rate", "Tremor", "Nervousness", "Headache"],
        "rx_required": True, "price_cny": 70,
    },
    # Antibiotics (common prescriptions for travelers)
    "amoxicillin": {
        "name": "Amoxicillin", "name_zh": "阿莫西林",
        "category": "Penicillin Antibiotic", "category_zh": "青霉素类抗生素",
        "dosage": "500mg three times daily — complete the full course even if feeling better.",
        "dosage_zh": "500mg每日3次——即使症状好转也须服满疗程。",
        "warnings": ["⚠️ Penicillin allergy: Do NOT take if allergic (rash, swelling, anaphylaxis)",
                     "Complete the FULL course — stopping early causes antibiotic resistance",
                     "Diarrhea is common. If severe watery/bloody, contact doctor immediately"],
        "warnings_zh": ["⚠️ 青霉素过敏：如过敏（皮疹、肿胀、过敏反应）请勿服用",
                        "服满完整疗程——过早停药导致耐药",
                        "腹泻常见。如严重水样/血便，请立即就医"],
        "side_effects": ["Diarrhea", "Nausea", "Rash", "Yeast infection"],
        "rx_required": True, "price_cny": 35,
    },
    # Anti-diarrheal (OTC travel essential)
    "loperamide": {
        "name": "Loperamide", "name_zh": "洛哌丁胺（易蒙停）",
        "category": "Anti-diarrheal", "category_zh": "止泻药",
        "dosage": "2 tablets after first loose stool, then 1 tablet after each subsequent loose stool. Maximum 8 tablets/day. Do not take for more than 2 days without consulting a doctor.",
        "dosage_zh": "首次稀便后2片，之后每次稀便后1片。每日最大8片。如超过2天未缓解请就医。",
        "warnings": ["Do NOT take if you have fever/blood in stools or if diarrhea is from infection (will trap bacteria)",
                     "Stay hydrated — this only slows diarrhea, does not treat the cause",
                     "May cause constipation if overused"],
        "warnings_zh": ["如有发热/便血或感染性腹泻禁用——会困住细菌",
                        "保持补水——本品仅减缓腹泻，不治疗病因",
                        "过度使用可能便秘"],
        "side_effects": ["Constipation", "Drowsiness", "Dry mouth"],
        "rx_required": False, "price_cny": 15,
    },
    # Sleep / sedating antihistamine (common traveler aid)
    "diphenhydramine": {
        "name": "Diphenhydramine", "name_zh": "苯海拉明",
        "category": "First-generation Antihistamine / Sedating", "category_zh": "第一代抗组胺药/镇静",
        "dosage": "25-50mg at bedtime for sleep. Every 4-6 hours for allergy symptoms (maximum 300mg/day).",
        "dosage_zh": "睡前25-50mg用于睡眠。过敏症状每4-6小时（每日最大300mg）。",
        "warnings": ["Causes drowsiness — do NOT drive or operate machinery",
                     "Avoid alcohol — increases sedation",
                     "Not recommended in elderly (increased confusion/fall risk)"],
        "warnings_zh": ["引起嗜睡——请勿驾驶或操作机械",
                        "避免酒精——增强镇静",
                        "老年不推荐（增加意识混乱和跌倒风险）"],
        "side_effects": ["Drowsiness", "Dry mouth", "Blurred vision", "Constipation"],
        "rx_required": False, "price_cny": 18,
    },
    # Vitamin D (very common deficiency in northern China)
    "vitamin_d": {
        "name": "Vitamin D3 (Cholecalciferol)", "name_zh": "维生素D3（胆钙化醇）",
        "category": "Vitamin supplement", "category_zh": "维生素补充剂",
        "dosage": "1000-2000 IU (25-50mcg) once daily.", "dosage_zh": "每日一次1000-2000国际单位（25-50微克）。",
        "warnings": ["Important for bone health and immune function",
                     "Very common deficiency in winter / indoor lifestyle — test blood level if possible"],
        "warnings_zh": ["对骨骼健康和免疫功能重要",
                        "冬季/室内生活方式非常常见缺乏——可能的话验血检查"],
        "side_effects": ["Well-tolerated at recommended doses. Excess may cause kidney stones."],
        "rx_required": False, "price_cny": 40,
    },
    # Protonix/Pantoprazole (another PPI, commonly prescribed)
    "pantoprazole": {
        "name": "Pantoprazole", "name_zh": "泮托拉唑",
        "category": "Proton Pump Inhibitor (PPI) — Acid reducer",
        "category_zh": "质子泵抑制剂——抑酸药",
        "dosage": "40mg once daily before breakfast.", "dosage_zh": "早餐前每日一次40mg。",
        "warnings": ["Same warnings as omeprazole — do not stop abruptly after long-term use"],
        "warnings_zh": ["与奥美拉唑相同警告——长期使用后勿突然停药"],
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Abdominal pain"],
        "rx_required": False, "price_cny": 55,
    },
    # Antipsychotic / Mental health example
    "sertraline": {
        "name": "Sertraline", "name_zh": "舍曲林",
        "category": "SSRI Antidepressant — Depression / Anxiety / OCD / PTSD",
        "category_zh": "SSRI类抗抑郁药——抑郁/焦虑/强迫症/创伤后应激障碍",
        "dosage": "50-200mg once daily in the morning or evening.",
        "dosage_zh": "每日一次50-200mg，早晨或晚上。",
        "warnings": ["⚠️ May increase suicidal thoughts in young adults during first few weeks — monitor closely",
                     "Do NOT stop abruptly — must taper gradually under medical supervision",
                     "Takes 4-6 weeks for full effect — do not stop early because of side effects",
                     "Avoid alcohol — increases drowsiness and depression risk"],
        "warnings_zh": ["⚠️ 年轻人开始几周可能增加自杀念头——密切监测",
                        "勿突然停药——必须在医疗监督下逐渐减量",
                        "4-6周达到完全效果——不要因副作用过早停药",
                        "避免酒精——增加嗜睡和抑郁风险"],
        "side_effects": ["Nausea", "Insomnia or drowsiness", "Sexual side effects", "Headache", "Dry mouth"],
        "rx_required": True, "price_cny": 80,
    },
}


# ---- Insurance providers --------------------------------------------------
INSURANCE_PROVIDERS = [
    {"name": "Cigna International", "name_zh": "信诺国际",
     "website": "https://www.cigna.com.hk",
     "claims_hotline": "+1 (800) 992-0692 / +852 2521-6000",
     "notes": "Direct billing with most international hospitals in China. Requires pre-authorization for non-emergency admissions.",
     "notes_zh": "与中国大部分国际医院直付。非急诊入院需预授权。",
     "coverage_types": ["International health", "Medical evacuation", "Dental", "Mental health"],
     "in_network_hospitals": ["ufh", "pumch", "bjh", "hku", "raffles", "amcare"]},
    {"name": "BUPA Global", "name_zh": "保柏国际",
     "website": "https://www.bupa.com.hk",
     "claims_hotline": "+852 2510-9133 / +44 (0)1273 323 232",
     "notes": "One of the most widely accepted international insurers in mainland China hospitals. Direct pay at UFH and most private international clinics.",
     "notes_zh": "中国大陆医院最广泛接受的国际保险公司之一。和睦家及大部分私立国际诊所直付。",
     "coverage_types": ["International health", "Medical evacuation", "Cancer care", "Transplant"],
     "in_network_hospitals": ["ufh", "pumch", "bjh", "hku", "amcare", "raffles"]},
    {"name": "Aetna International", "name_zh": "安泰国际",
     "website": "https://www.aetnainternational.com",
     "claims_hotline": "+1 (860) 273-0231",
     "notes": "Strong international network. Direct billing at major private hospitals in Beijing and Shanghai.",
     "notes_zh": "强大的国际网络。北京、上海主要私立医院直付。",
     "coverage_types": ["International health", "Emergency evacuation"],
     "in_network_hospitals": ["ufh", "bjh", "hku", "raffles"]},
    {"name": "Allianz Care (International SOS)", "name_zh": "安联保险（国际SOS）",
     "website": "https://www.internationalsos.com",
     "claims_hotline": "+86 10 6462-9100 / +65 6338-8788",
     "notes": "Integrated with International SOS — excellent emergency and evacuation support across China.",
     "notes_zh": "与国际SOS整合——在中国境内提供出色的紧急和转运支持。",
     "coverage_types": ["International health", "Emergency evacuation", "Travel insurance"],
     "in_network_hospitals": ["ufh", "pumch", "bjh", "raffles"]},
    {"name": "AXA PPP Healthcare", "name_zh": "安盛天平原生医疗",
     "website": "https://www.axappphealthcare.co.uk",
     "claims_hotline": "+44 (0)20 3823 5937",
     "notes": "UK-based international health insurance. Accepted at UFH, Raffles and select private clinics.",
     "notes_zh": "英国本土国际医疗保险。和睦家、莱佛士和部分私立诊所接受。",
     "coverage_types": ["International health"],
     "in_network_hospitals": ["ufh", "raffles"]},
    {"name": "Ping An Health Insurance (China domestic)", "name_zh": "平安健康保险（中国本土）",
     "website": "https://www.pingan.com.cn",
     "claims_hotline": "+86 400-8833-666",
     "notes": "China local health insurance. Direct pay at public and some private hospitals. Often required for Chinese employees or expats on local contracts.",
     "notes_zh": "中国本土健康保险。公立和部分私立医院直付。中国雇员或本地合同外籍人士通常需要。",
     "coverage_types": ["Inpatient", "Outpatient", "Prescription drugs"],
     "in_network_hospitals": ["pumch", "bjh", "hku", "amcare"]},
    {"name": "Now Health International", "name_zh": "诺和健康国际",
     "website": "https://www.now-health.com",
     "claims_hotline": "+852 3018 3700",
     "notes": "Asia-focused international health insurance. Direct pay at most Beijing private international hospitals.",
     "notes_zh": "以亚洲为重点的国际健康保险。北京大部分私立国际医院直付。",
     "coverage_types": ["International health", "Dental", "Mental health"],
     "in_network_hospitals": ["ufh", "amcare", "raffles"]},
]


# ---- Medical terms dictionary (English -> Chinese + Latin) ----------------
# Used by translator.py as an overlay on top of general-purpose translation.
MEDICAL_TERMS = {
    "headache": ("头痛", "cephalalgia"),
    "migraine": ("偏头痛", "migraine"),
    "fever": ("发热", "febris"),
    "high temperature": ("体温升高", "febris"),
    "cough": ("咳嗽", "tussis"),
    "shortness of breath": ("呼吸困难", "dyspnea"),
    "difficulty breathing": ("呼吸困难", "dyspnea"),
    "chest pain": ("胸痛", "dolor pectoris"),
    "heart attack": ("心脏病发作", "infarctus myocardii"),
    "stroke": ("中风", "apoplexia / ictus cerebrovascularis"),
    "nausea": ("恶心", "nausea"),
    "vomiting": ("呕吐", "vomitus"),
    "stomach pain": ("胃痛", "dolor abdominis"),
    "abdominal pain": ("腹痛", "dolor abdominis"),
    "diarrhea": ("腹泻", "diarrhoea"),
    "constipation": ("便秘", "constipatio"),
    "blood in stool": ("便血", "haematochezia"),
    "bloody stool": ("便血", "haematochezia"),
    "back pain": ("背痛", "dolor dorsi"),
    "neck pain": ("颈痛", "dolor cervicis"),
    "muscle pain": ("肌肉痛", "myalgia"),
    "joint pain": ("关节痛", "arthralgia"),
    "skin rash": ("皮疹", "exanthema"),
    "rash": ("皮疹", "exanthema"),
    "itching": ("瘙痒", "pruritus"),
    "hives": ("荨麻疹", "urticaria"),
    "allergy": ("过敏", "allergia"),
    "allergic reaction": ("过敏反应", "reactio allergica"),
    "anaphylaxis": ("过敏性休克", "anaphylaxis"),
    "dizziness": ("头晕", "vertigo"),
    "lightheadedness": ("头晕目眩", "lipothymia"),
    "fainting": ("晕厥", "syncope"),
    "palpitations": ("心悸", "palpitatio"),
    "high blood pressure": ("高血压", "hypertensio"),
    "hypertension": ("高血压", "hypertensio"),
    "low blood pressure": ("低血压", "hypotensio"),
    "fatigue": ("疲劳", "lassitudo"),
    "tiredness": ("疲倦", "lassitudo"),
    "weakness": ("无力", "debilitas"),
    "weight loss": ("体重减轻", "decrementum ponderis"),
    "weight gain": ("体重增加", "incrementum ponderis"),
    "insomnia": ("失眠", "insomnia"),
    "anxiety": ("焦虑", "anxietas"),
    "depression": ("抑郁", "depressio"),
    "sore throat": ("咽喉痛", "pharyngodynia"),
    "runny nose": ("流鼻涕", "rhinorrhoea"),
    "stuffy nose": ("鼻塞", "congestio nasi"),
    "sneezing": ("打喷嚏", "sternutatio"),
    "ear pain": ("耳痛", "otalgia"),
    "ear infection": ("耳朵感染", "otitis"),
    "tooth pain": ("牙痛", "dolor dentium"),
    "toothache": ("牙痛", "dolor dentium"),
    "eye pain": ("眼痛", "ophthalmalgia"),
    "blurred vision": ("视力模糊", "visio confusa"),
    "double vision": ("复视", "diplopia"),
    "red eye": ("红眼", "oculus ruber"),
    "burning sensation": ("烧灼感", "sensio ardens"),
    "tingling": ("麻刺感", "paresthesia"),
    "numbness": ("麻木", "hypoesthesia"),
    "swelling": ("肿胀", "tumor"),
    "inflammation": ("炎症", "inflammatio"),
    "injury": ("受伤", "injurium"),
    "wound": ("伤口", "vulnus"),
    "bruise": ("淤青", "contusio"),
    "bleeding": ("出血", "haemorrhagia"),
    "sprain": ("扭伤", "distorsio"),
    "fracture": ("骨折", "fractura"),
    "burn": ("烧伤", "ustio"),
    "animal bite": ("动物咬伤", "morsus animalis"),
    "dog bite": ("狗咬伤", "morsus canis"),
    "cat bite": ("猫咬伤", "morsus felis"),
    "snake bite": ("蛇咬伤", "morsus serpentis"),
    "poisoning": ("中毒", "intoxicatio"),
    "choking": ("窒息", "suffocatio"),
    "trauma": ("创伤", "trauma"),
    "asthma": ("哮喘", "asthma"),
    "wheezing": ("喘息", "wheezing"),
    "pneumonia": ("肺炎", "pneumonia"),
    "bronchitis": ("支气管炎", "bronchitis"),
    "tuberculosis": ("结核病", "tuberculosis"),
    "diabetes": ("糖尿病", "diabetes mellitus"),
    "diabetes type 1": ("1型糖尿病", "diabetes mellitus typus 1"),
    "diabetes type 2": ("2型糖尿病", "diabetes mellitus typus 2"),
    "thyroid": ("甲状腺", "glandula thyreoidea"),
    "hyperthyroidism": ("甲状腺功能亢进", "hyperthyreoidismus"),
    "hypothyroidism": ("甲状腺功能减退", "hypothyreoidismus"),
    "heart disease": ("心脏病", "cardiopathia"),
    "coronary artery disease": ("冠心病", "morbi coronarii arteriarum"),
    "heart failure": ("心力衰竭", "insufficientia cardiaca"),
    "arrhythmia": ("心律不齐", "arrhythmia"),
    "atrial fibrillation": ("心房颤动", "fibrillatio atrialium"),
    "kidney disease": ("肾病", "nephropathia"),
    "liver disease": ("肝病", "hepatopathia"),
    "hepatitis": ("肝炎", "hepatitis"),
    "cirrhosis": ("肝硬化", "cirrhosis hepatis"),
    "cancer": ("癌症", "cancer"),
    "tumor": ("肿瘤", "tumor"),
    "malignant": ("恶性", "malignus"),
    "benign": ("良性", "benignus"),
    "ulcer": ("溃疡", "ulcus"),
    "gastritis": ("胃炎", "gastritis"),
    "gastroenteritis": ("胃肠炎", "gastroenteritis"),
    "appendicitis": ("阑尾炎", "appendicitis"),
    "hernia": ("疝气", "hernia"),
    "hemorrhoids": ("痔疮", "haemorrhoides"),
    "piles": ("痔疮", "haemorrhoides"),
    "arthritis": ("关节炎", "arthritis"),
    "osteoarthritis": ("骨关节炎", "osteoarthritis"),
    "rheumatoid arthritis": ("类风湿关节炎", "arthritis rheumatoidea"),
    "gout": ("痛风", "podagra"),
    "osteoporosis": ("骨质疏松症", "osteoporosis"),
    "anemia": ("贫血", "anaemia"),
    "iron deficiency": ("缺铁", "defectus ferri"),
    "vitamin d deficiency": ("维生素D缺乏", "defectus vitaminis D"),
    "cholesterol": ("胆固醇", "cholesterolum"),
    "high cholesterol": ("高胆固醇", "hypercholesterolaemia"),
    "triglycerides": ("甘油三酯", "triglycerida"),
    "stroke risk": ("中风风险", "ictus cerebrovascularis periculum"),
    "dementia": ("痴呆", "dementia"),
    "alzheimer": ("阿尔茨海默病", "morbus Alzheimer"),
    "parkinson": ("帕金森病", "morbus Parkinson"),
    "epilepsy": ("癫痫", "epilepsia"),
    "seizure": ("发作（癫痫）", "epileptica concussio"),
    "migraine headache": ("偏头痛发作", "cephalalgia migrainosa"),
    "pregnancy": ("怀孕", "graviditas"),
    "pregnant": ("怀孕的", "gravida"),
    "miscarriage": ("流产", "abortus spontaneus"),
    "vaginal bleeding": ("阴道出血", "haemorrhagia vaginalis"),
    "morning sickness": ("晨吐", "vomitus matutinus"),
    "labor": ("分娩", "partus"),
    "childbirth": ("分娩", "partus"),
    "menstruation": ("月经", "menstruatio"),
    "menopause": ("更年期", "menopausa"),
    "contraception": ("避孕", "contraceptio"),
    "birth control": ("节育", "anticonceptio"),
    "condom": ("避孕套", "condomus"),
    "sexually transmitted disease": ("性传播疾病", "morbus sexualiter transmissus"),
    "std": ("性传播疾病", "morbus sexualiter transmissus"),
    "hiv": ("艾滋病毒", "HIV"),
    "aids": ("艾滋病", "AIDS"),
    "hospital": ("医院", "hospitalis"),
    "clinic": ("诊所", "clinica"),
    "doctor": ("医生", "medicus"),
    "physician": ("医师", "physicus"),
    "nurse": ("护士", "nutrix"),
    "pharmacist": ("药剂师", "pharmacista"),
    "pharmacy": ("药房", "officina pharmaceutica"),
    "drugstore": ("药店", "officina pharmaceutica"),
    "prescription": ("处方", "praescriptio"),
    "medicine": ("药品", "medicamentum"),
    "medication": ("药物", "medicamentum"),
    "pill": ("药片", "pilula"),
    "tablet": ("片剂", "tabella"),
    "capsule": ("胶囊", "capsula"),
    "ointment": ("药膏", "unguentum"),
    "cream": ("乳膏", "cremor"),
    "drops": ("滴剂", "guttae"),
    "injection": ("注射", "iniectio"),
    "syringe": ("注射器", "syringa"),
    "needle": ("针", "acus"),
    "dressing": ("敷料", "sphacelarium"),
    "bandage": ("绷带", "vitta"),
    "gauze": ("纱布", "carbasus"),
    "suture": ("缝合", "sutura"),
    "stitch": ("缝线", "sutura"),
    "cast": ("石膏", "emplastrum gypsum"),
    "crutches": ("拐杖", "baculi auxiliares"),
    "wheelchair": ("轮椅", "sella curulata ambulatoria"),
    "ambulance": ("救护车", "ambulancia"),
    "emergency room": ("急诊室", "taberna urgentiae"),
    "icu": ("重症监护室", "unitas curae intensivae"),
    "intensive care unit": ("重症监护室", "unitas curae intensivae"),
    "operating room": ("手术室", "cubiculum chirurgicum"),
    "surgery": ("外科手术", "chirurgia"),
    "operation": ("手术", "operatio"),
    "x-ray": ("X光检查", "radiographia"),
    "ct scan": ("CT扫描", "tomographia computata"),
    "mri": ("核磁共振成像", "magneticum resonantiae imaginatio"),
    "ultrasound": ("超声波检查", "ultrasonographia"),
    "blood test": ("验血", "examen sanguinis"),
    "urine test": ("验尿", "examen urinae"),
    "blood pressure": ("血压", "pressio sanguinis"),
    "pulse": ("脉搏", "pulsus"),
    "temperature": ("体温", "temperatura"),
    "heart rate": ("心率", "frequentia cardiaca"),
    "respiratory rate": ("呼吸频率", "frequentia respiratoria"),
    "oxygen saturation": ("血氧饱和度", "saturatio oxygenii"),
    "blood sugar": ("血糖", "glucosum sanguinis"),
    "glucose": ("葡萄糖", "glucosum"),
    "insulin": ("胰岛素", "insulina"),
    "vaccination": ("疫苗接种", "vaccinatio"),
    "vaccine": ("疫苗", "vaccinum"),
    "immunization": ("免疫接种", "immunisatio"),
    "flu shot": ("流感疫苗", "vaccinum influenzae"),
    "covid vaccine": ("新冠疫苗", "vaccinum COVID-19"),
    "rabies": ("狂犬病", "rabies"),
    "malaria": ("疟疾", "malaria"),
    "dengue": ("登革热", "dengue"),
    "yellow fever": ("黄热病", "febris flava"),
    "tetanus": ("破伤风", "tetanus"),
    "chickenpox": ("水痘", "varicella"),
    "measles": ("麻疹", "morbilli"),
    "mumps": ("腮腺炎", "parotitis epidemica"),
    "rubella": ("风疹", "rubella"),
    "polio": ("小儿麻痹症", "poliomyelitis"),
    "common cold": ("普通感冒", "rhinopharyngitis acuta"),
    "influenza": ("流行性感冒", "influenza"),
    "flu": ("流感", "influenza"),
    "coronavirus": ("冠状病毒", "coronavirus"),
    "covid": ("新冠病毒", "COVID-19"),
    "sinus infection": ("鼻窦感染", "sinusitis"),
    "sinusitis": ("鼻窦炎", "sinusitis"),
    "ear infection": ("耳部感染", "otitis"),
    "conjunctivitis": ("结膜炎", "conjunctivitis"),
    "pink eye": ("红眼病", "conjunctivitis"),
    "stye": ("麦粒肿", "hordeolum"),
    "dandruff": ("头皮屑", "pityriasis capitis"),
    "acne": ("痤疮", "acne"),
    "psoriasis": ("牛皮癣", "psoriasis"),
    "eczema": ("湿疹", "eczema"),
    "urinary tract infection": ("尿路感染", "infectio tractus urinarii"),
    "uti": ("尿路感染", "infectio tractus urinarii"),
    "kidney stone": ("肾结石", "calculus renalis"),
    "gallstone": ("胆结石", "calculus biliaris"),
    "bladder infection": ("膀胱感染", "cystitis"),
    "prostate": ("前列腺", "prostata"),
    "erectile dysfunction": ("勃起功能障碍", "dysfunction erectilis"),
    "testicular pain": ("睾丸疼痛", "dolor testicularis"),
    "appendix": ("阑尾", "appendix vermiformis"),
    "herpes": ("疱疹", "herpes"),
    "cold sore": ("唇疱疹", "herpes labialis"),
    "shingles": ("带状疱疹", "herpes zoster"),
    "wart": ("疣", "verruca"),
    "fungal infection": ("真菌感染", "infectio fungalis"),
    "athlete foot": ("脚气", "pedis athletae"),
    "ringworm": ("癣", "tinea"),
    "lice": ("头虱", "pediculi"),
    "scabies": ("疥疮", "scabies"),
    "allergy testing": ("过敏测试", "testis allergiae"),
    "food allergy": ("食物过敏", "allergia ciborum"),
    "peanut allergy": ("花生过敏", "allergia arachis"),
    "milk allergy": ("牛奶过敏", "allergia lactis"),
    "lactose intolerance": ("乳糖不耐受", "intolerantia lactosi"),
    "gluten intolerance": ("麸质不耐受", "intolerantia gluteni"),
    "celiac disease": ("乳糜泻", "morbus coeliacus"),
    "first aid": ("急救", "auxilium primum"),
    "cpr": ("心肺复苏", "reanimatio cardiopulmonalis"),
    "heimlich maneuver": ("海姆立克急救法", "maneuver Heimlich"),
    "antibiotic": ("抗生素", "antibioticum"),
    "antibiotic resistance": ("抗生素耐药性", "resistentia antibiotica"),
    "pain killer": ("止痛药", "analgesicum"),
    "analgesic": ("镇痛剂", "analgesicum"),
    "anti inflammatory": ("消炎药", "antiinflammatorium"),
    "ibuprofen": ("布洛芬", "ibuprofenum"),
    "paracetamol": ("对乙酰氨基酚", "paracetamolum"),
    "acetaminophen": ("对乙酰氨基酚", "acetaminophenum"),
    "aspirin": ("阿司匹林", "acidum acetylsalicylicum"),
    "antihistamine": ("抗组胺药", "antihistaminicum"),
    "steroid": ("类固醇", "steroidum"),
    "corticosteroid": ("糖皮质激素", "corticosteroidum"),
    "insulin": ("胰岛素", "insulina"),
    "inhaler": ("吸入剂", "inhalator"),
    "vitamin": ("维生素", "vitamina"),
    "supplement": ("补充剂", "supplementum"),
    "blood type": ("血型", "typus sanguinis"),
    "blood group": ("血型", "typus sanguinis"),
    "blood donation": ("献血", "donatio sanguinis"),
    "organ transplant": ("器官移植", "transplantatio organi"),
    "dialysis": ("透析", "dialysis"),
    "chemotherapy": ("化疗", "chemotherapia"),
    "radiation therapy": ("放疗", "radiotherapia"),
    "physical therapy": ("物理治疗", "therapia physica"),
    "rehabilitation": ("康复", "rehabilitatio"),
    "counseling": ("心理咨询", "consilium psychologicum"),
    "therapy": ("治疗", "therapia"),
    "treatment": ("治疗", "tractatio"),
    "diagnosis": ("诊断", "diagnosis"),
    "prognosis": ("预后", "prognosis"),
    "symptom": ("症状", "symptoma"),
    "sign": ("体征", "signum"),
    "chronic": ("慢性", "chronicus"),
    "acute": ("急性", "acutus"),
    "bacterial": ("细菌性", "bacterialis"),
    "viral": ("病毒性", "viralis"),
    "infectious": ("传染性", "infectiosus"),
    "contagious": ("传染性", "contagiosus"),
    "epidemic": ("流行病", "epidemia"),
    "pandemic": ("大流行病", "pandemia"),
    "quarantine": ("隔离", "quarantina"),
    "isolation": ("隔离", "isolatio"),
    "medical certificate": ("医疗证明", "certificatum medicum"),
    "prescription refill": ("处方续药", "renovatio praescriptionis"),
    "generic drug": ("仿制药", "medicamentum genericum"),
    "brand name": ("品牌药", "nomen notum"),
    "side effect": ("副作用", "effectus secundarius"),
    "dosage": ("剂量", "dosis"),
    "dosage form": ("剂型", "forma dosis"),
    "over the counter": ("非处方药", "sine praescriptione"),
    "otc": ("非处方药", "sine praescriptione"),
    "medical record": ("病历", "commentarium medicum"),
    "medical history": ("病史", "historia medicorum"),
    "allergy list": ("过敏列表", "index allergiarum"),
    "insurance card": ("保险卡", "cardis assecurationis"),
    "policy number": ("保单号", "numerus consilii"),
    "pre authorization": ("预授权", "praeauctoritas"),
    "direct billing": ("直付", "exsolutio directa"),
    "claim form": ("索赔表", "formula petitionis"),
    "reimbursement": ("报销", "refectio"),
    "deductible": ("免赔额", "deductibile"),
    "co payment": ("自付额", "co-pagamentum"),
    "out of pocket": ("自掏腰包", "ex propria pecunia"),
    "in network": ("网络内医院", "in retis"),
    "out of network": ("网络外医院", "extra retem"),
    "medical evacuation": ("医疗转运", "evacuatio medica"),
    "repatriation": ("遣返", "repatriatio"),
    "second opinion": ("第二诊疗意见", "secundum consilium medicum"),
    "general practitioner": ("全科医生", "medicus generalis"),
    "gp": ("全科医生", "medicus generalis"),
    "specialist": ("专科医生", "specialista"),
    "pediatrician": ("儿科医生", "pediatricus"),
    "obstetrician": ("产科医生", "obstetricius"),
    "gynecologist": ("妇科医生", "gynecologus"),
    "cardiologist": ("心脏科医生", "cardiologus"),
    "neurologist": ("神经科医生", "neurologus"),
    "orthopedic surgeon": ("骨科医生", "chirurgus orthopaedius"),
    "dermatologist": ("皮肤科医生", "dermatologus"),
    "ophthalmologist": ("眼科医生", "ophthalmologus"),
    "psychiatrist": ("精神科医生", "psychiatr"),
    "psychologist": ("心理学家", "psychologus"),
    "dentist": ("牙医", "dentista"),
    "surgeon": ("外科医生", "chirurgus"),
    "anesthesiologist": ("麻醉科医生", "anesthesiologus"),
    "radiologist": ("放射科医生", "radiologus"),
    "pathologist": ("病理科医生", "pathologus"),
    "pharmacy in chinese hospital": ("中国医院的药房", "officina pharmaceutica in hospitali sinensi"),
    "emergency": ("急诊", "urgentia"),
    "medical emergency": ("医疗紧急情况", "urgentia medica"),
    "call 120": ("拨打120", "voca 120"),
    "appointment": ("预约", "constitutum"),
    "consultation": ("会诊", "consultatio"),
    "follow up": ("随访", "sequela"),
    "referral": ("转诊", "recommendatio"),
    "check up": ("体检", "examen medicum generale"),
    "annual physical": ("年度体检", "examen physicum annuum"),
    "health screening": ("健康筛查", "exploratio salutaris"),
    "tcm": ("中医", "medicina tradita Sinensis"),
    "acupuncture": ("针灸", "acupunctura"),
    "herbal medicine": ("草药", "medicamentum herbale"),
    "massage": ("按摩", "massagium"),
    "yoga": ("瑜伽", "yoga"),
    "meditation": ("冥想", "meditatio"),
}

